### ISSUE TITLE
Support `copier update --conflict inline`

### ISSUE THREAD

**Issue by chrisranderson** [copier-org/copier#1000]
**Is your feature request related to a problem? Please describe.**
I was using `copier --vcs-ref "$REF" --defaults --overwrite --conflict inline` to update repos before I knew about `copier update`. I need `copier update` so deletions are applied as well, not just additions/overwriting.

**Describe the solution you'd like**
I want to see inline conflicts when I run `copier update --conflict inline`. Right now I get `Error: Unknown switch --conflict`.

**Describe alternatives you've considered**
- Manually using git to check for deletions between tags in addition to `copier --vcs-ref "$REF" --defaults --overwrite --conflict inline`.

**Additional context**
- My current version: `copier update 7.1.0a0`
- Recent relevant PR: https://github.com/copier-org/copier/pull/971
- I guess I would expect a new release: 7.1.0a1 maybe?

**Comment by yajo** [comment]
The only thing that changed in #971 is that the `--conflict` thing goes after `update` and not before. 

If you're on 7.1.0a1, it's the contrary. But that's alpha so we changed it. 

Does that work for t you?

**Comment by chrisranderson** [comment]
`copier --defaults --overwrite --conflict inline update` works for me, thank you.
