### ISSUE TITLE
`validator`  is not called when value is specified on commandline

### ISSUE THREAD

**Issue by lhupfeldt** [copier-org/copier#1012]
The `validator` action is not called when the parameter is specified with `-d`

I expect the `validator` to be be called regardless where the parameter value came from.

- Inputs should be validated regardless how they were given
- I have automated tests of template using `-d` to expand and just realized the validators were not tested.

**Comment by lhupfeldt** [comment]
Great.

I don't know if this should be left open until #962  is released.

**Comment by yajo** [comment]
Once fixed, we close the issues. Otherwise it's hard to know when it's time to release!

You can install from master if you need it.
