### ISSUE TITLE
Standalone Installer

### ISSUE THREAD

**Issue by RichiCoder1** [copier-org/copier#1026]
**Is your feature request related to a problem? Please describe.**
Create a standalone CLI or installer for copier, independent of `pip`.

**Describe the solution you'd like**
Either a standalone CLI or installer based on [PyInstaller](https://pyinstaller.org/en/stable/index.html)

**Describe alternatives you've considered**
N/A

**Additional context**
Howdy! I really love the concept of copier, but almost no one on our team or company uses Python, as we're mostly a JavaScript/C# team. I'd love to recommend using copier to them, however having to install and go through python is extra steps that they'd rather avoid 😅. Would be great to be able to have a simple installer or executable would make it a lot simpler for devs and CI.

However, I recognize that the setup and CI required to do so may be complex, so this is more of a "nice to have" request.

**Comment by sisp** [comment]
Duplicate of #457.

**Comment by RichiCoder1** [comment]
@sisp ah, apologies! I searched and somehow that issue didn't come up 😅
