### ISSUE TITLE
Local template folder is deleted after copier finishes

### ISSUE THREAD

**Issue by JensRoland** [copier-org/copier#1029]
**Describe the problem**
When using Copier from Python, not via the commandline, and using either `run_copy` or `run_auto` with a local source template and a local destination which are *above* the working directory, Copier will delete the template folder after creating the project in the destination.

**Python script**
This script will reproduce the problem. The template is simply a `copier.yml` file and a folder named `{{project_name}}`, but these must be above the current working directory for the issue to happen.

```python
import os

from copier import run_copy

template_dir = os.path.join(os.path.dirname(__file__), '..', '..', '..', 'template')
destination_dir = os.path.join(os.path.dirname(__file__), '..', '..', '..', 'destination')

run_copy(src_path=template_dir, dst_path=destination_dir, data={
    'project_name': "Foo",
})
```

**To Reproduce**

1. Create a template in `./template`
2. Create the `./destination` folder
3. Save the Python script in a subfolder, e.g. `./scripts/helpers/templating/run_copier.py`
4. Install Copier 7.0.1
5. `cd scripts/helpers/templating`
6. `python run_copier.py`
7. The template folder disappears

**Logs**

<details>
```
Copying from template version None
 identical  .
    create  Foo
    create  Foo/readme.md
```
</details>

**Expected behavior**
The template remains in the file system, unchanged

**Environment**
 - OS: MacOS Ventura on Macbook M1
 - Copier version: copier 7.0.1
 - Python version: 3.9.10
 - Installation method: Poetry

**Additional context**
I believe the problem may have been introduced by PR 802: https://github.com/copier-org/copier/pull/802

See here: https://github.com/copier-org/copier/pull/802/files#diff-f94487dd6380c21ab3fee87440d06676ad5d21d11b04acb8c6b6f4b929e3dde7R199-R212

The Template `_cleanup` method tries to determine, through `_temp_clone` if there is a temporary local clone of the (remote) template, and if so, it deletes it. Somehow, when the template is local, but resides above the CWD in the file system, this cleanup mechanism mistakes it for a temporary clone (the absolute path comparison fails) and the template is deleted.

**Comment by sisp** [comment]
Thanks for reporting this bug, @JensRoland! :pray: I've been able to reproduce it and submitted a PR that fixes it. See #1037.
