### ISSUE TITLE
Copier doesnt find the correct version based on tag using local git repo

### ISSUE THREAD

**Issue by cclecle** [copier-org/copier#1042]
**Describe the problem**
When instantiating template from local git repo, copier fails to find the version based on tag, despite using PEP440 compliant tags.
After some investigation it comes that the problem is actually coming from a project dependency: dunamai.
Dunamai by default needs TAGs to be prefixed with a 'v'. ie: v0.1.2  v1.1.2 ...

I manage to fix it in my own code, but its more a wrokaround.. :
```
dunamai.VERSION_SOURCE_PATTERN = r'''
    (?x)                                                        (?# ignore whitespace)
    ^v?((?P<epoch>\\d+)!)?(?P<base>\\d+(\\.\\d+)*)              (?# v1.2.3 or v1!2000.1.2)
    ([-._]?((?P<stage>[a-zA-Z]+)[-._]?(?P<revision>\\d+)?))?    (?# b0)
    (\\+(?P<tagged_metadata>.+))?\$                             (?# +linux)
'''.strip()

import copier
copier.run_auto("./", "../_gitrepo",vcs_ref="HEAD",use_prereleases=True,defaults=True,cleanup_on_error=False)
```

Then I asked [Dunamai team](https://github.com/mtkennerly/dunamai/issues/61).

They say it is needed to add: `pattern=Pattern.DefaultUnprefixed` to not have this issue.
Is it possible to either add it in dunamai call in template.py:484, or convince them to "fix" it ? 

**Environment**
 - OS: Linux and Windows
 - Copier version: copier-7.0.1-py3-none-any.whl
 - Python version: 3.9+
 - Installation method: pip

**Comment by sisp** [comment]
The pattern [difference is only about the `v` prefix](https://github.com/mtkennerly/dunamai/blob/bf8cb851355d49837d60c007a7bd45d490650439/dunamai/__init__.py#L95-L96). I can't think of any reason why a PEP 440 version tag without a leading `v` should not be supported by Copier. So my :+1: for using `dubamai.Pattern.DefaultUnprefixed`.

**Comment by cclecle** [comment]
thanks ! :)

**Comment by cclecle** [comment]
PR https://github.com/copier-org/copier/pull/1048 created
