### ISSUE TITLE
Add support for mercurial

### ISSUE THREAD

**Issue by vincent-hatakeyama** [copier-org/copier#1051]
**Is your feature request related to a problem? Please describe.**

I need to use mercurial repository as repository containing the template.

I also need to initialize mercurial projects from templates. (it looks like this is something copier is capable of, otherwise it is not needed).

**Describe the solution you'd like**

I’d like both points to be possible.

It does not look like its possible to indicate the branch to use in a git repository, so that would be nice to be able to do too with mercurial templates.

**Describe alternatives you've considered**

The alternative would be to use cookiecutter.

The ability to update a project from a template would be missed thought.

**Comment by yajo** [comment]
Thanks! I knew some day somebody would come up with this! 😆 (Next one will be pijul -- I hope nobody asks for svn or bzr these days).

All Copier's magic is currently very tied to git. Maybe too much indeed. It would be really good if we did this:

1. Abstract out the vcs operations.
2. Implement current Git operations as an implementation of that abstract something.
3. Add mercurial too (this one should be a separate PR).

However I'll close as won't fix for the sake of honesty and to keep the issue tracker clean. FWIW I have no plans to implement this. However, it'd be really nice if somebody wants to propose the PR.
