### ISSUE TITLE
Copier does not create .copier-answers.yml in Azure repos  and .rej files while copier update

### ISSUE THREAD

**Issue by sandeeps311** [copier-org/copier#1055]
**Describe the problem**

Copier does not create .copier-answers.yml in Azure repos while clone project using copier  and .rej files while copier update

**Template**

**To Reproduce**

1. Run `copier ...`
2. run copier azure-repo-url
3..copier-answers.yml is not creating
4. run copier update - .rej file not creating

**Logs**

<details>

```

```

</details>

**Expected behavior**

It should create .copier-answers.yml in repo and .rej file when we are running copier overwrite

**Screenshots/screencasts/logs**

**Environment**
 - OS:  Windows 
 - Copier version:  latest
 - Python version: 3.10
 - Installation method:  

**Additional context**

**Comment by sandeeps311** [comment]
I haven't added {{_copier_conf.answers_file}} previously in template repo
problem is solved now

**Comment by sisp** [comment]
Related to #983.
