### ISSUE TITLE
Copier should support .yaml extension  for .copier-answers.yml

### ISSUE THREAD

**Issue by sandeeps311** [copier-org/copier#1077]
Hi Team,
While using a copier update im getting this error 
**Cannot update because cannot obtain old template references from `.copier-answers.yml`.**
I think copier only supports .yml extension for copier-answers.yml,
Pleas check below code reference 
https://github.com/copier-org/copier/blob/17135c5f346bb2daad32c40ae43f8790ac50c270/copier/main.py#L594

**Comment by ahgraber** [comment]
For additional info, https://copier.readthedocs.io/en/latest/configuring/#answers_file implies that the answers file is user-configurable

**Comment by yajo** [comment]
If you're not using the default file name, then you must provide it with the `-a` flag.

**Comment by sandeeps311** [comment]
It would be nice if you added support for both file extensions ".yml" and ".yaml" because there is no difference in functionality or syntax between the two extensions.

**Comment by yajo** [comment]
Sadly, the YAML project only decided that `.yaml` is the standard file extension after Copier was invented. Thus, we keep this old default. But you can choose a different default as long as you use it in your CLI, if that missing "a" is important for you. 😃
