### ISSUE TITLE
copier 7.1.0 fails on vcs-ref

### ISSUE THREAD

**Issue by hollow** [copier-org/copier#1093]
**Describe the problem**

After upgrading to copier 7.1.0, I cannot use copy or update from a ref/branch.

**To Reproduce**
1. Upgrade to copier 7.1.0
2. Run `copier -r my-branch update`
3. See error

**Logs**

```
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 128
Command line: | /opt/homebrew/bin/git reset --hard my-branch
Stderr:       | fatal: ambiguous argument 'my-branch': unknown revision or path not in the working tree.
```

**Comment by sisp** [comment]
Could you please provide a minimal example for reproducing this problem? It seems there can be a few reasons that lead to this Git error.

**Comment by hollow** [comment]
Take any template and try to initialize from a branch, e.g.:

```
copier -r dependabot/pip/astroid-2.15.3 copy https://github.com/RomainBrault/python-whiteprint.git copier-test
```

**Comment by nytalex** [comment]
same issue here

**Comment by sisp** [comment]
Thanks for providing more details, @hollow. And thanks for tracing down the commit that introduced the regression, @nytalex. This way very helpful.

I've submitted a PR that fixes the bug. See #1115.
