### ISSUE TITLE
Document `tasks` features

### ISSUE THREAD

**Issue by peterwwillis** [copier-org/copier#1095]
**Is your feature request related to a problem? Please describe.**

In the [tasks](https://copier.readthedocs.io/en/stable/configuring/#tasks) sections, there are some examples like:

```
    - [invoke, "--search-root={{ _copier_conf.src_path }}", after-copy]
    # You are able to output the full conf to JSON, to be parsed by your script
    - [invoke, end-process, "--full-conf={{ _copier_conf|to_json }}"]

```

What is `invoke`? What is `after-copy`? What is `end-process`? What are those arguments being passed to? How are these arrays supposed to be used? It's not clear what's going on here. I expected to be able to just pass the name of a program and its arguments, but "invoke" doesn't seem to be the name of a process, and I don't know why "after-copy" and "end-process" are there or what they're doing.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dhirschfeld** [comment]
Just piping up here that I had exactly the same questions and wasted hours searching for the answers before I found this thread.

Without the context of exactly what the arguments are, I think the example just *adds* confusion.

Using some string arguments and some not is also confusing. IIUC it's a YAML "feature" that you don't need to quote strings but IMO it again adds complexity and confusion to the example.

If I actually get `tasks` working I might take it on board to improve the examples in the docs...

**Comment by sisp** [comment]
Sorry for the confusion, @dhirschfeld. Documentation improvements are always most welcome! :pray:

**Comment by dhirschfeld** [comment]
I've got it working now - very simple in the end! :tada:

I think it was the choice of example that made for the confusion. Since `copier` does a copy operation I initially thought the `after-copy` was a `copier` configuration, not just an argument passed to the `invoke` cli.

**Comment by yajo** [comment]
@dhirschfeld would you like to submit an improvement for the docs?

**Comment by dhirschfeld** [comment]
> @dhirschfeld would you like to submit an improvement for the docs?

Sure, happy to take that on board in the next week or so. If you'd like it in sooner someone else may have to pick it up as life is pretty hectic right now :/
