### ISSUE TITLE
Support SourceHut

### ISSUE THREAD

**Issue by jgarte** [copier-org/copier#1096]
**Is your feature request related to a problem? Please describe.**

I'd like to have a shortcut for cloning copier templates from [SourceHut](https://sr.ht/).

**Describe the solution you'd like**

A shortcut like the following:

SourceHut: sr:~namespace/project

sr is a cute shortcut

**Additional context**
https://git.sr.ht/~jmbr/cookiecutter-jax-project

**Comment by yajo** [comment]
I don't plan on adding any more shortcuts, sorry. I don't even like the 2 I have... 😁
