### ISSUE TITLE
More class, less dangling methods

### ISSUE THREAD

**Issue by Yajo** [copier-org/copier#110]
The more I hack into copier, the more I see the code is structured weirdly.

It seems like copier is thought as a library which also lets CLI usage, instead of the other way around.

Since #106, we leverage Plumbum for the CLI stuff, and it feels way more pythonic and comfortable to write it like this.

Now, the `CopierApp` class and its friends feature [the `invoke()` method](https://plumbum.readthedocs.io/en/latest/api/cli.html#plumbum.cli.application.Application.invoke), which should be just enough to let downstream to use Copier as a lib in other python codebases.

If we refactor the codebase to make it more focused on that, we will save the pain to keep on passing arguments here and there. We will easily know if we're updating or copying, know if the user forced the execution, and so on.

---

This is my mind map about what the new object model would be and what information could be obtained from each object:

- [ ] `Answer`: what has been responded to a question. It can be obtained from asking the user, from API call, last answers in the `Subproject`, or defaults from the `Question` (which may be templated). It returns the best match for each `Question`.
- [ ] `Question`: contains a question definition. It is obtained from the `Template`. Each question is related to an answer
- [ ] `Questionary`: contains all questions and helpers to ask to the user.
- [ ] `Template`: available versions, the questionary, local clone location, options defined in the template.
- [ ] `Subproject`: is repo? is dirty? last update version, last answers, local path, folder exists?
- [ ] `Settings`: the evolution of `ConfigData`. It won't require passing through `make_config()` (I always thought that's a weird design). It will hold references to all external settings sources (which are the `Template`, and the API call, and after #235 it will also be user config file). It will *not* hold answers data.
- [ ] `Renderer`: takes care of rendering the files to disk.
- [ ] `Worker`: combines all other objects and has 2 main methods: `copy()` and `update()`.

**Comment by pykong** [comment]
> The more I hack into copier, the more I see the code is structured weirdly.
>
> It seems like copier is thought as a library which also lets CLI usage, instead of the other way around.

I am not sure I can concur, still I am committed to maximum code quality and hence I am open for improvements even radical refactoring required it makes sense.

> the pain to keep on passing arguments here and there. 

Carrying the extensive signatures around is indeed a major pain point which I could not tackle via my last big refactoring.

**TL/DR:** I am open to suggestions/PR. Ideally those should be made/merged before I am going to work on #79 again which could happen in the coming weeks.

**Comment by pykong** [comment]
@Yajo What is your the status of this?
Do you think it to be necessary we still need to further increase the quality of code?
Are there still some things you want to do before releasing `3.0.0.`?

_(There is no fixed release date though. It is done when it's done. :-) )_

**Comment by Yajo** [comment]
#120 improved the situation but it's still a problem. I did a couple of attempts but it's gonna mean a full refactoring, and I don't have resources to do that. I'd be glad to review it or give some insight on it though. Release 3.0.0 has a lot of new features. IMHO this shouldn't be the focus for this release. We should polish them now that they're almost ready.

**Comment by pykong** [comment]
Agreed. The upcoming release `3.0.0` is already quite a fat one.
So let us focus on the user-facing/feature side of things.

**Comment by pawamoy** [comment]
I find the code hard to navigate and reason about. It feels like a top-to-bottom chain of calls, with very small margins of re-usability. Everything is very tied together, sometimes making changes hard to implement (sometimes very easy though :wink: #193).

For example: #197. `make_config` does a lot of things, in a very hard to read / implicit way: lots of arguments, using `locals()` :fearful:, splitting and merging dicts back and forth, etc.

Other functions elsewhere in the code also have lots of arguments, repeated along the call chain.

Both the `cli.copy` and `cli.update` commands use `main.copy` under the hood, which then guesses if we're updating or not using the result of `make_config`: we lost information on the way.

Maybe sharing less code between different functionalities and create smaller re-usable functions with less arguments would help readability, maintenance and enhancements :slightly_smiling_face:. I think the issue title itself summarizes it also pretty well!

Of course I don't know the code as much as you do, @Yajo and @pykong, so please don't take this as a rant but rather as feedback!

**Comment by Yajo** [comment]
Yes, I know, that's exactly the point in this issue. The code is hard to maintain as it is right now. Also, it's impossible to know if an answer comes from `.copier-answers.yml`, from CLI or from user input, which makes it hard to implement things as "don't ask me if I already answered".

This needs a massive refactoring. Luckily, our test suite is big enough to warn us about any problems introduced.

I'd be glad to finish #173 before starting this task, but this one has to go for v4.
