### ISSUE TITLE
Copier not updating/regenerating .pre-commit-config.yaml

### ISSUE THREAD

**Issue by chienandalu** [copier-org/copier#1100]
**Describe the problem**
`.pre-commit-config.yaml` is not being updated (nor regenerated) on successive `copier -f update`.

**Template**

https://github.com/Tecnativa/doodba-copier-template/blob/main/.pre-commit-config.yaml.jinja

**To Reproduce**
1. Populate the template with `copier copy gh:Tecnativa/doodba-copier-template .`. Defaults answers are OK.
1. Commit results with `git add -A` and `git commit --all`.
1. Delete `.pre-commit-config.yaml` file.
1. Commit again, but this time with `git commit --all --amend --no-verify` for avoiding pre-commit.
1. Run `copier -f update`.

**Logs**

<details>

Updating to template version 5.1.4
~/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/template.py:146: OldTemplateWarning: This template was designed for Copier 4.1.0, but your version of Copier is 7.1.0. You could find some incompatibilities.
  warn(
Inicializado repositorio Git vacío en /tmp/copier.main.old_copy.i46tglyy/.git/
pre-commit installed at .git/hooks/pre-commit

Copying from template version 5.1.4
 identical  .
 identical  .editorconfig
 identical  .flake8
 identical  .module-readme.rst.j2
 identical  .vscode
 identical  .vscode/extensions.json
 identical  .vscode/doodba.code-snippets
 identical  devel.yaml
 identical  .docker
 identical  .docker/odoo.env
 identical  .docker/db-access.env
 identical  .docker/db-creation.env
 identical  .pylintrc-mandatory
 identical  .pylintrc
 identical  .gitignore
 identical  tasks.py
 identical  .eslintrc.yml
    create  .pre-commit-config.yaml
 identical  odoo
 identical  odoo/custom
 identical  odoo/custom/entrypoint.d
 identical  odoo/custom/entrypoint.d/.empty
 identical  odoo/custom/build.d
 identical  odoo/custom/build.d/.empty
 identical  odoo/custom/conf.d
 identical  odoo/custom/conf.d/.empty
 identical  odoo/custom/src
 identical  odoo/custom/src/repos.yaml
 identical  odoo/custom/src/addons.yaml
 identical  odoo/custom/src/private
 identical  odoo/custom/src/private/.editorconfig
 identical  odoo/custom/dependencies
 identical  odoo/custom/dependencies/apt_build.txt
 identical  odoo/custom/dependencies/gem.txt
 identical  odoo/custom/dependencies/npm.txt
 identical  odoo/custom/dependencies/apt.txt
 identical  odoo/custom/dependencies/pip.txt
 identical  odoo/custom/ssh
 identical  odoo/custom/ssh/id_rsa.pub
 identical  odoo/custom/ssh/config
 identical  odoo/custom/ssh/known_hosts
 identical  odoo/custom/ssh/id_rsa
 identical  odoo/Dockerfile
 identical  odoo/.dockerignore
  conflict  .copier-answers.yml
 overwrite  .copier-answers.yml
 identical  prod.yaml
 identical  LICENSE
 identical  common.yaml
 identical  .prettierrc.yml
 identical  setup-devel.yaml
 identical  test.yaml
 identical  README.md
 identical  .isort.cfg

 > Running task 1 of 2: invoke after-update
 > Running task 2 of 2: invoke develop
Reinicializado el repositorio Git existente en /home/pbaeza/temp/.git/
pre-commit installed at .git/hooks/pre-commit

Inicializado repositorio Git vacío en /tmp/copier.main.new_copy.x84j6am6/.git/
pre-commit installed at .git/hooks/pre-commit

</details>

**Expected behavior**
`.pre-commit-config.yaml` is regenerated. I detected the problem because several of the library versions were found in the file, and then investigated, it leads to the non updating of the file. As I think this way of reproducing is faster, I put it, but it can be similar changing manually the file and doing the copier update.

The log says that creates the file, but it later disappears.

**Environment**
 - OS: Ubuntu Linux 22.04
 - Copier version: 7.1.0
 - Python version: 3.10.6
 - Installation method: pipx

**Comment by carlosdauden** [comment]
+

**Comment by sisp** [comment]
I think this behavior is correct. In step 3, you delete the `.pre-commit-config.yaml` file in the generated project. When you run `copier -f update`, the generated project is updated using the latest version of the template. But you removed `.pre-commit-config.yaml`, and the update algorithm respects this change and keeps the file deleted.

The logic is essentially:
1. Compute the changes you made after generating the project using the _old_ template.
2. Generate a fresh project using the _new_ template.
3. Apply your changes on top of that new fresh project.

See the docs for more [details of the update algorithm](https://copier.readthedocs.io/en/v7.1.0/updating/#how-the-update-works).

In case you're wondering, the `-f` flag is merely a shortcut for `--defaults --overwrite`. It won't recreate a file that is present in the template that you explicitly deleted in the project afterwards.

**Comment by yajo** [comment]
Welcome around! 

Yes, it seems copier is respecting your changes where you were expecting it to replace them. If that's what you want, just copy again instead of updating. 

    copier -f copy gh:Tecnativa/doodba-copier-template .

I'll close because it doesn't seem a bug here, but please reopen if needed.
