### ISSUE TITLE
Answers file configuration in Settings ignored

### ISSUE THREAD

**Issue by Daemo00** [copier-org/copier#1150]
### Describe the problem

The configuration `_answers_file` is ignored in `copier.yaml`, so the previously chosen answers are not proposed.

### Template

https://github.com/Daemo00/Python-Package-Template-using-Copier/tree/7c882c03972a41d9007d4463f64bfd05e57ad608

### To Reproduce

1. Clone the template
2. Run
    ```shell
    copier --vcs-ref=7c882c03972a41d9007d4463f64bfd05e57ad608 copy https://github.com/Daemo00/Python-Package-Template-using-Copier MyPackage
    ```
    The only required field is the Package name
4. Run the same command again

### Expected behavior

The previously chosen answers are proposed.

### Screenshots/screencasts/logs

[Screencast from 2023-05-21 22-25-05.webm](https://github.com/copier-org/copier/assets/23295253/83690abe-4aec-411c-a6e1-b8dac58810f7)

### Operating system

Linux

### Operating system distribution and version

Ubuntu 23.04

### Copier version

copier 7.2.0

### Python version

Python 3.11.2

### Installation method

pipx+pypi

### Additional context

It works if the answers file is provided explicitly:
```shell
copier --answers-file .copier-answers.yaml --vcs-ref=7c882c03972a41d9007d4463f64bfd05e57ad608 copy https://github.com/Daemo00/Python-Package-Template-using-Copier MyPackage
```

It is similar to https://github.com/copier-org/copier/issues/876, and I have read the answer there that points to https://copier.readthedocs.io/en/stable/configuring/#applying-multiple-templates-to-the-same-subproject; but maybe here the issue is a bit different: the template is declared in the above command, so `copier` should be able to retrieve the relative path of the answers file from the configuration `_answers_file` in `.copier.yaml`.

**Comment by yajo** [comment]
You could do this if you want to recopy:

    copier recopy -a .copier-answers.yaml

Or you could do this if you want to update:

    copier update -a .copier-answers.yaml

So your use case is a bit weird. Why do you want to copy it again?

**Comment by Daemo00** [comment]
`recopy` is not available for the version `7.2.0` I was using in this issue.
Anyway I tried again with `8.0.0` and nothing has changed: I only have to use the UNSAFE flag and move some options around.
`update` is ok too, but the point is that I would like to not specify the answers file each time.

Using `copy` again is the only way I could think of in order to not always specify the answers file as argument of every command.
Since I am providing the template explicitly (it is an argument of the `copy` command), `copier` should know that the provided template is using a particular file for the answers and that should be used for providing default values.

I understand that other commands like `update` need to know where the answers file is because they don't have any information about the template, but I think `copy` might be smarter and look for the answers file configured in the template it is copying.

**Comment by pawamoy** [comment]
> update is ok too, but the point is that I would like to not specify the answers file each time.

You don't have to. If your answer file is named and located as expected by Copier, you can just run `copier update`.

> Since I am providing the template explicitly (it is an argument of the copy command), copier should know that the provided template is using a particular file for the answers and that should be used for providing default values.

That's the case. Not sure how you got the opposite impression :confused: 

> I understand that other commands like update need to know where the answers file is because they don't have any information about the template

They don't, and they do. As mentioned previously, if you followed the docs and named/located your answer file as Copier expects it, you don't have to give its path when updating.

> but I think copy might be smarter and look for the answers file configured in the template it is copying.

It sounds like you're expecting Copier to find previous answers in... the template itself? That is not how Copier works. You generate a project a first time, answering *all* questions, and their answers are recorded within the generated project. Then, when you update, Copier gets the previous answers and reuses them.

**Comment by yajo** [comment]
> `update` is ok too, but the point is that I would like to not specify the answers file each time.

You just have to use the default answers name. If you use the default, then you don't need to specify a different one.

Otherwise, how would Copier know which template are you updating from?

**Comment by Daemo00** [comment]
I'm sorry if I haven't been able to explain myself clearly, I'll try again from the beginning 😄

I have created the linked template that in its configuration states a particular name for the answers file: https://github.com/Daemo00/Python-Package-Template-using-Copier/blob/7c882c03972a41d9007d4463f64bfd05e57ad608/copier.yaml#L34

I'd like to be able to _update_ (with `update` or other commands) any project created by that template when the template changes, without specifying the answers file name each time.

I understand that, in order to do that, `copier` must be provided the information of the answers file name, so that it can retrieve the answers.
This information usually comes from the parameter `-a` (that is what was suggested in https://github.com/copier-org/copier/issues/1150#issuecomment-1585564330).

I think that the same information (the answers file name) could also be retrieved by `copier` from the template, because it is in the template's configuration file.

The only command (that I know of) that allows the template as an argument is `copy`, so I tried it as described in the issue, but didn't work as expected.

**Comment by Daemo00** [comment]
> Otherwise, how would Copier know which template are you updating from?

Just a few seconds late, I think the answer is
> I think that the same information (the answers file name) could also be retrieved by `copier` from the template, because it is in the template's configuration file.
>
> The only command (that I know of) that allows the template as an argument is `copy`, so I tried it as described in the issue, but didn't work as expected.

**Comment by yajo** [comment]
OK, now I think we're getting to it 😆 



> The only command (that I know of) that allows the template as an argument is `copy`

That is indeed because `copy` is for copying from scratch. Thus, it needs to know where's the template you want to copy and where do you want to copy it.

`recopy` and `update` don't need you to tell where is the template, because they already know where you copied it from last time, because when you ran `copy`, that info got written in the answers file. Thus, those 2 commands need to have a preexisting answers file to work.

Now you have to understand one killer feature: Copier allows applying multiple templates to the same project. For example, [here you have one example of a project that has 2 different answer files because it has 2 templates applied to it](https://gitlab.com/moduon/moduon-odoo-addons/-/tree/a7dfb79a00706e56ad0a9e3f919f28dc67da5295)), and each template does its thing separately. This works perfectly and is required by design.

So, summarizing, to update or recopy, Copier needs an answers file. But in a project you can have more than one answer files.

So, if you just run `copier update`, how will Copier know which copier answers file to use? Simple: it will always use `.copier-answers.yml` if you don't specify it.

So you can either specify the answers file name always when updating/recopying, or use the default name.

**Comment by pawamoy** [comment]
Yep, thanks @Daemo00 for clearing things up :slightly_smiling_face: 
I guess it boils down to this:

> I think that the same information (the answers file name) could also be retrieved by copier from the template, because it is in the template's configuration file.

IIUC, that would require passing the path to the template each time you update instead of the path to the answers file. Not really better :smile:!

I definitely recommend using the default path and name for the answers file, so that Copier finds it automatically, and therefore you don't have to specify it on the command line each time you update :slightly_smiling_face:

**Comment by Daemo00** [comment]
> That is indeed because `copy` is for copying from scratch. Thus, it needs to know where's the template you want to copy and where do you want to copy it.

But then why does
```
copier --answers-file .copier-answers.yaml --vcs-ref=7c882c03972a41d9007d4463f64bfd05e57ad608 copy https://github.com/Daemo00/Python-Package-Template-using-Copier MyPackage
```
find the answers that are in `MyPackage`?
Just curious, because this looked to somehow support my idea to use the `copy` command to _update_ the project.

> Now you have to understand one killer feature: Copier allows applying multiple templates to the same project. For example, [here you have one example of a project that has 2 different answer files because it has 2 templates applied to it](https://gitlab.com/moduon/moduon-odoo-addons/-/tree/a7dfb79a00706e56ad0a9e3f919f28dc67da5295)), and each template does its thing separately. This works perfectly and is required by design.

Got it, so what I expected is not going to work by design; I was afraid so, I'm closing the issue and thanks anyway for your time 😄

> that would require passing the path to the template each time you update instead of the path to the answers file. Not really better :smile:!

That's True, but I expected both to work the same way.
It also depends on what someone believe is _better_; maybe I prefer to remember the template I want to apply instead of the name of the answers file it uses.

Could we at least provide a fallback to `.copier-answers.yaml` after `.copier-answers.yml`?
After all, https://yaml.org/faq.html itself says
> Please use ".yaml" when possible.

**Comment by pawamoy** [comment]
I agree that supporting both extensions would be nice. The config file itself supports both: https://copier.readthedocs.io/en/stable/configuring/#the-copieryml-file.

**Comment by yajo** [comment]
> I agree that supporting both extensions would be nice. The config file itself supports both: https://copier.readthedocs.io/en/stable/configuring/#the-copieryml-file.

That can be done, yes.



> After all, https://yaml.org/faq.html itself says
> 
> > Please use ".yaml" when possible.

FWIW, that FAQ didn't exist when Copier acquired its ability to use an answers file. At least, I searched for that standard actively and couldn't find it.



> But then why does
> 
> ```
> copier --answers-file .copier-answers.yaml --vcs-ref=7c882c03972a41d9007d4463f64bfd05e57ad608 copy https://github.com/Daemo00/Python-Package-Template-using-Copier MyPackage
> ```
> 
> find the answers that are in `MyPackage`? Just curious, because this looked to somehow support my idea to use the `copy` command to _update_ the project.

Like any other config param, `_answers_file` can be templated. This is a valid questionary:

```yaml
_answers_file: .{{ woohoo }}.copier-answers.yml
woohoo: "😃"
```

Thus, to obtain that value, Copier must first process the questionary. Unless, of course, you hardcode the value using `-a` on the CLI call.
