### ISSUE TITLE
Allow skipping file chunks

### ISSUE THREAD

**Issue by NewbiZ** [copier-org/copier#1153]
### Actual Situation

`copier` is able to either consider a file for update, or skip it. This is handled on a per-file basis with `skip_if_exists`.

This works well and is very handy for files that are generated once and will most probably never need to be updated again. 

### Desired Situation

It often happens that only _parts_ of a file would need to be skipped, while the rest should be considered for update. This happens when some configuration files cannot be split.

A typical example is the `pyproject.toml`, which AFAIK cannot be split in multiple subfiles:

- Most of the file would likely need to be considered for updates, as usual.
- But some parts, like the `[tool.pylint]` section very often contains project-specific exclusion rules that should not be reverted.
- The same applies for `[tool.mypy]`, etc

I guess the canonical example is the code coverage percent configuration. I would typically set it at 100% for a freshly generated template, but very often it would get tailored after the fact by each project to be e.g. 80%. I currently cannot convey to `copier` that the whole `pyproject.toml` should be considered for update _except_ some lines which would likely be updated for each project.

This is kind of annoying because it makes each project update a game of cat and mouse between the updates that are legitimate and the updates that should not be considered. 

### Proposed solution

I would propose that `copier` accepts markers inside templates to convey that a portion of the file should be skipped upon update.

Let's imagine the following `pyproject.toml jinja`:

    [project]
    name = {{ project_name }}

    [tool.pylint]
    {{ copier_skip_start(pylint-coverage, '#') }}
    coverage = 100
    {{ copier_skip_stop(pylint-coverage, '#') }}

That would generate the following:

    [project]
    name = myproject

    [tool.pylint]
    # copier_skip_start: pylint-coverage
    coverage = 100
    # copier_skip_stop: pylint-coverage

Upon updating that file and comparing against the current project, `copier` would then be able to ignore bits in between the `copier_skip_start`/`copier_skip_stop` parts, while matching them against their `id` (`pylint-coverage` here)

**Comment by NewbiZ** [comment]
I was confused as to how `copier` works.

With the migration system, once an update on a file has been done, and the result committed, these will not be reapplied upon update unless the template changes that file.

This issue is not relevant, sorry for the confusion on my side, great work with `copier`.

**Comment by oskarryn** [comment]
I think it's still relevant because `copier update` won't try to overwrite if the template file is unchanged, but it would try if other parts of the file changed.

For example, if you change something different than coverage in toml, then you will have to pick that change and manually ignore the coverage. Ideally, there would be no conflict and coverage would be ignored while the new change gets added.

**Comment by pawamoy** [comment]
@oskarryn sorry, I have trouble understanding what you mean exactly. If you think there's an issue with Copier, or possible enhancements, could you open a new issue and describe your use case precisely?
