### ISSUE TITLE
Don't require users to review all questions when running copier update

### ISSUE THREAD

**Issue by drewoldag** [copier-org/copier#1178]
### Actual Situation

When someone runs `copier update`, they have to review all of the responses that they have provided in their answers file. People get kind of blind to these responses and just return through the list as fast as possible. 

### Desired Situation

It would be nice if there was an argument that would take all the previous responses found in the answers file and only present the user with new template questions that were added after the hydrated project was created. 

### Proposed solution

I have no technical solution, but an initial questions like this would be amazing. (Actual wording should be improved.) 
```
>> Would you like an interactive update?
          Full interaction - review previous answers
    >> Some interaction - use previous answers, show me new questions
          No interaction - show no questions, just take previous answers and default values for new questions
```

**Comment by sisp** [comment]
I like the idea. :+1: I'd use a switch though, e.g. `copier update --keep-answers` (just an idea, to be discussed) and `--defaults` might be added to use default answers for new questions.

**Comment by yajo** [comment]
Using `--defaults`, any question without a default value will be asked. Does that solve your problem?

**Comment by drewoldag** [comment]
`--defaults` would be fine, but I like the clarity of the `--keep-answers` flag. 

At the end of the day, it would just be nice not to be forced to review all the prior responses when updating :)

**Comment by yajo** [comment]
Maybe, but `--keep-answers` is a bit absurd as a flag name. Answers are always kept on updates and recopies. Something like `--skip-answered` or `--ask-only-new-questions` makes more sense.

I don't have plans to implement this, but any PR would be welcome.
