### ISSUE TITLE
_subdirectory with template crashes

### ISSUE THREAD

**Issue by AntoineD** [copier-org/copier#1182]
### Describe the problem

Using `_subdirectory` with a template value crashes on template copy.

### Template

This can be reproduced with the example from the [doc](https://copier.readthedocs.io/en/stable/configuring/#skip_if_exists):
```yaml
_subdirectory: "{{ python_engine }}"
python_engine:
    type: str
    choices:
        - poetry
        - pipenv
```

### To Reproduce

`copier copy <path to template> .`

### Logs

```console
❯ copier copy <path to template> .
🎤 python_engine
   poetry

Copying from template version None
 identical  .
Traceback (most recent call last):
  File "/home/ad/.local/bin/copier", line 8, in <module>
    sys.exit(copier_app_run())
             ^^^^^^^^^^^^^^^^
  File "/home/ad/.local/pipx/venvs/copier/lib64/python3.11/site-packages/plumbum/cli/application.py", line 639, in run
    inst, retcode = subapp.run(argv, exit=False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ad/.local/pipx/venvs/copier/lib64/python3.11/site-packages/plumbum/cli/application.py", line 634, in run
    retcode = inst.main(*tailargs)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/ad/.local/pipx/venvs/copier/lib64/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ad/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/cli.py", line 66, in handle_exceptions
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ad/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/cli.py", line 243, in main
    ).run_copy()
      ^^^^^^^^^^
  File "/home/ad/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/main.py", line 740, in run_copy
    self._render_folder(src_abspath)
  File "/home/ad/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/main.py", line 637, in _render_folder
    for file in src_abspath.iterdir():
  File "/usr/lib64/python3.11/pathlib.py", line 931, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/<path to template>/poetry'
```

### Expected behavior

The project is created.

### Operating system

Linux

### Operating system distribution and version

Fedora 37

### Copier version

8.0.0

### Python version

3.11

### Installation method

pipx+pypi

**Comment by pawamoy** [comment]
Can you show the file tree of your template? Looks like the `poetry` directory simply does not exit. If you're working on the template, have you tried `copier copy -r HEAD /path/to/template .`?

**Comment by AntoineD** [comment]
I had a typo on the `poetry` directory name, sorry about that!
But actually I chose this example because its behavior (wongly) matched the issue I had.

Here is an template directory that has the issue:
```console
❯ tree
.
├── copier.yml
└── {{ name }}
    └── toto
❯ cat copier.yml 
name:
    type: str
_subdirectory: "{{ name }}"
```

then:
```console
❯ copier copy -r HEAD <path to template> .
🎤 name
   x

Copying from template version None
 identical  .
Traceback (most recent call last):
  File "/home/ad/.local/bin/copier", line 8, in <module>
    sys.exit(copier_app_run())
             ^^^^^^^^^^^^^^^^
  File "/home/ad/.local/pipx/venvs/copier/lib64/python3.11/site-packages/plumbum/cli/application.py", line 639, in run
    inst, retcode = subapp.run(argv, exit=False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ad/.local/pipx/venvs/copier/lib64/python3.11/site-packages/plumbum/cli/application.py", line 634, in run
    retcode = inst.main(*tailargs)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/ad/.local/pipx/venvs/copier/lib64/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ad/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/cli.py", line 66, in handle_exceptions
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ad/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/cli.py", line 243, in main
    ).run_copy()
      ^^^^^^^^^^
  File "/home/ad/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/main.py", line 740, in run_copy
    self._render_folder(src_abspath)
  File "/home/ad/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/main.py", line 637, in _render_folder
    for file in src_abspath.iterdir():
  File "/usr/lib64/python3.11/pathlib.py", line 931, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/<path to template>/x'
```

**Comment by pawamoy** [comment]
I don't see the use-case behind having a variable subdirectory name.  The user chooses the name of the destination folder when generating a project. So the subdirectory name has no importance. Your example is equivalent to naming the subdirectory `project` and setting the value of `_subdirectory` to `"project"` in copier.yml. WDYT?

**Comment by pawamoy** [comment]
> would have someprefix-{{ name }} instead of {{ name }}

You mean for the `_subdirectory` value? But what about the actual subdirectories? What are their names? Is your template public so I can take a look?

**Comment by AntoineD** [comment]
OK, this is not my actual root issue, please let me backpedal once again. >_<

My root issue is with using `copier update`, for which I was expecting `_subdirectory` to be the solution, but anyway here is my issue:
```console
❯ tree template
.
├── copier.yml
└── prefix-{{name}}
    ├── {{_copier_conf.answers_file}}.jinja
    └── foo
❯ cat template/copier.yml                  
name:
  type: str

```
the file `foo` is empty and `{{_copier_conf.answers_file}}.jinja` created following the docs.

Then create a project from the template
```console
❯ copier copy template .    
No git tags found in template; using HEAD as ref
🎤 name
   x

Copying from template version 0.0.0.post2.dev0+4d57457
 identical  .
    create  prefix-x
    create  prefix-x/.copier-answers.yml
    create  prefix-x/foo
❯ tree prefix-x/
prefix-x/
└── foo
```

Then change the content of `foo` to whaterver and run
```console
❯ copier update prefix-x 
/home/ad/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/vcs.py:179: DirtyLocalWarning: Dirty template changes included automatically.
  warn(
No git tags found in template; using HEAD as ref
Updating to template version 0.0.0.post3.dev0+3bafaed
🎤 name
   x

Copying from template version 0.0.0.post3.dev0+3bafaed
 identical  .
    create  prefix-x
    create  prefix-x/.copier-answers.yml
    create  prefix-x/foo
❯ tree prefix-x/
prefix-x/
├── foo
└── prefix-x
    └── foo
❯ cat prefix-x/prefix-x/foo 
XX
```

The updated `foo` is created into a nested `prefix-x`.

**Comment by pawamoy** [comment]
First, I'm not sure that generating a project from a template *into the template* itself is a good idea, but maybe I'm wrong and this is a supported use-case.

Then, the behavior you witness is expected: you are running an update while giving `prefix-x` as destination. So the project is updated from the current directory *into prefix-x*. Therefore you get a nested prefix-x/prefix-x.

If what you wanted to do is do a partial update of just the prefix-x directory, that is not supported. Updates are always complete: they update the whole project, not just a part of it.

So instead of `copier update prefix-x`, simply try `copier update`.

**Comment by pawamoy** [comment]
There's no way to enforce the name of the generated project's root directory I'm afraid. The user always chooses the destination path, whether it's `.` (and in that case they created the current directory anyway) or `whatever`.
