### ISSUE TITLE
After update to 8.0.0 copier does not work with jinja extensions

### ISSUE THREAD

**Issue by lazarvgd** [copier-org/copier#1185]
### Describe the problem

I have updated copier version to 8.0.0, and when I run `copier copy <dst_dir> <src_dir>`, and I get the error:

```
/Users/<my_user>/Library/Python/3.9/lib/python/site-packages/copier/vcs.py:179: DirtyLocalWarning: Dirty template changes included automatically.
  warn(
Template uses unsafe features: jinja_extensions, tasks
```

If I change the version to 7.2.0, everything works fine. 
Can you please advice and point me how to fix this issue?

thanks

### Template

n/a

### To Reproduce

1. copier copy <dst_dir> <src_dir>

### Expected behavior

The behaviour should be the same as it was with version 7.2.0, copier was able to perform copy command successfully.

### Operating system

macOS

### Operating system distribution and version

13.4 (22F66)

### Copier version

8.0.0

### Python version

Python 3.9.6

### Installation method

pip+git

**Comment by sisp** [comment]
Copier v8 introduced a new flag `--UNSAFE` which is required when a template uses unsafe features to opt-in to allowing such potentially dangerous templates. Please see the [release log](https://github.com/copier-org/copier/releases/tag/v8.0.0) and a related [discussion](https://github.com/orgs/copier-org/discussions/1174) as well as [post-merge discussion](https://github.com/copier-org/copier/issues/1137#issuecomment-1576135992).

**Comment by sisp** [comment]
I'll close this issue because I think I've answered your question. But feel free to get back in case something is still unclear.

**Comment by lazarvgd** [comment]
Thanks for the answer. :)
