### ISSUE TITLE
Support hidden variables without user prompt/input

### ISSUE THREAD

**Issue by lhupfeldt** [copier-org/copier#1205]
### Actual Situation

In version 7 you could use `when: false` to set temporary variables without prompting the user. This feature is not available i version 8, see  #1175.

### Desired Situation

Functionality similar to `when: false` is restored

### Proposed solution

Introduce a new flag e.g. `hidden: true`
There must be a default value set in config.
Values will not be stored so will always be calculated based on static or Jinja template defaults.

**Comment by sisp** [comment]
What do you think about #1203?
