### ISSUE TITLE
Error: Unknown switch -f in 8.0.0

### ISSUE THREAD

**Issue by ap-wtioit** [copier-org/copier#1213]
### Describe the problem

Running copier with `copier -f` doesn't work in 8.0.0

### Template

None

### To Reproduce

1. Run `copier -f`

### Logs

```console
Error: Unknown switch -f
------
copier 8.0.0

Create a new project from a template.

Docs in https://copier.readthedocs.io/

WARNING! Use only trusted project templates, as they might execute code with the
same level of access as your user.


Usage:
    copier [SWITCHES] [SUBCOMMAND [SWITCHES]] args...

Hidden-switches:
    -h, --help         Prints this help message and quits
    --help-all         Prints help messages of all sub-commands and quits
    -v, --version      Prints the program's version and quits

Sub-commands:
    copy               Copy from a template source to a destination.; see
                       'copier copy --help' for more info
    recopy             Recopy a subproject from its original template; see
                       'copier recopy --help' for more info
    update             Update a subproject from its original template; see
                       'copier update --help' for more info
```

### Expected behavior

Copier --help-all states -f still exists:
```
 -l, -f, --defaults              Use default answers to questions, which
                                    might be null if not specified.
```

so it should work

### Operating system

Linux

### Operating system distribution and version

Ubuntu 22.10

### Copier version

copier 8.0.0

### Python version

Python 3.7.3

### Installation method

pipx+pypi

**Comment by ap-wtioit** [comment]
`-l` and `--defaults` give the same error message

**Comment by ap-wtioit** [comment]
Figured it out. I missed the introduction of sub commands. I need to run `copier update -f`.

The documentation here should also be updated:
https://pypi.org/project/copier/8.0.0/

![image](https://github.com/copier-org/copier/assets/38032588/483004d9-adf4-497f-8656-d87785a1b952)

**Comment by pawamoy** [comment]
That is expected and was listed in the breaking changes: flags are now passed to subcommands, like `copier update -f`. See the v8 remease notes :)
