### ISSUE TITLE
Copier update fails if git gpg commit signing is enabled globally

### ISSUE THREAD

**Issue by scmmmh** [copier-org/copier#1224]
### Describe the problem

If signing git commits is enabled globally for a user using `git config --global commit.gpgsign true`, then running `copier update` fails with the error "error: gpg failed to sign data". This is caused by `copier/main.py` in lines 917-928, where user name and email are set and then a commit is attempted. Since there is no GPG key for the given e-mail address GPG cannot sign the commit and the update process fails in line 926.

### Template

Error is template-agnostic.

### To Reproduce

1. Run `git config --local commit.gpgsign true`
2. In a project created using `copier copy` run `copier update`
3. Update fails with `error: gpg failed to sign the data`

### Expected behavior

The update is applied

### Operating system

Linux

### Operating system distribution and version

Ubuntu 23.04

### Copier version

8.0.0

### Python version

CPython 3.11

### Installation method

pipx+pypi

**Comment by sisp** [comment]
I believe #856 is related but abandoned. It would be great to finish that work.

**Comment by scmmmh** [comment]
Looking at #856, that definitely looks as if that would fix my bug, as that is essentially the workaround I'm currently applying.

**Comment by sisp** [comment]
Great! Would you be interested in working on a PR that finishes what was started in #856?

**Comment by scmmmh** [comment]
What is there that remains to be done? As far as I can see there is just one failing check, but I can't see why it failed anymore.

**Comment by sisp** [comment]
It looks like it was complete but didn't get merged for some reason. Since then, the code base has evolved, there are merge conflicts and probably new tests that need this extra Git config command as well. It should be quite straightforward to replicate #856 for the current state of the project.

**Comment by scmmmh** [comment]
I am happy to pitch in, but I currently can't make any promises as to when I will find time for it.

**Comment by sisp** [comment]
I've been thinking about this issue and #856 a little more and dislike the many added Git config lines in the tests of #856. So why were they added? Because the test suite fails for developers with GPG commit signing enabled, and that's because the repo/global/system Git config affects Copier's _internal_ usage of `git`, e.g. in the update algorithm. I believe we should differentiate between two Git usage scenarios in Copier:

1. Programmatic usage of `git` respecting user's configs. This is needed for cloning a template, e.g. when the Git project is private and the user has configured credentials or an SSH key.
2. Internal usage of `git`, e.g. the update algorithm.

For 2., we should make `git` ignore any config files and, thus, run it in full isolation of the user's environment. I think this is possible, see e.g. https://stackoverflow.com/a/67512433.

WDYT, @copier-org/maintainers?

**Comment by sisp** [comment]
It looks like this would be quite straightforward to do if we raised the minimum required `git` version to v2.32.0 two new environment variables `GIT_CONFIG_SYSTEM` and `GIT_CONFIG_GLOBAL` were introduced in this release (https://github.com/git/git/commit/4179b4897f2de28858acaebd6382c06c91532e98). Before, running in `git` in a sanitized environment requires unsetting `HOME` and `XDG_CONFIG_HOME` which is likely to have negative side effects, e.g. when pre-commit hooks are registered that (for some reason) use those environment variables.

**Comment by scmmmh** [comment]
If I remember correctly, the code already tries to run the git commands with `--no-verify`, so that shouldn't be a problem.

**Comment by sisp** [comment]
Only the second commit but not the first, which is intended to run Git hooks:

https://github.com/copier-org/copier/blob/34daebbd7cedf142af60468eb118909eefbae16f/copier/main.py#L923-L926

**Comment by scmmmh** [comment]
Yes, but if I understand how plumbum works correctly, then the first command can fail and will not throw an exception (due to the `retcode=None`). I don't understand the code well enough to determine if it is an issue, if the first commit fails, but the second succeeds.

**Comment by yajo** [comment]
El sáb., 1 jul. 2023 16:50, Sigurd Spieckermann ***@***.***>
escribió:

> For 2., we should make git ignore any config files and, thus, run it in
> full isolation of the user's environment. I think this is possible, see
> e.g. https://stackoverflow.com/a/67512433.
>
> WDYT, @copier-org/maintainers
> <https://github.com/orgs/copier-org/teams/maintainers>?
>

Good idea!

>

**Comment by sisp** [comment]
@yajo I realized this would need `git` v2.32.0+. https://github.com/copier-org/copier/issues/1224#issuecomment-1624221904

**Comment by yajo** [comment]
I don't think this is a requirement, but a recommendation. Older Git won't react to that env variable, and that's totally fine. If you don't have gpg enabled, you can still work as normal.

Another option is forget about that and just add the `--no-gpg-sign` flag wherever needed. I don't think this would be too complicated honestly.
