### ISSUE TITLE
Add a bit more info for unsafe features

### ISSUE THREAD

**Issue by mitchnegus** [copier-org/copier#1269]
### Actual Situation

I just upgraded from Copier 7.2 to 8.1, and got "bitten" by the safety measures that were implemented in that change (the `--UNSAFE` and `--trust` options). I actually think this is a great idea, especially going with the `--trust` option as an alternative to `--UNSAFE`, but might suggest adding a note to the error message to help those encountering this issue in the future. Right now, I just got an error that 

```
Template uses unsafe feature: tasks
```

I had to dig through the CHANGELOG (fine; it showed the issue, but didn't really give motivation for why my previously trusted template was now doing something "unsafe") and then dig further until I came across issue #1137 (and corresponding PR). 

### Desired Situation & Proposed Solution

To avoid that legwork for each user, perhaps that error could just be changed to note that users who trust their templates should run with either the `--UNSAFE` or `--trust` option if they trust the template? Looks like this might be as simple as changing [line 109 in `copier.errors.py`](https://github.com/copier-org/copier/blob/a9e7b6ba3c9ae3fca6606eb8ae22e7da52b2d69d/copier/errors.py#L109) to be something like:

```python
super().__init__(
    f"Template uses potentially unsafe feature{s}: {', '.join(features)} \n"
    "If you trust this template, consider adding the `--trust` option when running `copier copy`."
)
```

Thanks for all your hard work, seems like an awesome tool so far!

**Comment by sisp** [comment]
I like it! :+1: Just a minor suggestion: I think just stating `copier copy` may be misleading when seeing this message during `copier update`, so how about changing it like this?

```diff
 super().__init__(
     f"Template uses potentially unsafe feature{s}: {', '.join(features)} \n"
-    "If you trust this template, consider adding the `--trust` option when running `copier copy`."
+    "If you trust this template, consider adding the `--trust` option when running `copier copy/update`."
 )
```

**Comment by mitchnegus** [comment]
Sounds good! See #1280.
