### ISSUE TITLE
Templates created via VCS-ref HEAD cannot update properly

### ISSUE THREAD

**Issue by OverkillGuy** [copier-org/copier#1305]
### Describe the problem

Creating a repo from template, using the `--vcs-ref HEAD` flag, say for `v1.1.0-8-xyz` (8th commit after tag `v1.1.0`) fails to `copy update`, as the version of template is not detected properly, causing a fail to clone/checkout tag.

I assume that this is happening on all `--vcs-ref` that aren't git tags, but derived versions such as commits.

### Template

My template is at https://github.com/OverkillGuy/python-template, but not much of it is required for this (and I use tasks = unsafe/trust question).

### To Reproduce

1. Get a template with well known tag, say `v1.0.0`
2. Make a new commit or two, without publishing newer tag
3. Create a repo from latest template via `copier copy --vcs-ref HEAD source destination`
4. Create a new commit or two more, publishing tag `v2.0.0` of template
5. Run `copier update`, observe effect

### Expected behavior

Successful update to v2.0.0, instead of a crash/error around bad git checkout.

### Screenshots/screencasts/logs

Crash/error (do not recall exact, have to regenerate, instead of expected template update

### Operating system

Linux

### Operating system distribution and version

Pop_OS 22.04 (~Ubuntu 22.04)

### Copier version

8.1.0

### Python version

3.11

### Installation method

pipx+pypi

### Additional context

Will try to reproduce with minimal template later, my own being needlessly convoluted.

**Comment by yajo** [comment]
That's the expected behavior according to the docs: 

https://github.com/copier-org/copier/blob/1936824ac5431e347fe294b4f4ae3269e1bf360e/docs/updating.md?plain=1#L18-L21

To update it, either publish a new release or add `-r HEAD`.
