### ISSUE TITLE
Ambiguous exit code 2

### ISSUE THREAD

**Issue by sisp** [copier-org/copier#1328]
### Describe the problem

[Copier uses exit code 2 for `UnsafeTemplateError`](https://github.com/copier-org/copier/blob/ddafdee3ce162da7b889c44e11aad8b19c910136/copier/cli.py#L72-L74) while Plumbum uses the same exit code for `plumbum.cli.switches.SwitchError` type errors, e.g. mutually exclusive switches that are passed simultaneously.

### Template

There is none yet that exhibits this problem, but it would occur after merging #1325.

### Expected behavior

Copier should use different exit codes for semantically different error types.

### Operating system

Linux

### Operating system distribution and version

any

### Copier version

next feature release that includes #1325

### Python version

any

### Installation method

pipx+pypi

**Comment by yajo** [comment]
Yikes...

I guess it's easier to change our own exit code and consider it a breaking change, isn't it?

Our new exit code should be then `0b100`, which means `4`.

**Comment by sisp** [comment]
> I guess it's easier to change our own exit code and consider it a breaking change, isn't it?

Agreed.

> Our new exit code should be then `0b100`, which means `4`.

Just for my better understanding: What's the rationale behind `0b100`?

**Comment by yajo** [comment]
In general terms, the exit code communicates what happened.

By using only numbers that don't conflict at the binary level, you can reason better about subprocesses. 

One example:

```py
from my_custom_cli_calling_lib import run_copier_cli

SOME_ERROR = 0b1
WRONG_FLAGS = 0b10
UNSAFE_TEMPLATE = 0b100

res = run_copier_cli()
if res & UNSAFE_TEMPLATE:
  print("Please add --trust")
if res & WRONG_FLAGS:
  print("Fix flags.")
if res & SOME_ERROR:
  print("I don't know what happened, but it was bad")
```

With that system, you can even communicate multiple error states with a single exit code. For example, if we were to tell that there are wrong flags and the template is unsafe, we could make Copier exit with 6 and the above code would do what is expected.

Probably not very applicable for Copier, but it's my rule of thumb in all other projects.

**Comment by sisp** [comment]
Thanks for the detailed clarification :pray:, this makes a lot of sense! 👍

I'll send a PR with this change tomorrow.
