### ISSUE TITLE
`FieldValidationInfo` is deprecated, use `ValidationInfo` instead.

### ISSUE THREAD

**Issue by RomainBrault** [copier-org/copier#1341]
### Describe the problem

Pydantic 2.4.0 emits the warning:

`FieldValidationInfo` is deprecated, use `ValidationInfo` instead.'

### Template

https://github.com/RomainBrault/python-whiteprint

### Logs

```console
E       AssertionError: The CLI did not exit properly.
E       assert 1 == 0
E        +  where 1 = <Result DeprecationWarning('`FieldValidationInfo` is deprecated, use `ValidationInfo` instead.')>.exit_code`
```

### Expected behavior

No warning should be emited

### Operating system

Linux

### Operating system distribution and version

Ubuntu 23.04

### Copier version

8.3.0

### Python version

3.11.5

### Installation method

distro package

### Additional context

Conda install

The fix looks simple:

Replace FieldValidationInfo by FieldValidation in user_data.py

**Comment by sisp** [comment]
Thanks for reporting this, @RomainBrault! :pray: Would you like to submit a PR?
