### ISSUE TITLE
CLI help not properly generated in docs

### ISSUE THREAD

**Issue by yajo** [copier-org/copier#1357]
Following https://github.com/copier-org/copier/issues/1349, it seems something broke:

![imagen](https://user-images.githubusercontent.com/973709/272654095-44896503-8d9e-45a1-9d04-0f8c4b3be261.png)

**Comment by pawamoy** [comment]
Since the snippet actually runs `copier`, the docs job in CI must be missing the installation of the project and its dependencies.

**Comment by sisp** [comment]
Ouch, yes, the problem is that Read the Docs only installs the `docs` group which doesn't contain Plumbum etc.:

https://github.com/copier-org/copier/blob/2cf1dca03c6bf9a74df401355cbd540f7d0099cf/.readthedocs.yml#L14

I think we need to install `main` and `docs`:

```diff
-poetry install --only docs
+poetry install --with docs
```

**Comment by yajo** [comment]
Seems like that must be the fix. Wanna do that @sisp?

FWIW, we have readthedocs builds enabled in PRs, so we can check these things before merging.

**Comment by sisp** [comment]
Sure, I've submitted a PR: #1358

I must have missed the failing build in #1349. :thinking: Let me check in #1358 that Read the Docs builds correctly again. Sorry about the breakage. :bow:

**Comment by yajo** [comment]
No problem @sisp! On the contrary, thanks for your help in keeping the house clean! I appreciate it a lot 😃
