### ISSUE TITLE
bug: Importing from Copier prevents forcing colors with FORCE_COLOR=1

### ISSUE THREAD

**Issue by pawamoy** [copier-org/copier#1378]
### Describe the problem

Rich or Rich-based CLIs will print colors on regular terminals. In subprocesses, Rich detects that the process isn't attached to a TTY (or rather pseudo-TTY if I recall terminology correctly) and disables colors. Colors can be forced back using the `FORCE_COLOR=1` environment variable.

Setting the variable works well... unless something is imported from Copier. [This was quite hard to identify as the cause](https://github.com/DanCardin/cappa/issues/30), but here's a reproduction example:

```python
# colors_without_copier.py
from rich.console import Console
console = Console()
console.print("[bold green]Hello[/]")
```

```python
# colors_with_copier.py
from copier import run_copy
from rich.console import Console
console = Console()
console.print("[bold green]Hello[/]")
```

```bash
# colors.sh
echo "Forcing colors without Copier imports"
FORCE_COLOR=1 python colors_without_copier.py | cat -n

echo "Forcing colors with Copier imports"
FORCE_COLOR=1 python colors_with_copier.py | cat -n
```

Now run `bash colors.sh` and you get an output similar to this (don't pay attention to the actual colors, I'm using a dynamic color theme based on my wallpaper thanks to pywal):

![copier_colors](https://github.com/copier-org/copier/assets/3999221/b8cdfbea-376f-4342-b9af-059abc196263)

See script in the "Reproduction" section for a complete script that you can copy and paste.

### Template

N/A

### To Reproduce

```bash
cd $(mktemp -d)

cat <<EOF >colors_without_copier.py
from rich.console import Console
console = Console()
console.print("[bold green]Hello[/]")
EOF

cat <<EOF >colors_with_copier.py
from copier import run_copy
from rich.console import Console
console = Console()
console.print("[bold green]Hello[/]")
EOF

cat <<EOF >colors.sh
echo "Forcing colors without Copier imports"
FORCE_COLOR=1 python colors_without_copier.py | cat -n
echo "Forcing colors with Copier imports"
FORCE_COLOR=1 python colors_with_copier.py | cat -n
EOF

bash colors.sh
```

### Expected behavior

Importing things from Copier should not cancel the effect of `FORCE_COLOR=1`.

### Operating system

Linux

### Operating system distribution and version

Linux 6.5.7-arch1-1

### Copier version

8.3.0

### Python version

3.11.5

### Installation method

pipx+pypi

**Comment by pawamoy** [comment]
OK, I expanded the imports trigger by `from copier import run_copy`, and identified the culprit to be `copier.tools`. Looking at the code, the cause is obvious: `colorama.init()` is ran at import time.

**Comment by pawamoy** [comment]
Reading https://github.com/tartley/colorama/pull/230, my `deinit`, re`init` solution does not seem to be right, since ANSI codes should always be stripped on Windows. I'd therefore recommend using `colorama.just_fix_windows_console()` instead.

Additional note: `from plumbum import colors` weirdly adds a line `%` at the end of the output...

**Comment by pawamoy** [comment]
Plumbum weirdness filed here: https://github.com/tomerfiliba/plumbum/issues/659

**Comment by yajo** [comment]
Related: #368
