### ISSUE TITLE
Add py.typed file

### ISSUE THREAD

**Issue by mwgamble** [copier-org/copier#1381]
### Actual Situation

Mypy is unable to find type information for the `copier` package, which requires me to manually ignore type errors for `copier` whenever I import it.

### Desired Situation

Mypy doesn't complain about missing type information, and the type safety of my own code is increased as a result. I also have to invest less mental energy worrying about ignoring types for a package I'm using.

### Proposed solution

Add a `py.typed` file to the `copier` package.

**Comment by yajo** [comment]
It's weird. Our full code base has type hints, and we use mypy to check it...

**Comment by pawamoy** [comment]
Some PEP requires that a py.typed file is present to mark a package as typed. It's not required if you run mypy directly on its sources though, that's why it didn't complain.
