### ISSUE TITLE
Make `mypy copier --strict` pass

### ISSUE THREAD

**Issue by bswck** [copier-org/copier#1441]
### Actual Situation

`mypy copier --strict` fails with 68 errors in 7 files (checked 11 source files).
Checked on compiled mypy 1.5.1, Python 3.8.17. 

### Desired Situation

`mypy copier --strict` passes successfully.

### Proposed solution

Resolve all errors reported by mypy.
A followup to #1431.

**Comment by bswck** [comment]
I want to see [autorefine](https://github.com/bswck/autorefine) in the action of semi-auto-resolving this, as soon as it's ready.

**Comment by Lujeni** [comment]
Hey @bswck ! Thanks for this nice project

Is it possible to propose a batch of small pull requests in order to fix specific mypy errors or would you prefer a single PR to fix all of them?

**Comment by bswck** [comment]
> Hey @bswck ! Thanks for this nice project
> 
> Is it possible to propose a batch of small pull requests in order to fix specific mypy errors or would you prefer a single PR to fix all of them?

Thanks for reaching out. If you want to fix this issue, then I guess you might make a single pull request with bulk fixes in logically separated commits and in line with [the contributing guide](https://github.com/copier-org/copier/blob/master/CONTRIBUTING.md#pull-request-guidelines).

If you're asking about _autorefine_, it will aim to organize fixes of linting and typechecking errors into groups that can be separated into small pull requests for the ease of reviewing and preserving easily bisectable, clean, logically grouped SCM history.

_autorefine_ is a very big idea, but I am currently jobless and have no time nor money to take the effort all by myself. If you want to help, please reach out to me.

**Comment by sisp** [comment]
Resolved via #1527.
