### ISSUE TITLE
Make PR checks for Python 3.12 required

### ISSUE THREAD

**Issue by sisp** [copier-org/copier#1445]
### Actual Situation

Currently, all PR checks for Python 3.12 are optional. See any open PR and notice the missing `Required` badges for those checks.

### Desired Situation

Since Python 3.12 has been released and is officially supported by Copier, those checks should be required as well.

### Proposed solution

AFAIK, this is a GitHub project setting that only @yajo can change.

**Comment by yajo** [comment]
Thanks! Done

**Comment by sisp** [comment]
Thanks! :+1:
