### ISSUE TITLE
Workflow for updating from a local clone of a template

### ISSUE THREAD

**Issue by oprypin** [copier-org/copier#1446]
### Actual Situation

I have a few projects using the template `gh:oprypin/py-project-template`,
and I also have a local clone of the template `~/py-project-template`.

Currently Copier expects the following workflow from maintainers of a public template:

1. Edit something in the local clone
2. **Commit the template and publicly push it**
3. In a project using this template: `copier update -A -r HEAD`
4. Look at the new changes in the real project

I am not fully satisfied with this workflow because at first I want to *try* the template - whether it produces valid syntax and whether the destination project still works OK with the changes. And only then publish the changes.

### Desired Situation

I want the following workflow to be possible:

1. Edit something in the local clone
2. In a project using this template: `copier update -A -r HEAD`
3. Look at the new changes in the real project
4. If it looks good, **commit the template and publicly push it**

But Copier doesn't work that way, so instead this is what I have to do:

1. Edit something in the local clone
2. In a project using this template:
    1. `sed -i 's@gh:oprypin/py-project-template@~/py-project-template@' copier-answers.yml`
    2. `git commit -a` (because dirty state is not allowed)
    3. `copier update -A -r HEAD`
    4. `sed -i 's@~/py-project-template@gh:oprypin/py-project-template@' copier-answers.yml`
3. Look at the new changes in the real project
4. If it looks good, commit the template and publicly push it

### Proposed solution

I think my suggested workflow would be nice for many people and I wish it could just work. I want to publicly refer to my template so others can use it, but I want to use the local clone whenever I personally work with it.

One simple way is to support passing a **different path of a template as a flag**. Notably, I would like this to also **not write the overridden path of the template back into the answers file**, otherwise the last revert step will still be necessary.

Or perhaps even better, a mapping of such overrides could be a **permanent global config**: I want to tell copier that whenever it sees `gh:oprypin/py-project-template`, it should look at `~/py-project-template` instead.

In the meantime I hardcoded this override into my fork of Copier https://github.com/copier-org/copier/commit/ec09a7eefc6a48a348568c2cd5d358aac749ff7c and this works well for me.

**Comment by pawamoy** [comment]
> otherwise the last revert step will still be necessary.

Let say Copier has a flag to specify a local template path when updating.
If it's only for testing your latest template changes, shouldn't you:

- update your project from the local template
- check that everything is OK
- **revert everything**
- commit and push the template
- do a real update from the remote template?

This way the commits referenced in `.copier-answers.yml` throughout your Git history will be existing commits. If you commit your project from a local template, using HEAD and packing uncommitted changes, the commit in `.copier-answers.yml` will be wrong (they won't exist on the remote) I think. Maybe you don't care though :smile:

**Comment by oprypin** [comment]
No that's not right. Sure, if I'm ready to move forward with the template as is then I need to commit it. Which is not a big deal and I may have already done it (in which case your comment is *completely* inapplicable). However I **still don't need to push it first** to make a ""real"" update like you're saying. If everything was already committed and looks good, I don't in fact need to redo anything.

**Comment by sisp** [comment]
@oprypin I haven't actually tried this, but would reconfiguring Git via an environment variable using [`insteadOf`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf) at least avoid the `sed` hack?

```sh
GIT_CONFIG_PARAMETERS="'url.~/py-project-template.insteadOf=https://github.com/oprypin/py-project-template'" copier update ...
```

Or alternatively by setting this in the project's local Git config?

**Comment by oprypin** [comment]
@sisp Wow that's such a cool suggestion. I was thinking about a .gitconfig change but didn't know that you can override it through an environment variable. And it *has* to be a temporary override, otherwise I can never push that repo :smile: 

Yes! This worked for me instead of the manual replacement or my forked change.

```bash
GIT_CONFIG_PARAMETERS="'url.$HOME/py-project-template.insteadOf=https://github.com/oprypin/py-project-template.git'" copier update -a .tools/copier-answers.yml -A -r HEAD
```

**Comment by sisp** [comment]
Great! 😊 Does it solve the complete problem for you or only the `sed` part?

**Comment by oprypin** [comment]
I.. think that's the entirety of the solution actually, yeah. This is basically the flag that I was asking for **or**
if I add a permanent shell alias `alias copier='GIT_CONFIG_PARAMETERS="..." copier`
then this is equivalent to my best-case suggested solution
>  a mapping of such overrides could be a **permanent global config**

Unless the project owners want to integrate or popularize this possibility more, then nothing to do.

**Comment by yajo** [comment]
You can integrate https://github.com/KyleKing/copier-template-tester into your template pipeline. I do it in my templates, through pre-commit. It is a nice tool for snapshot-based testing in copier templates.
