### ISSUE TITLE
Fix documentation link in Github Repo

### ISSUE THREAD

**Issue by kenibrewer** [copier-org/copier#1460]
### Actual Situation

Clicking the primary link on the Github leads you to ReadtheDocs builds page: https://readthedocs.org/projects/copier/

Link location:
![image](https://github.com/copier-org/copier/assets/17461269/a3dcdbc3-4fe3-4851-be8f-12eb4bddb479)
Destination:
![image](https://github.com/copier-org/copier/assets/17461269/1bd64f2e-3792-4bd5-9613-6e4f6e989fac)

### Desired Situation

The primary link should direct to the documentation itself not the builds. 

### Proposed solution

Change the link to https://copier.readthedocs.io/en/stable/

**Comment by yajo** [comment]
It's on purpose, so you can select the docs for the version you want.
