### ISSUE TITLE
json dump of _copier_conf not working

### ISSUE THREAD

**Issue by johannesloibl** [copier-org/copier#1481]
### Describe the problem

I have a task like this:
```
_tasks:
    # Strings get executed under system's default shell
    - [
        "{{ _copier_python }}",
        "{{ _copier_conf.src_path }}/hooks/post_gen.py",
        "--conf={{ _copier_conf|to_json|b64encode }}"
    ]
```
When updating a project with copier, `_copier_conf` contains some
values that cannot be serialized.
```
  File "C:\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'function'>
```
Apparently there are functions that need to be removed before serialization:
![image](https://github.com/copier-org/copier/assets/48917891/58083902-5a30-4204-a953-fbc2f3be3551)
 

### Template

```
_tasks:
    # Strings get executed under system's default shell
    - [
        "{{ _copier_python }}",
        "{{ _copier_conf.src_path }}/hooks/post_gen.py",
        "--conf={{ _copier_conf|to_json|b64encode }}"
    ]
```

### Expected behavior

`{{ _copier_conf|to_json }}` shall be serializable by default

### Operating system

Windows

### Operating system distribution and version

Win 10

### Copier version

9.1.0

### Python version

CPython 3.11

### Installation method

pip+pypi

**Comment by johannesloibl** [comment]
I just tried to contribute a fix for this issue, but it seems it was indirectly fixed by some new version of ``pydantic``'s ``to_jsonable_python`` function, which automatically removes unserializeable stuff from the context.
I think this issue can be closed 🔮

**Comment by yajo** [comment]
Cool! Thanks
