### ISSUE TITLE
Migrate existing project managed by cruft to copier

### ISSUE THREAD

**Issue by clement-chaneching** [copier-org/copier#1517]
### Describe the problem

Hello,

I have pypackages managed by cruft and cookiecutter and I m willing to move to copier. 
It's pretty easy to modify the template and use copier to create new projects.
However I cannot manage to move my existing projects to copier template without overwriting everything (have something like cruft link)

I searched through the issues and discussions, but didn't manage to find any simple solutions to migrate...
This [discussion ](https://github.com/orgs/copier-org/discussions/1393) suggests to create a copier from scratch and move everything which is a pain.

I tried to `copier copy template existing_project`, but it just overwrites everything when I run copier update if I dont use conflict rej. I do not have the inline modification in my vscode.

### Template

```
# Configs

_templates_suffix: ""
_subdirectory: template

# Variables
Set of variables...

# Task to execute after generating the project
_tasks:
    - ["python", post_gen_project.py]
    - "rm post_gen_project.py"
```

### To Reproduce

1. Have an existing project not managed by copier
2. Create a similar copier template with template app.py
3. Try to link existing project to copier without overriding files (use copier copy template existing_project without overwriting app.py)
4. It will overwrite it if I run copier update

### Expected behavior

When using copier copy on an existing project, and deciding not to overwrite the files, it should keep track of the file, and not overwrite everything when copier update.

### Operating system

Linux

### Operating system distribution and version

debian wsl

### Copier version

9.1.1

### Python version

3.10

### Installation method

pipx+pypi

**Comment by sisp** [comment]
> This [discussion ](https://github.com/orgs/copier-org/discussions/1393) suggests to create a copier from scratch and move everything which is a pain.

Could you elaborate why this approach is a pain for you? If you have multiple projects, you should be able to automate the steps and only do some manual checking/cleanup before committing.

**Comment by clement-chaneching** [comment]
Ok, was just checking if there was an easy way to do it.
But if not, I ll find a way to automate it, thx
