### ISSUE TITLE
remove flake8

### ISSUE THREAD

**Issue by danieleades** [copier-org/copier#1524]
### Actual Situation

this project is linted using flake8 *and* ruff. It does not need both.

### Desired Situation

remove flake8 linting

### Proposed solution

Unfortunately I find nix impenetrable so it's not clear to me how to remove flake8 from this repo

**Comment by danieleades** [comment]
for ruff to have parity with flake8 #1523 needs to be merged.

**Comment by yajo** [comment]
This is only using ruff AFAICS.

**Comment by danieleades** [comment]
> This is only using ruff AFAICS.

You may wish to reopen this to track removing the flake8 config file in that case
