### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by pykong** [copier-org/copier#154]
Once the dev setup has stabilized it will be time to reflect the changes back into the dev docs:
`CONTRIBUTING.md`.

See also: #129 #132

**Comment by pawamoy** [comment]
Seeing how you improved CONTRIBUTING.md in [this commit](https://github.com/copier-org/copier/commit/4f36db4c72004ae4d124aa391db55737b8ecfdf3), maybe this issue could be closed?

Maybe just one thing I noticed: you track VSCode settings and set the path to the interpreter to `.venv/bin/python`, but if contributors do not tell Poetry to install the venv in the project, they will have to change that setting:

```diff
-  "python.pythonPath": ".venv/bin/python"
+  "python.pythonPath": "/home/pawamoy/.cache/pypoetry/virtualenvs/copier-AExR1Oeb-py3.9/bin/python"
```

Not sure how to circumvent that though.

**Comment by Yajo** [comment]
Yes, that's because of https://github.com/microsoft/vscode-python/issues/8372.  For now, the only way to use both tools sanely and share out-of-the-box settings is to tell poetry to save the venv local to the project. 

I should document that.
