### ISSUE TITLE
Organization avatar cut off

### ISSUE THREAD

**Issue by sisp** [copier-org/copier#1547]
I noticed that the `copier-org` organization avatar is cut off at the right:

![image](https://github.com/copier-org/.github/assets/2206639/1e038f69-4760-4ea5-bc05-92f970f5658b)

Also, it seems the "C" from "Copier" is present in the avatar at the right, just barely visible. We should remove the text and add padding to give the logo-only image a 1:1 aspect ratio.

I don't have permissions to change it. Would you mind fixing it, @yajo?

**Comment by sisp** [comment]
I can extract the avatar PNG from the SVG logo on Monday and post it here.

**Comment by sisp** [comment]
Here is the avatar PNG with padding, 1:1 aspect ratio, 512x512px resolution and a transparent background:

![copier-org avatar](https://github.com/copier-org/copier/assets/2206639/89539e94-0a73-4494-a93c-082362e13559)

I hope this works fine. :crossed_fingers:

**Comment by sisp** [comment]
@yajo Do you happen to have a moment to update the org avatar?

**Comment by yajo** [comment]
Ah sorry I forgot! Fixed now.
