### ISSUE TITLE
Be able to go back to a previous answer in the template generation questions menu

### ISSUE THREAD

**Issue by nathanjmcdougall** [copier-org/copier#1553]
### Actual Situation

At the moment, when you are answering the questions in the template generation menu, it is not possible to revise an answer after it has already been submitted.

This can be frustrating when you have answered a series of questions, and then you realize that you had a typo in the previous response.

### Desired Situation

It would be good if there were some way to go back to the previous question and revise the answer.

### Proposed solution

I am not sure the best way to provide this functionality. Perhaps using a particular keyboard combination, such as repeated backspaces on an empty answer to the current question.

**Comment by pawamoy** [comment]
Hey, thanks for the feature request :slightly_smiling_face: I believe this is already tracked in #1490 so I'll close as duplicate.

**Comment by nathanjmcdougall** [comment]
Woops, sorry I didn't find that one.
