### ISSUE TITLE
⚠ CRITICAL: Copier 9.1.1 broken by too loose `pyyaml-include` requirement ⚠

### ISSUE THREAD

**Issue by bswck** [copier-org/copier#1568]
### Describe the problem

Yesterday, [`pyyaml-include` 2.0 was released](https://github.com/tanbro/pyyaml-include/blob/a7cd1223237e98d7302a55dc65db98411f34c232/CHANGELOG.md#20). Unsuprisingly for a non-CalVer major release, it stabilized a **breaking change**: the `pyyaml-include`'s package namespace `yamlinclude` was moved to `yaml_include` ([ref](https://github.com/tanbro/pyyaml-include/blob/a7cd1223237e98d7302a55dc65db98411f34c232/CHANGELOG.md#20b1)).

The latest Copier release, 9.1.1, was released prior to removing the `pyyaml-include` dependency in 037d7f0.
Back then, the `pyproject.toml` version specification for `pyyaml-include` was `">=1.2"`:
https://github.com/copier-org/copier/blob/b3ed48d7dda94e700317226018bec37ac244e529/pyproject.toml#L43

which has been welcoming Copier-incompatible `pyyaml-include==2.0` with open arms in every installation since the yesterday's `pyyaml-include` release. 

Copier is now unusable in every environment that installed Copier upon the `pyyaml-include` 2.0 release (including [my today's CI environment](https://github.com/skeleton-ci/skeleton-python/actions/runs/8508259877/job/23301830458) that adopts CTT for testing my Copier template), unless one pins the legacy `pyyaml-include<2` explicitly as a direct, non-transitive dependency.

### Template

Doesn't apply.

### To Reproduce

1. `pip install copier`
2. `copier`

### Logs

```console
~/dev/skeleton git:(main|)❯❯❯ copier
Traceback (most recent call last):
  File "/home/bswck/.local/bin/copier", line 5, in <module>
    from copier.__main__ import copier_app_run
  File "/home/bswck/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/__init__.py", line 6, in <module>
    from .main import *  # noqa: F401,F403
  File "/home/bswck/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 46, in <module>
    from .subproject import Subproject
  File "/home/bswck/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/subproject.py", line 15, in <module>
    from .template import Template
  File "/home/bswck/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/template.py", line 20, in <module>
    from yamlinclude import YamlIncludeConstructor
ModuleNotFoundError: No module named 'yamlinclude'
```

### Expected behavior

No errors.

### Operating system

Linux

### Operating system distribution and version

Ubuntu 23.04

### Copier version

9.1.1

### Python version

3.10

### Installation method

pipx+pypi

### Additional context

**Workaround:** Pinning the legacy `pyyaml-include<2` directly.

I strongly suggest pinning all versions properly to prevent unexpected breaking changes in the future and make Copier more reliable.
[The current `pyproject.toml` file](https://github.com/copier-org/copier/blob/0fb2d0609dab494e501445711ec9bc9993071310/pyproject.toml) might expose Copier to many, many more identical pitfalls.

**Comment by pawamoy** [comment]
Upper bounds were explicitly removed before IIRC, because they usually cause conflicts in the Python ecosystem. But since Copier uses Dependabot/Renovatebot, I suppose we could add back upper bounds on major versions. I'd strongly recommend adding some CI jobs to test early on unaccepted versions if we go this route again!

**Comment by bswck** [comment]
> Upper bounds were explicitly removed before IIRC, because they usually cause conflicts in the Python ecosystem. But since Copier uses Dependabot/Renovatebot, I suppose we could add back upper bounds on major versions. I'd strongly recommend adding some CI jobs to test early on unaccepted versions if we go this route again!

I'd only like to note here that I provided a temporary workaround for troubled users, not a solution for Copier.
The best solution would definitely be either cutting a new release or, if we're sure that a post-2 version introduces some backward compatibility (which I doubt), specifying `!=2.0`.

**Comment by bswck** [comment]
When it comes to my suggestion, when I suggested pinning versions properly, I meant checking for future similar risks. This doesn't necessarily mean using bringing back conservative and troublesome upper bounds, but rather checking for identical pitfalls potential in the future, which was the direct reason for this issue to be filed.

**Comment by sisp** [comment]
I'd keep only lower bounds because upper bounds can cause unresolvable dependency trees. Major releases in SemVer-versioned projects _may_ break dependants but often don't. A missing upper bound like in this case can be worked around in userland by adding a constraint – see, e.g., https://github.com/copier-org/copier/issues/1225#issuecomment-1616656418.

Ideally, we should temporarily upper-bound `pyyaml-include`, make a patch release to fix the incompatibility that exists now, and remove the upper bound again along with a proper fix afterwards (see, e.g. #1244 and #1229 for a similar situation with Pydantic). But like many open-source projects do we not backport fixes, and the current `master` branch does not depend on `pyyaml-include` anymore. I think `master` is stable. Should we release v9.2.0 ASAP, @yajo?

**Comment by sisp** [comment]
@bswck Regarding upper bounds and pinning in Python (libraries): https://iscinumpy.dev/post/bound-version-constraints/

**Comment by bswck** [comment]
I'd been fully aware of troubles that come from upper bounds and slowly adapt my projects to best practices.
Regardless, thanks for recommending a great article though!

**Comment by pawamoy** [comment]
I'd vote for a quick release from master if possible indeed :)

**Comment by edgarrmondragon** [comment]
> I'd vote for a quick release from master if possible indeed :)

Second that. The dependency on `pyyaml-include` was dropped in https://github.com/copier-org/copier/commit/037d7f04a3c147411f3358fce19535c12f5e2804#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711, but the latest copier release is older than that. So indeed a release from `master` should fix this issue.

**Comment by andrew-glenn** [comment]
Adding that we're pinned to 0.8.30 for other reasons and this affects us as well

**Comment by trymzet** [comment]
To add to https://github.com/copier-org/copier/issues/1225#issuecomment-1616656418 regarding userland workarounds, with Rye, you can do `rye install copier --extra-requirement pyyaml-include==1.4.1`

**Comment by krassowski** [comment]
8.x branch is broken too. Would you consider a patch on 8.x for those who cannot upgrade to 9.x yet?

**Comment by sisp** [comment]
@krassowski Like many open-source projects, I don't think we have the capacity to backport fixes. But the ultimate decision lies with @yajo.

If I may ask, what's your reason for not being able to upgrade to 9.x?

**Comment by sschrijver-pon** [comment]
For those of you who installed `copier` using `pipx`, running `pipx install copier --force --pip-args "pyyaml-include<2"` seems to work

**Comment by bswck** [comment]
> **Edit:** in [#1225 (comment)](https://github.com/copier-org/copier/issues/1225#issuecomment-1616656418) I see the `pipx inject ...` command is used to specify a particular version of a sub-dependency. Is `inject` preferred? If so, it should be `pipx inject copier 'pyyaml-include<2'` instead of my suggestion!

Yeah, `pipx inject copier 'pyyaml-include<2'` would ensure that Copier's autonomous pipx venv sees `pyyaml-include<2`, that's the best approach for pipx IMO.

**Comment by FCamborda** [comment]
Any timeline on when we can expect the next release without `pyyaml-include`?

**Comment by henryiii** [comment]
FWIW, pyyaml-include should have had a deprecation period where both namespaces were provided and the one that was to be removed produced a warning. Making a sudden breaking change without warning is not a good idea in the Python ecosystem. There was a beta release, but unless you pass `--prerelease`, you don't see it (not a bad idea for CI).

**Comment by grbaiges** [comment]
Hi, we're experiencing this issue with Copier 8.1.0 as well, which was working well until last week. Is there anyway that old Copier versions were modified when doing the new release? Or is it that pyyaml-include was not pinned in old versions of Copier? Is there any Copier version safe from this bug that we can use straight away? This issue is quite blocking

**Comment by FCamborda** [comment]
> Hi, we're experiencing this issue with Copier 8.1.0 as well, which was working well until last week. Is there anyway that old Copier versions were modified when doing the new release? Or is it that pyyaml-include was not pinned in old versions of Copier? Is there any Copier version safe from this bug that we can use straight away? This issue is quite blocking

You can just install the latest Copier version with a compatible `pyyaml-include` for now
`pip install copier 'pyyaml-include<2'`

**Comment by pawamoy** [comment]
I agree with @henryiii, deprecation warnings are the most reliable way to inform downstream users that something is about to break.

Regarding new releases, @sisp and I agree on releasing a 9.x release quickly, and I believe we have enough privileges to do that (pushing a tag), but @yajo is our captain and we'd like to hear from him first :slightly_smiling_face: 
For a 8.x release, I'm ready to consider it myself, exceptionally. Again, needs blessing from @yajo.

**Comment by yajo** [comment]
Hello! Sorry everybody. Since some weeks ago, gmail decided that copier issues were spam and I lost every message 😆 

FWIW one advantage of not pinning versions is that we let you pin them downstream. Whatever packaging system you use, it should have a way to downgrade a package. Just do it and it will serve as a workaround for older releases.

Let me push a new release without pyyaml-include, which we don't require in master anymore.

**Comment by yajo** [comment]
Fixed in https://github.com/copier-org/copier/releases/tag/v9.2.0.
