### ISSUE TITLE
Provide a way to integrate with nix templates

### ISSUE THREAD

**Issue by mainrs** [copier-org/copier#1647]
### Actual Situation

Right now, `copier` is more of a standalone program. It already integrates with the `nix` ecoosystem by providing itself as a package inside a nix flake.

However, there is room for improvement!

### Desired Situation

`nix` has a feature called `templates`. They can be used to initialize a working directory by copying the files from a source directory you specify (i.e., the template) to the current directory.  The command for this is `nix flake init -t <template reference>`.

The repository at https://github.com/nixos/templates provides a set of templates that one can use. The shortcoming of this system is the static nature of templates; there is no way to provide dynamic variables that get substituted.  

`copier` could fit in here nicely by filling this gap. What I am requesting: a way to use `copier` to build a `nix template` output. Similar to [this flake](https://flakehub.com/flake/snowfallorg/vhs) that provides a library function called `mkRecorder`, `copier` could provide one called `mkNixFlakeTemplate` or something similar. Passing that function the directory to the template would generate the necessary nix expression to embed it.

**Comment by yajo** [comment]
For Copier, ˋnix flake initˋ is nothing more than yet another bootstrap-only templating engine. Not much different from cookiecutter or yeoman.

To be able to use the update feature of Copier, you need an impure environment with network access to clone and replay last copy, update the current one, compare them and do the smart evolution. Thus I think what you're asking is a bit over-engineered.

OTOH I agree that it'd be helpful for a template to supply an officially-supported version of Copier, just to make sure the template works fine with *that* Copier derivation. You can get the one from here, from flakehub or from nixpkgs and provide it as an output of your flake.

Worth it? I guess only in cases where you need extra plug-ins. For other cases you can tell your users to do something like this:

    nix run github:copier-org/copier/v9.3.1 copy gl:moduon/precommix .

And from that moment, you'll be able to update with:

    nix run github:copier-org/copier/v9.3.1 update

With a couple extra lines of nix code in your flake, you could provide this interface:

    nix run gitlab:moduon/precommix#copy
    nix run gitlab:moduon/precommix#update

So IMHO there's not much left for Copier to do in this regard. Just adapt to your needs 😊
