### ISSUE TITLE
Unable to set default value on a choice answer

### ISSUE THREAD

**Issue by josep-tecnativa** [copier-org/copier#1678]
### Describe the problem

I'm trying to set default value on this choice answer:
https://github.com/Tecnativa/doodba-copier-template/pull/476/commits/f8f4ab77d083496578f25c1a89b5731a41da9bfd

### Template

https://github.com/Tecnativa/doodba-copier-template/blob/main/copier.yml

### To Reproduce

To reproduce:
`copier copy --vcs-ref fix-ci-error --trust gh:Tecnativa/doodba-copier-template test-dir`
And when reaching traefik version choice answer, i do not get 2 as default answer. Instead, the arrow is on v3.0 version

### Expected behavior

The expected behavior following copier documentation is to have 2 as the default answer.
https://copier.readthedocs.io/en/stable/configuring/#advanced-prompt-formatting

### Operating system

Linux

### Operating system distribution and version

ubuntu 22.04

### Copier version

9.2.0

### Python version

3.11

### Installation method

pipx+pypi

**Comment by josep-tecnativa** [comment]
Solved, default has to be used before `choices`. Also before `when`.
https://github.com/Tecnativa/doodba-copier-template/pull/476/commits/b261d7c8289ceff922f1b5882f67048bb7a43fff#diff-a74d725f30a732f10530aec0b66cdc1f1856272e35ede5ba4826ead3075c3d3dR130

**Comment by josep-tecnativa** [comment]
Solved, default has to be used before choices. Also before when.
https://github.com/Tecnativa/doodba-copier-template/commit/b261d7c8289ceff922f1b5882f67048bb7a43fff#diff-a74d725f30a732f10530aec0b66cdc1f1856272e35ede5ba4826ead3075c3d3dR130

**Comment by sisp** [comment]
I can't imagine why `default` needs to come before `choices` and `when`; in fact, I cannot reproduce it:

```yaml
traefik_version:
  type: int
  when: "{{ true }}"
  help: >
    Indicate Traefik version( v2 recommended )
  choices:
    v1.7: 1
    v2.4: 2
    v3.0: 3
  default: 2
```

This simplified snippet (derived from your referenced `copier.yml` file) works fine for me. Would you mind double-checking?

**Comment by yajo** [comment]
AFAICS the CI on https://github.com/Tecnativa/doodba-copier-template/commit/f8f4ab77d083496578f25c1a89b5731a41da9bfd was cancelled manually, but going green on all variants already. Seems like a fail on the diagnose side.
