### ISSUE TITLE
Validators don't work when answers passed with --data flag

### ISSUE THREAD

**Issue by msharp9** [copier-org/copier#1698]
### Describe the problem

Adding a validator works when running copier copy on the command line, and prevents a user from giving an invalid answer, but this can be bypassed simply by giving that answer via the --data flag.  Validations don't run on answers when given directly.

### Template

Notes in "To Reproduce" section.  Not template specific.

### To Reproduce

Create a copier template with a copier.yml file using a validator.

```
project_name:
    type: str # Any value will be treated raw as a string
    help: An awesome project needs an awesome name. Tell me yours.
    default: paradox-specifier
    validator: >-
        {% if not (project_name | regex_search('^[a-z][a-z0-9\-]+$')) %}
        project_name must start with a letter, followed one or more letters, digits or dashes all lowercase.
        {% endif %}
```

Run `copier copy -d project_name=Any$invalid_answer! template template_copy`

And the template is still created.

### Expected behavior

I would expect the `copier copy` command to throw an error if a value doesn't meet validations.

### Operating system

macOS

### Operating system distribution and version

Sonoma 14.5

### Copier version

9.3.1

### Python version

Python 3.11.5

### Installation method

pip+pypi

**Comment by sisp** [comment]
Would you mind sharing the recorded answer (see, e.g., the content of `.copier-answers.yml`)?

**Comment by msharp9** [comment]
Oh, it was empty... Looks like I was pointing to the wrong directory since my copier.yml is in the root of the project with a `_subdirectory: template` set.

Running `copier copy -d project_name=Any$invalid_answer! . template_copy` I do see errors. 🤦

**Comment by sisp** [comment]
No worries, I'm glad you found the problem.

Just a side note: Your sample answer `Any$invalid_answer!` likely gets recorded as `Any!` because your shell treats `$invalid_answer` as an environment variable which gets expanded and likely doesn't exist. So, this might not be the best test answer.
