### ISSUE TITLE
missing config when using git clone

### ISSUE THREAD

**Issue by hydrargyrum** [copier-org/copier#1714]
### Describe the problem

When copier sees a template dir that's a dirty git repo, it will run git clone to a temp dir, and then try to commit dirty changes.
However, since no author is passed by copier, git will fail if no global user.name/user.email is set.

### Template

- init a git repo
- commit some files
- add untracked files

### To Reproduce

`copier /path/to/template .`

### Logs

```console
Command line: | /usr/bin/git --git-dir=.git --work-tree=/home/x/templates/pyproject commit -m 'Copier automated commit for draft changes' --no-verify --no-gpg-sign
Stderr:       | Author identity unknown
              | 
              | *** Please tell me who you are.
              | 
              | Run
              | 
              |   git config --global user.email "you@example.com"
              |   git config --global user.name "Your Name"
              | 
              | to set your account's default identity.
              | Omit --global to set the identity only in this repository.
              | 
```

### Expected behavior

Since the commit is temporary, the author information is not important.
I would expect copier to pass something like `--author='copier <copier@example.com>'` to `git-commit`

### Operating system

Linux

### Operating system distribution and version

debian

### Copier version

9.3.1

### Python version

3.12

### Installation method

pipx+pypi

**Comment by sisp** [comment]
I've submitted a PR that fixes this problem: #1716
