### ISSUE TITLE
Autodoc

### ISSUE THREAD

**Issue by Yajo** [copier-org/copier#173]
Readme's api docs are outdated. It would be best to have some kind of autodoc system. Even more if you think that fixing #110 would change them a lot.

**Comment by pawamoy** [comment]
[mkdocs](https://github.com/mkdocs/mkdocs) + [mkdocstrings](https://github.com/pawamoy/mkdocstrings) + [mkdocs](https://github.com/squidfunk/mkdocs-material) :smile: ?
