### ISSUE TITLE
Support Base Gitlab URL override

### ISSUE THREAD

**Issue by drandell** [copier-org/copier#1741]
### Actual Situation

We have a self hosted version of gitlab which has a different URL. Right now any gitlab links are hardcoded to start with https://gitlab.com

### Desired Situation

```yaml title="copier.yml"
base_gitlab_url = "https://custom.gitlab.com"
... everything else
```

### Proposed solution

Have an override that can be supplied in copier.yml to allow custom gitlab instances URLs

**Comment by pawamoy** [comment]
I'm not sure to understand. Are you speaking about the `gl` shortcut? You don't have to use the shortcut, you can use the full URL to your template repository, ending with `.git`.

**Comment by drandell** [comment]
> I'm not sure to understand. Are you speaking about the `gl` shortcut? You don't have to use the shortcut, you can use the full URL to your template repository, ending with `.git`.

Yes, i would like to use the gl: abbreviation as its nicer. Python Gitlab package has something similar in that you can specify the URL or you have a config file: https://python-gitlab.readthedocs.io/en/stable/cli-usage.html#configuration-files

**Comment by pawamoy** [comment]
I see, thanks. But... where would you want to configure that? In copier.yml? It would be too late :sweat_smile: You'd still have to type the full URL, so that Copier can clone the template, and find your configuration but... you already typed the URL.

**Comment by pawamoy** [comment]
This would only be possible if Copier had main, local configuration files.

**Comment by drandell** [comment]
Probably a bad example on my part! I was thinking of maybe a default environment variable that could be used if set, otherwise use the default gitlab.com URL?

**Comment by pawamoy** [comment]
Ah, an environment variable sounds doable! Something like `COPIER_GL_URL`, and `COPIER_GH_URL` for consistency.

**Comment by yajo** [comment]
Hello @drandell and welcome! Although I understand your request, shortcuts are only for the most common providers. If you use a different one, just use the full Git URL. Thanks for your report!
