### ISSUE TITLE
Allow copier templates to be in subdirectories of repositories

### ISSUE THREAD

**Issue by offbyone** [copier-org/copier#1748]
### Actual Situation

When using a git repository source, it would be nice to be able to define a template in a subdirectory instead of at the root:

```shellsession
$ copier copy gh:my-org/my-application/templates/default new-app
```

The reason here is that I'd like to maintain the templates for my application in the same source tree as the application itself, so that I can integration test them during releases, but _also_ make it very easy to instantiate them without asking my users to clone the repository first.

Right now, invoking this gives a stack trace:

```
Stderr:       | Cloning into '/var/folders/vg/rt3sgxfx6r951049hx0jl2ww0000gn/T/copier.vcs.clone.7n07gdm3'...
              | remote: Not Found
              | fatal: repository 'https://github.com/my-org/my-application/templates/default.git/' not found
```

### Desired Situation

Ideally, this would treat the `templates/default` as a path into the git repository after it is cloned, and use that as the root of the template instead.

### Proposed solution

`cookiecutter` offers this, to an extent, using the `--directory` flag; that would be a suitable option. Alternately, we could split the repo path along "obvious" lines and treat the first two segments as organization/repo and all later segments as path entries. 

That's only relevant to shortcut names, of course. We'd probably need the `--directory` flag for full repository URLs.

**Comment by pawamoy** [comment]
Have you tried the `_subdirectory` option in copier.yml?

**Comment by offbyone** [comment]
So, by that you mean I could still only have one template in a repository, but I could locate the template in a subdirectory?

That does in fact solve my issue. I missed that, thanks!

**Comment by sisp** [comment]
But keep in mind that

* `copier.yml` must be in the repository root and cannot be in the subdirectory, and
* the template version will be the same aa your application version, i.e. Git tags apply to both the application and the template which may be confusing.

**Comment by offbyone** [comment]
Yeah, there are some rough edges with it, but the co-versioning is desirable in my case.
