### ISSUE TITLE
Copier freezing during update

### ISSUE THREAD

**Issue by sevdesk-ryanp** [copier-org/copier#1751]
### Describe the problem

When running copier, it is either freezing, or taking an enormously long time to update the current project from template. This occurs even when I create a new project from template, create a dummy commit to the template and try to update. Is there any way to debug the issue through more --verbose logging? As far as I can tell it freezes right after _message_before_update and before tasks, 

but can't think of any reason it started to fail. I don't see a debug or verbose logging flag in the update docs. Any other ideas? 

### Template

I can't provide the template unfortunately. 

### To Reproduce

1. Run Copier copy
2. Add blank commit to template
3. Run Copier update on copied project

### Logs

```console
(dev) (base) ➜  ds-endpoint git:(development) copier update --trust --pretend
Updating to template version 0.2.65. <<freezes here for 10+ min
```

### Expected behavior

Successful update, logging of each step. along the way

### Operating system

macOS

### Operating system distribution and version

14.4.1 (23E224)

### Copier version

copier 9.3.1

### Python version

Python 3.11.0

### Installation method

distro package

### Additional context

Installed using brew/pixi

**Comment by pawamoy** [comment]
Most likely a duplicate of https://github.com/copier-org/copier/issues/1709.

**Comment by sevdesk-ryanp** [comment]
That was the issue! would it be possible to downgrade the version that's in brew while this is getting fixed? Brew doesn't make it easy to downgrade versions

**Comment by pawamoy** [comment]
No idea, we're not maintaining the brew package :sweat_smile:
