### ISSUE TITLE
Changing case in template breaks update (e.g. "Populate" -> "populate")

### ISSUE THREAD

**Issue by davidbrownell** [copier-org/copier#1767]
### Describe the problem

The update process does not work as expected (files aren't merged automatically) when case changes in the template. 

In the copier template referenced below, I introduce a change in `v2` that can be applied as expected. However, the [case-change](https://github.com/davidbrownell/copier-TemplateTest3/commit/00da3f0c53fc1cdf31d1dac22c6bad459cf244b9) in `v3` cannot be applied as expected.

### Template

https://github.com/davidbrownell/copier-TemplateTest3
https://github.com/davidbrownell/copier-TemplateTest3Output

### To Reproduce

1. [Works as expected] `copier copy https://github.com/davidbrownell/copier-TemplateTest3 --vcs-ref v1` [result is here](https://github.com/davidbrownell/copier-TemplateTest3Output/commit/64cebfab51a04987bbe327467696e73d952674bb)
2. [Works as expected] `copier update . --skip-answered --vcs-ref v2` [result is here](https://github.com/davidbrownell/copier-TemplateTest3Output/commit/8ae4f41e07c1f8828353c8325de0bb926e84b3f1)
3. [Does not work as expected] `copier update . --skip-answered --vcs-ref v3`

Note that the update results in a diff (in the screenshot section below) that is not automatically merged, and I haven't found a tool yet that is able to handle it correctly.

In this small example, the merge is fairly easy to resolve manually. The merge is much more complex in the [real code that prompted this investigation](https://github.com/gt-sse-center/copier-ProjectScaffolding).

### Expected behavior

The 3-way merge should work as it did when applying `v2` of the template.

### Screenshots/screencasts/logs

`git diff`:
![image](https://github.com/user-attachments/assets/762a2db4-c560-4df8-a463-36bc3914bfcc)

### Operating system

Windows

### Operating system distribution and version

Windows 11

### Copier version

9.3.1

### Python version

3.12.4

### Installation method

pip+pypi

**Comment by sisp** [comment]
Thanks for reporting this problem, @davidbrownell! :pray:

I've not been able to reproduce the problem _on Ubuntu 22.04_, Copier applies the update correctly for me. Could you share your Git version?

**Comment by davidbrownell** [comment]
Thanks for taking a look, @sisp. I am using `2.41.0.windows.1`. I will upgrade and let you know if I still see the issue.

**Comment by davidbrownell** [comment]
It worked! Upgrading to `git version 2.46.0.windows.1` seems to resolve the issue. Thanks so much for the help!
