### ISSUE TITLE
Save secret questions answers in seperate file

### ISSUE THREAD

**Issue by traverseda** [copier-org/copier#1798]
### Actual Situation

I'm using copier to deploy several docker containers and automatically configure stuff like single-sign-on. I have a `secrets_seed` setting that I'm setting using `secret: true` in copier.yml.

The user *must* put in exactly the same secret_seed value every time or else things will break. This is out of my control as fixing it would require forking the docker containers for several popular projects, which only set secrets inside the container the first time it's run. Cycling secrets is outside of the scope of my project.

`_skip_if_exists` can be used to reduce the damage from a user entering the wrong secret_seed value, but isn't a perfect solutions either it means I can't add new secrets to an existing secrets.env file. I'd need to make a secrets.env.d file and docker doesn't support globing for loading env files, so it would make the project much messier. 

### Desired Situation

I'd like to be able to save secrets into a separate yaml answers file that isn't checked into git, so that it can be included in backups but not in the git repo itself. This also reduces the risk of user-error from entering the wrong secrets_seed value.

This separate secrets.yaml file could be stored in backups along-side user data, but not checked into git.

**Comment by sisp** [comment]
Just an alternative idea: How about encrypting answers to secret questions and recording them like regular answers in the answers file? We could probably make this an opt-in feature that requires an encryption key (or key pair in case we want to support asymmetric encryption for some reason).

**Comment by traverseda** [comment]
I don't see much use of encrypting the secret_seed in my particular use case, as I need to store the salted and hashed generated secrets in cleartext to pass them to various services. Anyone who can see the in-use directory structure can see the secrets.

Right now my solutions is a wrapper script, I generate a `SECRET_SEED` file, and I wrap `copier update --data secret_seed=$(cat SECRET_SEED)`.

I definitely think the encrypted secrets makes sense for a lot of projects, most of them even. Just for my particular use-case, it would complicate things if multiple sysadmin work on the generated project tree.

**Comment by pawamoy** [comment]
If Copier was able to read and combine multiple answers files, you could generate the secrets YAML file yourself:

```django
secret1: "{{ secret1 }}"
secret2: "{{ secret2 }}"
```

Then

```bash
copier update --answers-file .copier-answers.yaml --answers-file secrets.yaml
```

**Comment by traverseda** [comment]
As an aside, I've done devops for a long time and I think using copier is a really exciting approach that gives the benefits of central project updates while allowing deep customization where it's needed. Beautiful project.

**Comment by sisp** [comment]
> I don't see much use of encrypting the secret_seed in my particular use case, as I need to store the generated secrets in cleartext to pass them to various services. Anyone who can see the in-use directory structure can see the secrets.

The idea behind encrypting secrets is all about allowing them to be versioned with Git as part of the answers file. Thus, you could Git-ignore the encryption key file instead of writing the cleartext secret to a separate answers file.

About supporting multiple answers files: How would we specify in which file an answer gets recorded?

**Comment by traverseda** [comment]
Yeah, less a full answers file and more a way to chainmap multiple yaml files together. One answers file and we can handle custom integrating on our own.

**Comment by yajo** [comment]
Are you using raw docker or docker compose?

**Comment by yajo** [comment]
Thanks everyone for your comments.

In docker compose you can add an extra .env file for the services that need it. That file can be skipped if exists and git-ignored. I've used this for years and it works very well.

In simple docker, you can have a similar result by mounting your separate secrets as a volume and reading the secrets file from your app code, or re-exporting them in the entrypoint.

So, this is not a problem in the copier side, AFACS. You just need to use the right tool for the job.

I hope you can fix your situation with these tips.

**Comment by traverseda** [comment]
Docker compose.

I believe I explained why I think that particular solution is less than ideal here:

>_skip_if_exists can be used to reduce the damage from a user entering the wrong secret_seed value, but isn't a perfect solutions either it means I can't add new secrets to an existing secrets.env file. I'd need to make a secrets.env.d file and docker doesn't support globing for loading env files, so it would make the project much messier.

While this would work it would essentially mean I'd need to create new secrets.env file every time I wanted to add or change a service in an existing docker compose. Want to add the option to run an app using postgres instead of mysql? New secrets file required.

>So, this is not a problem in the copier side, AFACS. You just need to use the right tool for the job.

I appreciate this project, and I know the average skill level from people opening issues on open source repos is pretty low, but I did go over why I think that solution is less than ideal. 

> You just need to use the right tool for the job.

>I hope you can fix your situation with these tips.

Comes off as pretty hostile, considering that I've mentioned that I already have two separate work-arounds that work well enough. It makes me wonder if you understood my original post. Maybe give this a more thorough read-through and discuss again, before dismissing it out of hand?

**Comment by pawamoy** [comment]
IIUC `_skip_if_exists` is not ideal because you can't *add* secrets (with new secret questions). In that case, have you considered handling the file containing secrets with a task?

**Comment by pawamoy** [comment]
(also, yes, please assume good faith from @yajo. you probably know how it is to maintain a popular open source projects: lots of feature requests that just *cannot* be implemented blindly, for many reasons)

**Comment by traverseda** [comment]
This may be a niche enough feature-request that it doesn't make sense to include, when I have a pretty reasonable work-around already.

Let me put together a minimal example that demonstrates this problem. All pseudo-code so bare with me. This is simplified, in real-life we don't need a redis password, but when dealing with complicated single-sign-on services stuff like this happens. Please don't get caught up in the details of the specific services, I just don't want to get too caught up in explaining complicated SAML/OAUTH/LDAP deployments.

```jinja
#secrets.env

#Sets the password at first_run, and only at first run. If this changes things break
postgres_password_firstrun={{secret_seed+"mysevice_postgres"|hash}}
myservice_db=postgresql://myservice:{{secret_seed+"mysevice_postgres"|hash}}@postgres

#Later on we added support for redis-based caching
{% if enable_redis %}
redis_password={{secret_seed+"mysevice_redis"|hash}}
myservice_redis=redis://myservice:{{secret_seed+"mysevice_redis"|hash}}@ipaddress
{% endif %}
```

```yaml
services:
  postgres:
    env_file: ./secrets.env

{% if enable_redis %}
  redis:
    env_file: ./secrets.env
{% endif %}

  myservice:
    env_file: ./secrets.env
```

In this scenario we started with just postgres and added support for redis based caching later on.

There are a ton of different ways to solve this, I've gone the wrapper script route to pass in `SECRET_SEED` that's stored in the directory tree but isn't saved to git, same with the `secrets.env`. So I do have an existing solution in place that I'm happy with. You could (in this particular example) also have a separate `redis_secrets.env` file, as docker does support multiple secrets. You can of course always write a custom task, which is flexible enough to do just about anything.

---

The way these issues are set up is designed to explain the problem space and not propose solutions, but I'd like to make a suggestion that would solve my problem and I believe would be more widely applicable.

Provide support for a separate `.copier_secrets.yaml`. Optionally encrypt that entire file with one or more passwords/keys. I think it makes sense for it to be a separate file rather than saved inline in .copier.yml for a number of reasons. One being that if for some reason you really needed to (like a leaked key) you could rewrite the git history to have never included that specific file.

**Comment by traverseda** [comment]
>Having encrypted and Git-tracked secrets would even allow Renovate to update a project that has secrets with a recent template.

That is my use case, sorry if I'm explaining it poorly. Re-generating files that rely on secrets, but making sure the secrets stay the same with each run. Except I don't want them tracked in git, I want them unencrypted and stored in an encrypted off-side backup, to better align with some change-management policies.

Would it make sense to open a separate feature request proposing that specific mechanism, and ignoring the use-case template?

**Comment by sisp** [comment]
I think this issue is sufficient.

We could implement it similar to the current answers file approach by exposing new Jinja variables `{{ _copier_conf.secrets_file }}` and `{{ _copier_secrets }}`, so this feature is opt-in by requiring the file template to be added by the template author. Further, we could add a CLI flag `--secrets-file` to override the secrets file name, and encryption could be enabled in user land via a CLI flag like `--secrets-key <key>` and/or `--secrets-key-file /path/to/crypt.key`. Just a first design proposal, open for discussion of course.

**Comment by yajo** [comment]
Hello! Sorry if I sounded rude. Indeed it wasn't my intention. 

My point was: can't you just add different secrets files? 

For your example, a separate `redis-secrets.env` file would solve your problems very simply.

**Comment by sisp** [comment]
> For your example, a separate `redis-secrets.env` file would solve your problems very simply.

I think the problem turna out to be the UX where a recopy or update currently doesn't prefill the questionnaire with the previous answers, so a separate file like `redis-secrets.env` plus `_skip_if_exists` to avoid changing the initial secrets. As (sort of) mentioned above, this prevents secret rotation, and even though @traverseda doesn't need it, I think it's something we should be able to support.

**Comment by traverseda** [comment]
>For your example, a separate redis-secrets.env file would solve your problems very simply.

In that specific example with docker yes. I'm still exploring the problem space but it becomes trickier when dealing with single-sign-on. Docker is by far the easiest example of this use case, but when you're talking about generating tokens for OIDC connect profiles that don't support including multiple files, and then you realize you need to change a file, it gets much trickier.

**Comment by yajo** [comment]
> this prevents secret rotation

It's a bit tricky, yes. However, all you need to do is delete the file and update. Or you can simply edit the file in place, given it's git-ignored.

For more complex scenarios, still Copier is probably not the best tool in your belt. Better tools (some mentioned already):

- https://github.com/bitnami-labs/sealed-secrets
- https://github.com/getsops/sops
- https://www.vaultproject.io/
- https://docs.ansible.com/ansible/latest/cli/ansible-vault.html

Those projects exist to provide a nice UX to the problem of deploying secrets. Each one has its pros and cons, and different scope. All of them need to deal with the complex machinery involved in cryptography, and are constantly updated to deprecate vulnerable algorithms and support newer ones.

Is all that an important subject in software development and deployment? Absolutely! Is it within Copier's scope? I still don't think so.  😅

So, probably you'll have to pick the best tool for your particular likes and needs and integrate it. If the integration is done at Copier level, then you can create a Jinja extension to support it and use it in Copier, or you can just feed some secrets to some CLI using Copier tasks and let that tool generate the secrets. However, probably the best integration will still be at the deployment level. For docker, that can be environment variables, volumes, entrypoints, etc. 

Still the solution you find can be interesting to others, so please share your findings so others can benefit too! ❤️

**Comment by traverseda** [comment]
It would be a lot easier to integrate SOPS into this cleanly if there was a way to import yaml.

The canonical way to decrypt data with SOPS is 

`cat encrypted-data | sops decrypt --input-type yaml --output-type yaml /dev/stdin > decrypted-data`

Now if I have a separate copier_secrets.yml it's much easier to deal with this in a natural way and still update templated files that contain secrets.

I actually am in favour of handling encryption separately, but being able to import another yaml file, and throw an error if it's not there, seems like base functionality for a lot of this stuff.

**Comment by traverseda** [comment]
Oh wait, If I'm not storing the secrets in git I can't update them anyway, it would just overwrite them. My mistake, I think you're absolutely right in hindsight. They really do need to be fully idempotent with no end user interaction. That will complicate my plans for a number of files. Thanks for taking the time to talk through this with me.
