### ISSUE TITLE
More flexible now function

### ISSUE THREAD

**Issue by pawamoy** [copier-org/copier#182]
I know the goal is not to replicate all cookiecutter's features, but I'd like to be able to use `now` with arguments to format the result, for example to output the year only.

They use [jinja2-time](https://pypi.org/project/jinja2-time/) in cookiecutter, which allows to do things like:

```
{% now "utc" "%Y" %}
```

Also your `now` function is UTC only, and not everybody wants to use UTC :slightly_smiling_face:

**Comment by Yajo** [comment]
I like the feature. @pykong WDYT?

We should deprecate the current `now()`, but don't remove it until v4 at least.
