### ISSUE TITLE
Problem updating a project created from a recursive template

### ISSUE THREAD

**Issue by hribera** [copier-org/copier#1839]
### Describe the problem

We have a copier template that has the following structure (simplified):
```
copier-template/
├── project
│   └── {{ repo_name }}
│       ├── {{ _copier_conf.answers_file }}
│       ├── Dockerfile
│       ├── LICENSE
│       ├── Makefile
│       ├── pyproject.toml
│       ├── tests
│       └── README.md
├── copier.yml
├── pyproject.toml
├── README.md
└── tests
```
The `copier.yml` file is:
```
# CONFIGURATION -------------------------
_subdirectory: project
_templates_suffix: ""
_jinja_extensions: []

# PROMPT --------------------------------
repo_name:
[and so on...]
```

We created a project using this template named `copier-project`.

Then we updated the template to have another file named `CONTRIBUTING.md` inside the `{{ repo_name }}` folder, and updated the version of the template with its corresponding tag and all.

We then wanted to update the project `copier-project` created using this template. So within the folder `copier-project` we ran:
```
poetry run copier update --skip-tasks --skip-answered --trust --vcs-ref=HEAD .
```
Which updated the project with the message `Updating to template version 0.2.7` and no errors.

However, we saw that the update command had created a new folder within `copier-project` named `copier-project` and had added the `CONTRIBUTING.md` file within this new folder, which completely breaks the structure of the project:
```
copier-project/
├── .copier-answers.yml
├── Dockerfile
├── LICENSE
├── Makefile
├── pyproject.toml
├── tests
├── README.md
└── copier-project
    └── CONTRIBUTING.md
```

### Template

The template used is a private template and cannot be shared.

### Expected behavior

We would have expected that the `CONTRIBUTING.md` file to be added in the `copier-project` folder.

### Operating system

Linux

### Operating system distribution and version

20.04

### Copier version

9.4.1

### Python version

3.11

### Installation method

pip+pypi

### Additional context

I have found that in [here](https://copier.readthedocs.io/en/stable/configuring/#subdirectory) it specifies that for recursive templates one should use the `_subdirectory` option in configuration. However, we weren't able to add the `{{ repo_folder }}` as a `_subdirectory` directly, so we added the `project` folder to get around the problem. We do need to have tests for the template, have a separate `pyproject.toml` for the template, among other things, so that is why we can't use the root directly either.

**Comment by pawamoy** [comment]
Hi @hribera, thanks for the report.

I believe that's the same issue as #1617, and I would therefore characterize it as "misuse". Can you check #1617 and tell us if that helps you solve your problem?
