### ISSUE TITLE
Support for Creating Multiple Files from Space-Separated List Input

### ISSUE THREAD

**Issue by aran159** [copier-org/copier#1847]
### Actual Situation

I would like to know if it's currently possible to create multiple files based on a space-separated list input using Copier's Jinja templating. 

### Desired Situation

For example, if I define a CLI question like this:

```yaml
my_list:
  type: str
  help: "Space separated list."
  placeholder: "value_1 value_2"
```

I would like to create multiple files using the following Jinja syntax:

```text
{% for item in my_list.split() %}{{ item }}{% endfor %}
```

This would generate two files named `value_1` and `value_2`.

I would expect this functionality to work similarly to the conditional files and directories feature outlined [here](https://copier.readthedocs.io/en/stable/configuring/#conditional-files-and-directories). I have been looking for tests in the repository for this specific feature but have only found tests related to conditional files and directories.

So, I am curious if this functionality is already supported. If not, does it make sense to add this feature?

Thank you!

**Comment by pawamoy** [comment]
See https://github.com/copier-org/copier/issues/1271.
