### ISSUE TITLE
Better handle empty suffix

### ISSUE THREAD

**Issue by pawamoy** [copier-org/copier#186]
I tried to bypass (:smiling_imp:) using a suffix for templates with `_templates_suffix: ""` in my `copier.yml`. Unfortunately it didn't work as expected: only directories were rendered (see #185), and no file was copied/rendered at all, even files with no extension.

Not sure what the code is doing with the suffix, but surely an error/warning could be displayed if the suffix is empty.

**Comment by Yajo** [comment]
Why would you like to resolve the suffix before answering? 🤔

**Comment by pawamoy** [comment]
For the same reason as in #197, i.e. to avoid prompting the users for nothing. We could argue however that, supposedly, the template writer already made sure the template is working, and didn't set an empty suffix as it doesn't work. In that case, maybe we could simply tell in the documentation that an empty suffix is invalid.

**Comment by Yajo** [comment]
Ah I see. Well, I think that the case of empty suffix, meaning that all files are templates, should be valid.

**Comment by pawamoy** [comment]
Alright! Then I'll try to send a PR with a fix 🙂
