### ISSUE TITLE
Multiline interactive input

### ISSUE THREAD

**Issue by Yajo** [copier-org/copier#210]
This would be very helpful to write things like multiple paragraphs of text, or long YAML lists, etc.

**Comment by pawamoy** [comment]
`prompt_toolkit` seems to be a great candidate.

Multi-line support, validation (useful for copier's prompt types), highlighting, and [so much more](https://python-prompt-toolkit.readthedocs.io/en/stable/pages/asking_for_input.html#asking-for-input).

**Comment by Yajo** [comment]
Quite amazing, yes.
