### ISSUE TITLE
Single-file templates

### ISSUE THREAD

**Issue by sswatson** [copier-org/copier#231]
I often want to use copier's functionality to produce a single file, rather than a directory. This is a commonly [requested feature for cookiecutter](https://github.com/cookiecutter/cookiecutter/issues/35), but it isn't supported. I'm wondering whether copier supports it, and if not, then whether it would make sense to add support.

**Comment by Yajo** [comment]
For copier, both the source and the destination arguments must be directories. However, if the source contains only 1 file, then only that file will be copied. Although this is pretty obvious, so I guess your template contains several files, right?

If the source directory contains several files, you can pick just one by using the `--exclude` flag twice to exclude all but the file you want. Example:

```bash
➤ copier --exclude '*' --exclude '!file-i-want' copy template/ destination

    create  file-i-want


➤ tree
.
├── destination
│   └── file-i-want
└── template
    ├── file-i-dont-want
    └── file-i-want
```

I guess this solves your problem, so I close. Please reopen if needed.

**Comment by sswatson** [comment]
Yes, this is perfect. I guess the point is that this problem is implicitly solved by copier's flexibility to copy to a directory which already contains files. I agree that this should have been obvious, but I overlooked it. Glad to have the more general solution you described as well. Thanks!
