### ISSUE TITLE
Files which aren't updated on 'update'

### ISSUE THREAD

**Issue by baurmatt** [copier-org/copier#234]
Hey,

is it possible to have files from the copier template only initially copied to the new project and not updated on `copier update`? This would be really helpful for files like README.md where you want to provide a initial version but recognize that it might change heavily over time.

Thanks! :)

**Comment by pawamoy** [comment]
I think you are interested in the `skip` [special option](https://github.com/copier-org/copier#special-options) ?

**Comment by baurmatt** [comment]
@pawamoy Thanks, this sounds exactly like what I'm looking for! :)
