### ISSUE TITLE
Don't run task on update

### ISSUE THREAD

**Issue by baurmatt** [copier-org/copier#238]
Hey,

I'd like to have a task (`git init`) which is run on `copy` but not on `update`. Is this possible?

Thanks! :)

**Comment by pawamoy** [comment]
Related to #196. In a more generic manner, it would be nice to have finer control over when a task is executed.

**Comment by pawamoy** [comment]
Maybe the most straight-forward way to implement this functionality would be to set additional environment variables (or change the current ones) when executing tasks. Currently we just have `STAGE=task`. What about `STAGE=copy` and `STAGE=update` instead?

**Comment by baurmatt** [comment]
I would suggestion not changing the `STAGE` environment variable as this would be a breaking change for existing users. Perhaps just implement a new environment variable `OPERATION` which can by `copy` or `update`?

**Comment by Yajo** [comment]
Closing as duplicate of #240.
