### ISSUE TITLE
Copy file with any suffix

### ISSUE THREAD

**Issue by tomgrin10** [copier-org/copier#246]
This tool is great!
But the only thing stopping me from using this over Cookiecutter is the need to suffix my files.
Maybe I missed this option, but I would love it if `_template_suffix: *` was a thing.

**Comment by Yajo** [comment]
I understand this would be nice to have, but it was a decision taken long ago, and complicates some valid use cases such as having `README.md` for your template along with `README.md.tmpl` for your subproject, or having a `LICENSE` for your template while using [a templated `LICENSE.tmpl` for the subproject, like here](https://github.com/Tecnativa/doodba-copier-template/blob/f131aead5f95e1bdf96ca9bde3b4760dd45228c4/%7B%25%20if%20project_license%20%25%7DLICENSE%7B%25%20endif%20%25%7D.jinja).

In any case, right now this is not supported.

> the only thing stopping me from using this over Cookiecutter is the need to suffix my files

IMHO this is an exaggeration. I see not suffixing just as a commodity after all, but it doesn't seem a blocking point.

In any case, we're open to PRs.

**Comment by Yajo** [comment]
I'm going to close this issue just to keep our issue tracker clean, and to don't give the impression we're gonna work on this while we won't at the moment. But as said, PRs are welcome. Thanks for your contribution!
