### ISSUE TITLE
When copier fails, it should not delete the destination path when it pre-exists

### ISSUE THREAD

**Issue by matt2000** [copier-org/copier#262]
## Steps to reproduce:

On OSX:
```
$ mkdir fail-copier/
$ echo '_tasks: [ "exit 1" ]' > ../fail-copier/copier.yaml
$ mkdir my-project
$ cd my-project/
$ echo "doomed" > file.txt
$ copier ../fail-copier .
> Running task 1 of 1: exit 1
Something went wrong. Removing destination folder.
```

## Expected results

The 'my-project' directory should be unmodified and `file.txt` should still exist.

## Actual Results

The 'my-project' directory and all its files are destroyed.

## Possible solution proposal

The project could be rendered to a folder created by copier, like `.copier-tmp` and right before exit, copier can safely remove that dir on failure, or its fully-rendered contents can be moved to the specified destination.

**Comment by Yajo** [comment]
There's an API flag `cleanup_on_error` that is `True` by default. AFAICS there's no CLI flag to disable it, so it should be added indeed.

**Comment by languitar** [comment]
This is extremely unexpected when updating an existing project. I don't think this ever makes sense for updates. Only for the initial creation.

**Comment by Yajo** [comment]
In updates, it doesn't happen already. See https://github.com/copier-org/copier/blob/aa1bfa1deda340b136a9cc94f1e0deaebf529e37/copier/main.py#L150

For copies and new CLI flag, see #273.

**Comment by ppo** [comment]
> In updates, it doesn't happen already. See
> 
> https://github.com/copier-org/copier/blob/aa1bfa1deda340b136a9cc94f1e0deaebf529e37/copier/main.py#L150
> 
> For copies and new CLI flag, see #273.

Well, yes, it happens during update 😕
v5.1.0 has the same code but the destination folder was deleted.

https://github.com/copier-org/copier/blob/2cf5be072a09d68f0743a50a5573b094964bda16/copier/main.py#L149
