### ISSUE TITLE
Bug when comparing untagged versions

### ISSUE THREAD

**Issue by Yajo** [copier-org/copier#269]
The error can be seen in [this build log](https://github.com/copier-org/copier/runs/1103825373?check_suite_focus=true#step:13:129).

When an update happens between 2 commits and some of them happen to be formed as valid PEP 440 versions, they get compared and can actually be considered a downgrade. That'd be a false positive.

Gotta fix that.

**Comment by pawamoy** [comment]
Hey @Yajo, the logs have expired, could you provide a new example and hardpost it here :sweat_smile: ?

**Comment by pawamoy** [comment]
As for commit sha identified as a PEP440 version, I guess it happens when the commit sha is only composed of digits.
I never saw a version like `57339573` or `2039958`, so maybe there's an easy way to fix this by checking the version length (in this specific case of all-digit version of course).

**Comment by Yajo** [comment]
> the logs have expired, could you provide a new example and hardpost it here 😅 ?

😬 I didn't know that happens. I'll do it the next time I hit it.

Regarding the issue, I see that, if you pip-install any project from git, pip converts any commit into a valid PEP440 version. I'd like to find out how it works and reuse that if possible.

**Comment by Yajo** [comment]
I was trying to solve this one, but I guess I need somebody to answer https://stackoverflow.com/q/68234174/1468388.

**Comment by pawamoy** [comment]
There's an answer now :slightly_smiling_face: 
So you can look into poetry-dynamic-versioning. PDM also has code to build such PEP440 versions in a git repository.
I'll try to give a concrete example later.

**Comment by Yajo** [comment]
Somebody answered something useful. It turns out https://github.com/mtkennerly/dunamai is the library that handles that part. This might work.

**Comment by Yajo** [comment]
https://github.com/mtkennerly/dunamai/issues/20 would answer the last part of my question.
