### ISSUE TITLE
Allow custom filters

### ISSUE THREAD

**Issue by baurmatt** [copier-org/copier#277]
I'd like to include a custom filter in my copier template which uses hmac to generate a secret.

```python
import binascii, hashlib, hmaci
hmac.new(binascii.unhexlify(key), msg.encode(), hashlib.sha256).hexdigest()
```

But I currently don't see an option to make this possible. Best idea I'd come up with was to include a task with search&replaces the generate template.

**Comment by pawamoy** [comment]
Related to #208, #182 and the discussion in #229.

**Comment by Yajo** [comment]
As the project is right now, you came up with a good solution.

Further progress is discussed in #208, so closing as duplicate.
