### ISSUE TITLE
Add an "assume-yes" option

### ISSUE THREAD

**Issue by ddidier** [copier-org/copier#301]
Hi, I'm trying to automate project creation for testing reasons. I cannot find way as a CLI option or in code to do that. Basically, I'd like to call something like `copier --answers-file "my-answers.yml" copy path/to/project/template path/to/destination -y`. Note the `-y` flag which stands for "assume-yes: automatically answer yes to all questions" like in so many CLI like `apt` or `yum` for example. Is there any workaround meanwhile? Thanks.

**Comment by Yajo** [comment]
Yes, there is `--force`
