### ISSUE TITLE
Reintroduce --no-diff option for update

### ISSUE THREAD

**Issue by ppg** [copier-org/copier#302]
I was reading #270 and I think there is a use case of wanting to use `--no-diff` with `update`. My workflow is:

1. Run `copier <template_src> .` to initialize a repo; we consider files laid down by `copier` to be 'owned' by it and not allowed to be modified.
2. Periodically run `copier --force update` to apply the latest copier `template_src` and/or retake control of files that might have been inadvertently changed.

Because `--no-diff` didn't exist for a while, and when it did exist it didn't work correctly, the way we make this work is to omit `_commit` from `.copier-answers.yml` with something roughly like:
```
{% set commit = _copier_answers.pop('_commit') -%}
{{ _copier_answers|to_nice_yaml }}
{% set _ = _copier_answers.update({ '_commit': commit }) -%}
```
This forces `copier` down the `copy_local` path here: https://github.com/copier-org/copier/blob/v5.1.0/copier/main.py; aside from the hard-coded (or non-working) `only_diff`, that was the only knob it appeared we could use to control this behavior. This has the downside of having to 'pluck' `_commit` from the `.copier-answers.yml` in that odd fashion to trigger this behavior, and thus we do not have record of what version of our `template_src` was used for the last run.

`--no-diff` as documented in v5.1.0 is precisely what we want, so that we could add back `_commit` to our `.copier-answers.yml` and run:
```
copier --force --no-diff update
```
This would behave like a `copy` but with out requiring `template_src` and `destination_path`, since those are known from the `.copier-answers.yml` and it's location, respectively. I tested this behavior out locally by modifying `config/factory.py` on `v5.1.0` to 'fix' the `--no-diff` bug:
```
$ diff config/factory.py.bak config/factory.py
77c77,79
<     init_args = {k: v for k, v in locals().items() if v is not None and v != []}
---
>     init_args = {k: v for k, v in locals().items() if v is not None and v != [] and k != "kwargs"}
>     for k, v in kwargs.items():
>         init_args[k] = v
```
I am not sure if this is the right 'fix', nor have tests, but it moves `only_diff` into `init_args` instead of nested under the `kwargs` key (as #270 points out); this seems like potentially the wrong behavior no matter if `--no-diff` is present or not? And with this change `only_diff` correctly makes it's way back to `main.py#copy` and triggers `copy_local` as desired.

What are the chances to add back in this feature, or in some other way expose the ability to control this functionality? To take a small step back, what I'd actually prefer is if I had a way to specify in the configuration the `update` behavior: some files I'd like to just overwrite (no diff, blow away any manual changes) and others I'd like to merge (diff, keep manual changes), controlled by the `template_src`. The first of those is the more desirable behavior, as one can usually inject entry points into generated code to enable customization in almost all cases; that's why `--no-diff` is appealing as it allows that behavior and seems much easier than trying to control on a file-by-file basis.

**Comment by Yajo** [comment]
I understand your use case.

I think that the best solution would be to introduce a new command `copier recopy`, which would just reapply the template with current answers but ignoring update diff. If you want to use that for update, we'd have to support something like `copier recopy --latest`.

Copier is under a big refactor, and this is not very high priority right now, so you probably will have to wait for awhile. I'm glad you found that workaround and possibly it will be helpful for others for the time being.

**Comment by ppg** [comment]
If you have to add the `--latest` flag anyway, how would that differ from just running `copier copy --latest`? `copier copy ...` already reuses answers, that's how I develop locally:

**Comment by ppg** [comment]
For anyone reading this in the future, this is what I went with for the `.copier-answers.yml` template:
```
{% set _ = _copier_answers.update({ 'commit': _copier_answers.pop('_commit') }) -%}
{{ _copier_answers|to_nice_yaml }}
{% set _ = _copier_answers.update({ '_commit': _copier_answers.pop('commit') }) -%}
```
That allows me to kick `update` into the `--no-diff` (or `copy` or `recopy) behavior but also record the commit of `template_src` that I last ran against. Then to reapply you just run `copier --force update` as desired.

**Comment by Yajo** [comment]
You can just `copier copy` again now, in master. If not fixed please reopen.
