### ISSUE TITLE
Allow custom jinja filters and tests

### ISSUE THREAD

**Issue by ppg** [copier-org/copier#303]
Jinja purposely limits the amount of logic and 'code' you can put into your templates, which makes sense, but they also then allow injecting custom filters and tests so you can expose more complicated helpers that the templates use. [get_jinja_env](https://github.com/copier-org/copier/blob/v5.1.0/copier/tools.py#L112-L128) allows passing in `filters`, but the call sites don't pass through any. It would be nice if there was a way to define custom filters in my `template_src` that are available to me when rendering files.

**Comment by ppg** [comment]
This might be a dupe of a the suggestion https://github.com/copier-org/copier/issues/208#issuecomment-699608983. I did find that file when looking for something like this issue, but thought it was only about adding one filter until I read all the way to the bottom.

**Comment by Yajo** [comment]
Yes, it's duplicate. Thanks for the report anyway :blush:
