### ISSUE TITLE
Copier changes LF to CRLF for some files (on Windows)

### ISSUE THREAD

**Issue by karolzlot** [copier-org/copier#308]
I am on Windows and I am generating from my simple template. 

In template all files have LF endings, but when any file is changed by Copier it is saved with CRLF.

I noticed it because it also changed .sh files this way and therefore broke them (I am using them in WSL to automate deploy to cloud etc.)

**Comment by Yajo** [comment]
I'm not sure if Copier is the responsible for this or git. 

Check https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf please.

Closing issue assuming I'm right, but please reopen otherwise :blush:

**Comment by qqgg231** [comment]
I set 'git config --global core.autocrlf true' and it didn't help. (it was set to `input` before)

I think you can reopen, it is something different.

**Comment by Yajo** [comment]
Please let's avoid git for once so we double-check it's copier.

1. Create a template with some file that uses CRLF.
1. `copier that-template a-new-folder`
1. Check if the created file inside `a-new-folder` has CRLF too.

**Comment by ideahitme-twin** [comment]
Related question where when using Copier + Jinja on Mac OS CRLF gets converted into LF. Not sure if it should be addressed by Copier or Jinja. 

(No git involved at all here) 

Here is my basic template:

```
$ tree template 
template
├── ApiClient.cs.jinja
└── copier.yml
0 directories, 2 files
$ cat template/copier.yml | wc -l
       0
$ cat -e template/ApiClient.cs.jinja 
//----------------------^M$
```

Now generate a project

```
$ copier template gen
Copying from template version None
    create  .
    create  ApiClient.cs
```
Check the line ending in ApiClient.cs

```
$ cat -e gen/ApiClient.cs 
//----------------------$
```

Any idea what if this is something configurable ?

**Comment by karolzlot** [comment]
I think it can be closed for now. If I will ever have it again I will let know.
