### ISSUE TITLE
Make the docs landing page more friendly (include simple template example)

### ISSUE THREAD

**Issue by epogrebnyak** [copier-org/copier#323]
I'm new to copier, but it looks this sentence in docs may need correction:

> If a YAML file named copier.yml is found in the root of the project (alternatively, a YAML file named copier.yaml), the user will be prompted to fill in or confirm the default values.

https://copier.readthedocs.io/en/stable/creating/

Also substituting values seems a part of core logic of copier, yet there is nothing about it on the front page of the docs. You provide for copying examples (like `shutil.copy`), but the user like myself is more interested how to provide custom values for package name, author etc. It would be great if starting examples helped with that.

**Comment by pawamoy** [comment]
Isn't what you're searching for in the next chapter, customization?

**Comment by epogrebnyak** [comment]
> Isn't what you're searching for in the next chapter, "configuring a template"?

Indeed, but why spend frontpage examples on just copying directories? Anyways, it is just an enhancement suggestion.

**Comment by pawamoy** [comment]
Oh I see what you mean now. In the overview we only show how to generate a project, and you suggest we should add a small example of how to write a template. Maybe something with a folder tree, and one file using Jjinja templating. What do you think @Yajo 🙂 ?

**Comment by Yajo** [comment]
Yes, the landing page is not so nice.

**Comment by epogrebnyak** [comment]
> Maybe something with a folder tree, and one file using Jjinja templating. 

My idea of what people look at on the first page: oh, it is a coockiecutter alternative? Is it easy to use? How can I mark the template? How can I provide the values to fill? Are there any special behaviours?

Similar page: https://cookiecutter.readthedocs.io/en/1.7.2/first_steps.html#your-first-cookiecutter

**Comment by Kilo59** [comment]
Even a couple of links to some actual copier template repos would go a long way.

Somewhat related, could you add a `copier` github tag to the project? and add the same tag to a good example template repos to make them more discoverable?

**Comment by Yajo** [comment]
You probably overlooked this section: https://copier.readthedocs.io/en/stable/#browse-or-tag-public-templates

However, it's true that I could tag Copier itself with that. It's not exactly a template, but it's certainly related to that topic.

**Comment by pawamoy** [comment]
I just looked at the `copier` tag/topic on GitHub, and I wonder if `copier-template` would not be better, because there are quite a number of unrelated projects using the `copier` tag. I'm already using both of them in my templates, and `copier-extension` for my Copier+Jinja extension.
