### ISSUE TITLE
Problems getting started on Windows 10 (WAS: Why is Copier not running with pipx's python?)

### ISSUE THREAD

**Issue by Cecron** [copier-org/copier#324]
First time user on Windows 10 here. I installed copier using pipx according to the instructions. I did not expect courier to fail based on the fact that Python is not in my PATH. I assumed courier would be supplied with Python from within pipx...

If this is intentionally, I'm curious of the reason.
Or perhaps this is a template specific thing? If so, are there any basic "poetry-based" templates available I could start with?

```
PS C:\proj\python> pipx install copier
  installed package copier 5.1.0, Python 3.9.1
  These apps are now globally available
    - copier.exe
PS C:\proj\python> copier "gh:pawamoy/copier-poetry" firstProject
...
    create  tests\__init__.py

 > Running task 1 of 1: python scripts/post_generation.py
'python' is not recognized as an internal or external command,
operable program or batch file.
...
```

I keep my python virtual environments in the project directory, so this looks like a chicken and the egg problem to me... ;-)

**Comment by pawamoy** [comment]
It could be because the Windows subprocess (when running the Python task) does not have the same PATH as your shell.

I see three potential solutions:

- passing `shell=True` to the subprocess command
- resolving `python` to its absolute path before running the subprocess
- on the user side, properly set the PATH environment variable (for the user account preferably, not the system), by adding the directory where your Python executable is

> If so, are there any basic "poetry-based" templates available I could start with?

I was going to advertise my template but I see you are currently using it and it's failing :sweat_smile: 
Hopefully one of the solutions above will work!

**Comment by Cecron** [comment]
Note that I purposely don't have Python in my PATH, since I use a pipx installed poetry and keep my virtual environments inside my project directories.

For now I went with solution 3, by creating and activating a virtual environment and my firstProject was created successfully. :-)

However, now I have the same questions about make, is it a mandatory requirement I missed?
(Sphinx e.g. is supplying a make.bat for the Windows platform.)
I do have git installed and in the path, but that is not shipped with make. :-(

```
PS C:\proj\python\copier> py -3 -m venv --prompt . .venv
PS C:\proj\python\copier> .\.venv\Scripts\Activate.ps1
(copier) PS C:\proj\python\copier> copier "gh:pawamoy/copier-poetry" firstProject
...
 > Running task 1 of 1: python scripts/post_generation.py
Project sucessfully generated!
Run `make` to show the available actions.

(copier) PS C:\proj\python\copier> make
make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program.
```
Thanks for helping me out. I heard about copier and really like the fact that it seems to handle more than just the initial template creation. I got the impression that copier would work on Windows, but perhaps not out-of-the-box ;-)

Perhaps I should have created a new issue, but I opted for editing the title for this one instead in order to minimize issue pollution ;-)

**Comment by pawamoy** [comment]
> Note that I purposely don't have Python in my PATH, since I use a pipx installed poetry and keep my virtual environments inside my project directories.

I fail to see how this relates? You can totally have Python in your PATH and still use pipx and tools installed with pipx normally.

> For now I went with solution 3, by creating and activating a virtual environment and my firstProject was created successfully. :-)

Solution 3 was about setting your PATH variable to include your system/user-account Python executable directory. Did you add the virtualenv Scripts directory instead?

> However, now I have the same questions about make, is it a mandatory requirement I missed?

It is not. In my copier-poetry template, make is just a helper. Anything you can call with `make TASK ARG=VALUE`, you can also call with `poetry run duty TASK ARG=VALUE`. And yeah, no make on Windows, unless you want to try the Mingw32 version through Conda or Chocolatey. I do not explicitly support Windows in my template.

> I got the impression that copier would work on Windows, but perhaps not out-of-the-box ;-)

It should work indeed, but some things can break. Check out the test suite: some tests are marked as "OK to fail". @Yajo spent many hours improving the test suite for Windows as well, but sometimes Windows won't help :confused:

**Comment by Yajo** [comment]
>  > Running task 1 of 1: python scripts/post_generation.py
> 'python' is not recognized as an internal or external command,
> operable program or batch file.

AFAICS, the task is executing `python`, which is not in your `$PATH`, so there's nothing Copier can do here. 🤷🏼‍♂️ 

The template itself should have a README where it tells you what things must be installed for it to work, and if you don't fill the requirements, then it will fail just like any other software.

Other than that, Copier runs in Windows mostly fine, although there are some rough edges that I haven't been able to fix, possibly due to some OS limitations.

**Comment by Cecron** [comment]
> Solution 3 was about setting your PATH variable to include your system/user-account Python executable directory. Did you add the virtualenv Scripts directory instead?
> 

I cheated ;-) If you look in the code-box I activated the virtual environment, which to my knowledge achieves the same goal.

> It is not. In my copier-poetry template, make is just a helper. Anything you can call with `make TASK ARG=VALUE`, you can also call with `poetry run duty TASK ARG=VALUE`. See [Tasks](https://pawamoy.github.io/copier-poetry/work/#tasks). And yeah, no make on Windows, unless you want to try the Mingw32 version through Conda or Chocolatey. I do not explicitly support Windows in my template.

Ah, so the output

`Run make to show the available actions.`

is only to support the "Makefile for convenience" bullet in the template documentation. ;-)

Thanks for the clarification!
It seems my next step will be to, based on your template, try and create a basic template without the "convenience". ;-)
