### ISSUE TITLE
Do not ask for updating .copier-answers.yml

### ISSUE THREAD

**Issue by Cecron** [copier-org/copier#325]
I did not expect to have to force update .copier-answers.yaml after running `copier update`, so I'm probably doing something wrong...

This is my result at `copier update`:
```sh
PS C:\copier-template> cd ..
PS C:\> copier update myproj
No git tags found in template; using HEAD as ref

package_name? Format: yaml
...
copyright_license? Format: yaml
🎤 [CC-BY-4.0]:
Either 1b4d418 or None is not a PEP 440 valid version.

    create  .gitignore
 identical  copier.yaml
 identical  pyproject.toml
  conflict  .copier-answers.yml
 Overwrite C:\myproj\.copier-answers.yml? [Y/n]
     force  .copier-answers.yml
```
(I now also noted that stray comment about `Either 1b4d418 or None is not a PEP 440 valid version.`...)

The changes in .copier-answers.yml doesn't strike me as odd, (except perhaps the ^M ;-)
```sh
PS C:\> cd myproj
PS C:\myproj> git diff
diff --git a/.copier-answers.yml b/.copier-answers.yml
index 2850703..ba49cb9 100644
--- a/.copier-answers.yml
+++ b/.copier-answers.yml
@@ -1,5 +1,5 @@
 # Changes here will be overwritten by Copier
-_commit: 1b4d418
+_commit: a86b2dd^M
 _src_path: copier-template
 author_email: Cecron@example.com
 author_name: Cecron
```

<details>

I'm on Windows 10 and the full transcript of my actions are:
### Create a directory to place the template in:
```sh
PS C:\> mkdir copier-template
PS C:\> cd copier-template
```
### Create a short `pyproject.toml.tmpl` with ninja variables like `[[ package_name ]]`:
```sh
PS C:\copier-template> type pyproject.toml.tmpl
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "[[ package_name ]]"
version = "0.1.0"
description = "[[ package_description ]]"
authors = ["[[ author_name ]] <[[ author_email ]]>"]
maintainers = ["[[ author_name ]] <[[ author_email ]]>"]
license = "[[ copyright_license ]]"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
```
### Create `copier.yaml` with questions and settings
```sh
PS C:\copier-template> type copier.yaml
package_name: my-package
package_description: A short description of the package.
author_name: Cecron
author_email: Cecron@example.com
copyright_license: "CC-BY-4.0"

_exclude:
    # Exclude git repo
    - ".git"
    # Don't match emacs backup files
    - "*~"
```
### Create `[[ _copier_conf.answers_file ]].tmpl` so copier registers answers
```sh
PS C:\copier-template> type *answers*
# Changes here will be overwritten by Copier
[[_copier_answers|to_nice_yaml]]
```
### Register template and commit to git:
```sh
PS C:\copier-template> git init
PS C:\copier-template> git add .
PS C:\copier-template> git commit -m "Initial template version"
```
### Run copier to create project
```sh
PS C:\copier-template> cd ..
PS C:\> copier copier-template myproj
  # Answer questions
  package_name? Format: yaml
  🎤 [my-package]:
  package_description? Format: yaml
  🎤 [A short description of the package.]:
  author_name? Format: yaml
  🎤 [Cecron]:
  author_email? Format: yaml
  🎤 [Cecron@example.com]:
  copyright_license? Format: yaml
  🎤 [CC-BY-4.0]:
      create  copier.yaml
      create  pyproject.toml
      create  .copier-answers.yml
```
### Run Poetry to install project dependencies and create Python virtual environment
```sh
PS C:\> cd myproj
PS C:\myproj> poetry install
```
### Register project and commit to git:
```sh
PS C:\myproj> git init
PS C:\myproj> git add .
PS C:\myproj> git commit -m "Initial template version"
```
### Do some updates in the project, e.g. add a `main.py`, and commit
```sh
PS C:\myproj> type main.py
print("Hello World")
PS C:\myproj> git add main.py
PS C:\myproj> git commit -m "Added main.py"
```
### Do an update to the template, e.g. add a `.gitignore`, and commit
```sh
PS C:\myproj> cd ..\copier-template
PS C:\copier-template> type .gitignore
# Emacs backup files
*~
\#*\#
PS C:\copier-template> git add .gitignore
PS C:\copier-template> git commit -m "Added gitignore file"
```
### Update the project from the template
```sh
PS C:\copier-template> cd ..
PS C:\> copier update myproj
No git tags found in template; using HEAD as ref

package_name? Format: yaml
🎤 [my-package]:

package_description? Format: yaml
🎤 [A short description of the package.]:

author_name? Format: yaml
🎤 [Cecron]:

author_email? Format: yaml
🎤 [Cecron@example.com]:

copyright_license? Format: yaml
🎤 [CC-BY-4.0]:
Either 1b4d418 or None is not a PEP 440 valid version.

    create  .gitignore
 identical  copier.yaml
 identical  pyproject.toml
  conflict  .copier-answers.yml
 Overwrite C:\myproj\.copier-answers.yml? [Y/n]
     force  .copier-answers.yml
```

</details>

**Comment by Yajo** [comment]
Hi and welcome to copier!



> I did not expect to have to force update .copier-answers.yaml after running `copier update`, so I'm probably doing something wrong...

Relax, it's OK.

This is a small pain point that I still didn't have time to fix. Indeed, you have to accept updates to that file on updates, which is a bit stupid because without that, the project wouldn't be "updated" at Copier's eyes. It should be a forced "yes" always.

Until it's fixed, just say yes always 🤷🏼‍♂️ 



> (I now also noted that stray comment about `Either 1b4d418 or None is not a PEP 440 valid version.`...)
> 
> The changes in .copier-answers.yml doesn't strike me as odd, (except perhaps the ^M ;-)

Well, these changes reveal you're not using git tags to version your template.

If you don't Copier might get tricked about which commit is newer, so it's better if you start versioning it 😉

**Comment by Cecron** [comment]
> Hi and welcome to copier!
> 
> > I did not expect to have to force update .copier-answers.yaml after running `copier update`, so I'm probably doing something wrong...
> 
> Relax, it's OK.

Thanks!

> > (I now also noted that stray comment about `Either 1b4d418 or None is not a PEP 440 valid version.`...)
> > The changes in .copier-answers.yml doesn't strike me as odd, (except perhaps the ^M ;-)
> 
> Well, these changes reveal you're not using git tags to version your template.
> 
> If you don't Copier might get tricked about which commit is newer, so it's better if you start versioning it 😉

I'll look into adding tags in my work flow right away!

(Also, thanks for editing my post adding the "Details" tag. I was actually looking for something like that when writing my post, and now I learned how to do it!)
