### ISSUE TITLE
Do not require --options before args on CLI

### ISSUE THREAD

**Issue by mszaf** [copier-org/copier#328]
Hello, new to this tool and really enjoying it so far.

I ran into some issues with following the docs and trying to accomplish the following:

![image](https://user-images.githubusercontent.com/20651891/105508334-435fc180-5c9a-11eb-958d-edb3783ab7f5.png)

Attempting to run `copier update --vcs-ref=HEAD` fails with `Error: Unknown switch --vcs-ref`

The main thing I'm trying to accomplish to update from a branch but with no success. Has this been done before?

I drilled into the source and found a work around but cannot do it from the command line:

```python
import copier
copier.copy(only_diff=True,vcs_ref='MY-BRANCH-HERE',quiet=True,force=True)
```

Thanks!

**Comment by Yajo** [comment]
Yes, you should have done `copier --vcs-ref=HEAD update` instead.

I know it's a little bit frustrating the need of options order... but well, our CLI toolkit requires that for now 🤷🏼‍♂️

**Comment by mszaf** [comment]
Awesome! argument order didn't even come to mind when I was trying to get this to work.

For reference I ended up using `copier --vcs-ref=branch-name --quiet --force update`

The only issue I have is that it seemed to make the comparison repo inside of the project directory.

So say file `a.txt` and `b.txt` changed since last commit, and my repo name is `copier-project`:
inside of my `copier-project` directory, after the update command, a new `copier-project` directory is created with the `a.txt` and `b.txt`

This is a non issue since I can use a post script to move them up one level but is this intended?

Thanks

**Comment by Yajo** [comment]
That's not supposed to happen, you're probably doing something wrong.

However that's a different subject, please open a separate discussion about it, and try to give good STR. Thanks!

**Comment by mszaf** [comment]
Yep! thanks for addressing the original issue. Will open new one soon detailing the second issue
