### ISSUE TITLE
Cosmetic remark about the questions

### ISSUE THREAD

**Issue by ppo** [copier-org/copier#336]
Let's put ourselves in the shoes of a user who is creating a project based on a template s/he doesn't know, and knowing nothing about Copier.

Currently, it looks like this…

![](https://i.imgur.com/nnMjJJz.png)

Does s/he really care about the variable name?  
Shouldn't there be a clear question in bold white on the first line?  
And below optionally an help text (in italic blue).  
Shouldn't the default value be highlighted in color?

**Comment by Yajo** [comment]
This is being improved for v6. Still not there, but much better indeed. Please test the latest alpha and reopen if needed 😊
