### ISSUE TITLE
`templates_suffix`: "extension prefix" rather than suffix

### ISSUE THREAD

**Issue by ppo** [copier-org/copier#337]
Changing the file extension has real disadvantages on editors as they are not recognized anymore.

There are extensions taking care of syntax highlighting.  
But there are still problems with the editor configuration.

I've an EditorConfig so I could modify that.  
But it's annoying and not pretty.

So, wouldn't it be better to use an "extension prefix"? (`.tmpl.py` instead of `.py.tmpl`)  
Or as I saw in another issue, just processing all files.
Or the more flexible, allow to define patterns to include (e.g. `["*.py", "*.html", ".env"]` or regex `(^\.env$)|(\.(py|html)$)`).

**Comment by Yajo** [comment]
In my experience, using a different default `.jinja` is the best, because it integrates properly with IDE syntax highlighters, such as https://github.com/samuelcolvin/jinjahtml-vscode/blob/b8fe444cbd838afb4962bb2446e67c85e0443675/package.json#L27-L177.



>  Or as I saw in another issue, just processing all files.

I think I never tested this, but if you use `_templates_suffix: ""`, does Copier process all files? 🤔

**Comment by ppo** [comment]
Apparently it doesn't work as expected… #186

**Comment by ppo** [comment]
> In my experience, using a different default `.jinja` is the best, because it integrates properly with IDE syntax highlighters, […]

As I tried to explain, yes… but no. I'm using `.jinja` and I've that extension installed but it's not working the same for `.py` and `.py.jinja`. The colors are not the same and my `.editorconfig` is not applied (because I don't want to include all the `.jinja` variants).

As usual, I'm looking to have things work as transparently as possible.  
Being able to configure something like `_templates_extension_prefix: ".jinja"` would make it absolutely transparent for everything you may have configured for the real extensions.

**Comment by pawamoy** [comment]
@ppo wouldn't `.jinja.py` be recognized as Python only (not Python+Jinja)? And therefore syntax highlighting could break easily?

**Comment by ppo** [comment]
@pawamoy Not if the editor extensions also support that… I guess I could bother them too with that 😉

**Comment by mazdakb** [comment]
I am creating a Django boilerplate project, similar to [Cookiecutter Django](https://github.com/pydanny/cookiecutter-django) but with `copier`. Changing the extension (to `.tmpl` or anything else) can also break [dependabot](https://dependabot.com/) which looks for specific files in a designated directory. Therefore I cannot keep the dependencies of the required libraries in template up to date as it's possible with cookiecutter. I can imaging any arbitrary tool which works like dependabot might break.

**Comment by Yajo** [comment]
dependabot works even if your requirements file contains jinja markers?

**Comment by mazdakb** [comment]
@Yajo Yes, it does.

**Comment by ppo** [comment]
> I am creating a Django boilerplate project, similar to [Cookiecutter Django](https://github.com/pydanny/cookiecutter-django) but with `copier`.

@mazdakb, I'm working on a similar project [Django Jazz](https://github.com/djazz/), if you want to collaborate…

_(sorry for the promotion but it's also so that you know why I posted so many issues, or more about their context 😉 )_
