### ISSUE TITLE
`--no-input` flag

### ISSUE THREAD

**Issue by ppo** [copier-org/copier#338]
Shouldn't there be a `--no-input` flag to tell Copier to not ask questions and use default values?  
Available during creation and update.

The `--force` should be just as it says: “Overwrite files that already exist, without asking”… so nothing to do with questions/answers.

**Comment by ypid** [comment]
What I would find most helpful is:

* Don’t ask questions that are already answered in `.copier-answers.yml` but answer new once instead of writing `null` into the answers file.
* Run `--force` update.

`--force` just writes `null` for new questions.

**Comment by Yajo** [comment]
> `--force` just writes `null` for new questions.

AFAIK it gets the default value of those questions, which might be null if you didn't specify it.

**Comment by dennisroche** [comment]
@Yajo I would like to pick this issue up as I found it confusing when trying to use `copier` for the first time

Proposed solution

- leave `--force` as-is to avoid a breaking change
- add `--defaults` flag to accept the default value of the questions
- add `--overwrite` flag to force overwrite files

Sound good?

**Comment by Yajo** [comment]
Seems good, thanks for volunteering. 😊
