### ISSUE TITLE
Resolve conflict: overwrite, skip, keep both or diff

### ISSUE THREAD

**Issue by ppo** [copier-org/copier#340]
**Use case:** I've a template file (`.env`) containing auto-generated passwords (using `make_secret()`), and it is ignored in Git (obviously).

When I update the project, it is of course every time different because of the auto-generated passwords… but it can also be different because of changes in the rest of the content. And the current file must keep the current passwords.

So, it would be great to have more choices (than "overwrite? y/n") to resolve the conflict.

I'm thinking about creating a new file containing either a diff or the new version (to be safe and not modifying the current file). That file would have the same name with a suffix ".diff" or ".new".

**Comment by Yajo** [comment]
There are a few tools in your belt that you can use:

1. Add `.env` to [`skip_if_exists`](https://copier.readthedocs.io/en/stable/configuring/#skip_if_exists)
2. Generate 2 identical files (`.env.new` can just contain `[% include ".env" -%]` and jinja will replicate it).
3. Use a pre-commit hook that forbids the inclusion of that file in your git history, [just like you'd do with `.rej` files](https://copier.readthedocs.io/en/stable/updating/).
4. Use [tasks](https://copier.readthedocs.io/en/stable/configuring/#tasks) to program a more specific workflow.

I think that a smart combination of some of those should be enough for your use case.
