### ISSUE TITLE
@Yajo: It's so rude to immediately lock an issue 😕

### ISSUE THREAD

**Issue by ppo** [copier-org/copier#342]
Cf. #340 😉😁

Why make it easy when you can do it manually in just 4 steps with an extra useless file and a custom task workflow, right?

Maybe a `_protected_files` could be useful to never overwrite them but create à `.new` file.  
I guess that all templates using `make_secret()` would need that.

So sorry to insist but I think it makes sense to have that built in Copier.

**Comment by pawamoy** [comment]
@ppo maybe you're not using the GitHub web interface? The issue was moved into the Discussions 🙂 Maybe locking is automatic when moving as a discussion, not sure.

**Comment by ppo** [comment]
Oh thanks. I'll check that.  
I'm using the mobile app.

**Comment by ppo** [comment]
Follow up in the discussion https://github.com/copier-org/copier/discussions/341

**Comment by Yajo** [comment]
Yes, sorry, that didn't happen before, it was just redirected. But discussions is beta and it seems that's how it looks now. I was not trying to be rude 😅
