### ISSUE TITLE
Does --subdirectory really work?

### ISSUE THREAD

**Issue by ppo** [copier-org/copier#354]
When executing the following command, the files are simply copied. And the folder `[[VAR]]` is not copied at all.

```
copier --subdirectory template-x git@github.com:namespace/project.git path/to/destination
```

The folder `/template-x/` is the root of a template (therefore with `/template-x/copier.yml`).

Version: 5.1.0

**Comment by Yajo** [comment]
Nope, it doesn't work fine.

It only works when used in the template itself, but when used in the CLI it doesn't make any sense.

See #315 for the whole story. For copier v6 that flag will disappear.
