### ISSUE TITLE
.rej files around when a conflicting file should be ignored

### ISSUE THREAD

**Issue by Yajo** [copier-org/copier#369]
Version affected: v6.0.0a6

STR:

1. A template includes a file in `skip_if_exists`
2. Copy it.
3. Change that file.
4. Update.

The conflict gets skipped, but a `.rej` file is created. It shouldn't.

**Comment by pawamoy** [comment]
Do you see an elegant way to fix this? I guess we could simply iterate on skipped files after the updating, removing any `.rej` file with the same name?

**Comment by Yajo** [comment]
I wouldn't call that elegant but it would work 😂

I didn't have time yet to figure out the cause of this problem.
