### ISSUE TITLE
Do something with the changelog

### ISSUE THREAD

**Issue by Yajo** [copier-org/copier#374]
Maintaining the changelog is boring. That's why it's so outdated. Gotta do something about it.

- Remove it and just use releases?
- Use some bot?

**Comment by pawamoy** [comment]
My 2 cents: I follow the Angular style for commit messages, which makes it easier to automatically generate the changelog for each release. I use my own project, git-changelog, to do that, though it's not perfect yet. There are many other tools that do just that, and maybe better, in javascript and python.

For more info on my own workflow: https://pawamoy.github.io/copier-poetry/work/#changelog

**Comment by Yajo** [comment]
But... do you think that would be helpful for a project that hasn't followed those conventions for years? 🙄

**Comment by Yajo** [comment]
Something I'm thinking about is removing the changelog and, instead, using github releases for that purpose. After all, there's where recent changes have been logged, and https://github.com/marketplace/actions/release-drafter might help.

**Comment by pawamoy** [comment]
> But... do you think that would be helpful for a project that hasn't followed those conventions for years? roll_eyes

Of course. You can generate only the most recent parts of the changelog, and leave the rest as it is. You can even generate entries for commits *not* using the Angular style (based on simple regexes: starts with "Add"? feature. Starts with "Fix"? bugfix, etc.)

If you prefer using GitHub releases, sure, why not! I myself try to avoid as much as possible vendor lock-in: changelog before provider-dependent releases notes, full links before provider-dependent shortcuts like `#153`, locally working test suites before provider-dependent CI, etc.
But I totally understand the convenience of such provider-dependent features! I'm not sure however that tools like pyup.io are able to fetch releases notes from GitHub releases instead of the changelog.

**Comment by Yajo** [comment]
> I myself try to avoid as much as possible vendor lock-in

That seems a valid point indeed.



> You can generate only the most recent parts of the changelog, and leave the rest as it is.

I didn't find the way to do it... When I do `git-changelog -o CHANGELOG.md .` it overrides the file completely. Is there any command to start at some version? Or are you talking about manual interaction?

**Comment by pawamoy** [comment]
Well I wasn't specifically talking about git-changelog, and indeed, it's not possible natively, but with some tweaks it is ([the tweaks I mentioned previously, requiring a Python script](https://github.com/pawamoy/duty/blob/master/duties.py#L24-L142)). To be honest, I can't seriously recommend git-changelog right now (and it's motivating me to work on it right now :smile:). I guess I just wanted to show you what was possible with changelog generators :slightly_smiling_face: 

Other candidates:

- https://github.com/vaab/gitchangelog
- https://github.com/KeNaCo/auto-changelog

**Comment by Yajo** [comment]
> https://github.com/KeNaCo/auto-changelog

This one looks promising, although https://github.com/KeNaCo/auto-changelog/issues/58 and https://github.com/KeNaCo/auto-changelog/issues/99 are blocking due to historical reasons.

I've been investigating all around, and found:

- https://keepachangelog.com/ is helpful.
- https://www.conventionalcommits.org/ also.

However, we have specific needs:

1. This project never had a commit message convention before. Thus, starting today wouldn't help unless the tool respects old manually-crafted changelog.
2. This project uses PEP440. That's on purpose. Semver has a lot of hype, but actually lacks a few features, and besides PEP440 is used for templates, so it doesn't make sense to use a different one for the parent project. But it used semver in the past. If point 1 is respected, this detail shouldn't matter.
3. We're python, so any python thing will get higher rating. https://github.com/goreleaser/chglog and https://www.npmjs.com/package/auto-changelog seem to be the only ones caring about point 1, but introduce some difficulties for installation in a python dev env.

Unless I find a tool that helps with both things, I think I'll just update it manually for the time being.

**Comment by pawamoy** [comment]
That's probably the best thing to do for now yes. I'll take your last comment as feedback to improve my own git-changelog :slightly_smiling_face:

**Comment by Yajo** [comment]
Nice, when it's ready feel free to ping around here, maybe we'll be able to do the switch.
