### ISSUE TITLE
Optionally copy a template without updating all git submodules

### ISSUE THREAD

**Issue by natopot8o** [copier-org/copier#386]
When a user has a template with a large number of git submodules, they may not want to immediately init all of them.

A potential use case (true in my case) is that there are submodules that are made  only in certain cases. The submodule contains a large number of other submodules only some of which are needed in particular cases. Checking all of them out when copying takes a large amount of time and is not necessary.

As a user I would like to be able to copy a template without recursively initializing them all, as this takes a large amount of time, I would prefer to be able to set copier to be able to copy without init and then initialize my submodules later.

Without this capability in some form or another it becomes relatively impossible to develop templates for projects with large amounts of submodules

## Suggestion
```
copier -m <url> <path>
copier --no-submodule <url> <path>
```

**Comment by Yajo** [comment]
The submodules you speak about are in the template or in the generated project?

If they were in the template, I think those should be necessary, and probably a good fix would be to maintain a local cache of templates.

**Comment by natopot8o** [comment]
Hey @Yajo thanks for getting back to me. The submodules are in the template - but the template is to be used for multiple use cases and for those specific use cases the submodules that are used are different. This is because of a required submodule (as in the problem is the --recursive because it pulls all of those submodules.

It would be good to be able to have options for the submodule update or to have the recursive update.

Would maintaining a local cache make copier update faster?

**Comment by natopot8o** [comment]
Sorry if this is a dumb question - asking because I'm curious. 

Is it not inefficient to pull all the submodule files down and include them in the diff for copier. wouldn't it make sense to have it  just as the submodule commit path? And then you would be able to see that the commit for a submodule had updated and then decide if you wanted to checkout that commit.

 I imagine that you might introduce breaking changes when you update a copier with submodules in the template if you aren't paying 100 % attention to them. And then if you do want to support updating you are forced to update your code to be compatible with 100 percent of the update (or selectively not include incompatible submodules - which you would have to track) even if only a small percentage don't work. Where as some people may want to deal with updating their compatibility with dependencies/submodules as a separate ongoing task and not have to worry about it every time they do an update. 

Although there would be cases where the template relies on the submodule update which would force you to update your submodule code. 

I think I'm understanding correctly, please let me know if I've missed something obvious.

**Comment by natopot8o** [comment]
> The submodules you speak about are in the template or in the generated project?
> 
> If they were in the template, I think those should be necessary, and probably a good fix would be to maintain a local cache of templates.

Sorry @Yajo I'm not 100 % sure I know what you  mean - I have pulled the template locally and copied from that, but it doesn't seem to speed anything up.

**Comment by natopot8o** [comment]
After playing with it more, I'm noticing that copier seems to be adding all the files in the submodules as new files - do I need to do some configuration or something to get these to be treated as submodules. I need to be able to commit my project and I cannot commit every file in the submodule as they are enormous, I'm getting the feeling that I'm not using this correctly.

**Comment by Yajo** [comment]
About caching, there's nothing you can do ATM. I was just talking about an hypothetical new feature for copier. Right now it's not supported.


About the issue you're talking about, I also think you must be using Copier wrong somehow. The purpose of including sumamodules in a template is to be able to share code between templates. If what you want is to include some submodule in your repo, it's better if you generate the `.gitmodules` file with Copier and, then, after generating, you manually call your git commands at will. Or you use `tasks` to automate it.

I hope it helps. I'll close this now assuming there's something wrong in the way you're using Copier. If you still need more help, please provide specific steps to reproduce and reopen.
