### ISSUE TITLE
feat: Conditional rendering of child files of conditionally rendered directory

### ISSUE THREAD

**Issue by natopot8o** [copier-org/copier#395]
Hey there, firstly thanks for this wonderful platform I think it's incredibly useful and I believe that I will use it liberally.

**Is your feature request related to a problem? Please describe.**

The issue that I would like to raise, is the conditional rendering of directories. 
At the moment, if the engine decides not to render a particular directory then the files in that directory are still
rendered just in the parent directory. I understand that you could conditionally render the children files if you put the conditional in each of their file names. 

**Describe the solution you'd like**

When a directory is not rendered by copier then I would like all of it's children to also not be rendered.

**Describe alternatives you've considered**

- Templating each of the child file names. (I think this is not a great user experience)
- Conditionally adding the directory as a submodule and deciding whether to use it in a task script. (This is quite complex)

**Comment by Yajo** [comment]
This is already fixed in master and will land in v6. I'm not sure if that particular feature is in the last alpha, but you could test if you want.

Advice: expect some bugs 😆
