### ISSUE TITLE
feat: provide a noninteractive way to check clone state

### ISSUE THREAD

**Issue by fdaguin** [copier-org/copier#401]
**Is your feature request related to a problem? Please describe.**

There is no noninteractive way to check if template clones are up-to-date with the latest changes in the template. Likewise, there is no way to figure out if a configuration drift had occurred.

**Describe the solution you'd like**

I'd like Copier to provide mechanism(s) to test those 2 states.

**Describe alternatives you've considered**

Using [Cruft](https://github.com/cruft/cruft) which supports this functionality in 2 ways, with:

- a `check` command: only check if the project is up to date
- a `diff` command with an `--exit-code`: check if the project has drifted

**Additional context**

I'd like to schedule a clone state check with a CI service.

**Comment by Yajo** [comment]
A workaround for your use case could be this?: 

    copier -f
    git diff

**Comment by fdaguin** [comment]
Thanks for your tip! However after some tests, it is unfortunately not working well.

In my testings, Copier only detects changes that were injected inside Jinja placeholders. It does not find any changes that occurred inside the rest of the files that were copied.

In other words, Copier doesn't know if the project has drifted.

**Comment by Yajo** [comment]
That's a bit weird because that's exactly one of Copier's main features. Could you be more specific and provide steps to reproduce?

**Comment by fdaguin** [comment]
**Template**
[https://github.com/copier-org/autopretty](https://github.com/copier-org/autopretty)

**Steps To Reproduce**
On my both of my environments:

1. `git init`
2. `copier copy https://github.com/copier-org/autopretty.git .`
3. `git commit -am "feat: init"`
4. Do random changes inside `.prettierrc.yml`:

```diff
-printWidth: 88
+printWidth: 80
proseWrap: always
xmlWhitespaceSensitivity: "ignore"
```

5. `git commit -am "chore: set prettier print width"`
6. `copier -a .copier-answers.autopretty.yml -f update`

I get the following output:

```text
 identical  .
 identical  .editorconfig
 identical  .gitignore
 identical  .flake8
 identical  .pre-commit-config.yaml
 identical  .github
 identical  .github/workflows
 identical  .github/workflows/pre-commit.yml
  conflict  .prettierrc.yml
     force  .prettierrc.yml
 identical  .copier-answers.autopretty.yml
```

However, nothing changes in both repositories.

**Environment 1**
 - OS: Ubuntu 20.04 in WSL
 - Copier version: 6.0.0a6.post25+2547899
 - Python version: 3.9.5
 - Installation method: pipx+git

**Environment 2**
 - OS: Windows 10 2004
 - Copier version: 6.0.0a6.post25+2547899
 - Python version: 3.9.0
 - Installation method: pipx+git

**Comment by Yajo** [comment]
That seems like an expected behavior to me. What were you expecting?

**Comment by fdaguin** [comment]
I actually expected `.prettierrc.yml` to changes back to what's defined in the up to date template, in a similar fashion to what [Cruft](https://github.com/cruft/cruft) does:

```diff
-printWidth: 80
+printWidth: 88
proseWrap: always
xmlWhitespaceSensitivity: "ignore"
```

This would allow me to have a proper `git diff` result, like you described in your workaround.

Sorry if I'm not understanding well how does Copier work.. I'm still trying to figure out [how the update works](https://github.com/copier-org/copier/blob/054b962d7093dbe0b24359e8ec9aded39d17f99d/docs/updating.md#how-the-update-works).

Thanks a lot for your time and dedication!

**Comment by Yajo** [comment]
If that's how Cruft works, then it makes me happy because I see Copier makes a big improvement.

In Copier, updating compares the original template with the latest version and extracts the diff, then applies it into your project. This is more powerful because it lets you modify any files and still get updates if your modifications don't conflict with how the template has evolved.

Only when both the template and the generated project have evolved differently the same code, Copier will leave `*.rej` files around with them.

What you want is something I call a "recopy", which ignores such evolution and just reapplies the latest template on top of your current project, just reusing the answers. Recopies are not supported on Copier 5, but for v6 they're already in master, so nothing to do here.

**Comment by fdaguin** [comment]
Fair enough, thanks for the clarification and for your time!
