### ISSUE TITLE
bug: choice 9.6 is truncated to 9

### ISSUE THREAD

**Issue by Yajo** [copier-org/copier#405]
**Describe the problem**

When updating interactively (with `-f` doesn't happen), `postgres_version` becomes `9` instead of `9.6`.

**Template**

https://github.com/Tecnativa/doodba-copier-template/blob/33b14028c6c9f9674cdfaffe3813aa6c18478308/copier.yml#L331-L341

**To Reproduce**

1. Copy interactively that template
2. Select `9.6` for `postgres_version`
4. It becomes `9` finally.

**Expected behavior**

Stay as 9.6.

**Screenshots/screencasts**

**Environment**
 - OS: Linux 
 - Copier version: 60f916017b43c66e1629823cd87afce9497c32d9   
 - Python version: Python 3.9.2
 - Installation method: pipx 

**Additional context**

**Comment by pawamoy** [comment]
I guess it's because no type is explicitly specified, so Copier takes the type of the default, which is an int, and then converts 9.6 using that type.

Possible solution: don't do type conversion if type is not explicitly specified.

**Comment by Yajo** [comment]
It seems there's another regression when I choose `I will use an external PostgreSQL server`, which doesn't return null as per https://github.com/tmbo/questionary/issues/126.

**Comment by Yajo** [comment]
After more thinking, supporting this use case is unnecessary trouble. It's better to just support all choices being the same type.
