### ISSUE TITLE
Passing boolean values as CLI arguments

### ISSUE THREAD

**Issue by parekh0711** [copier-org/copier#418]
How can I pass a boolean value as a command line argument to copier?
I'm doing it as given below:
`-d 'notification=False'`

However, in the template, the following line does not detect notification as being False, but works when I compare it to the string False.
`[% if notification -%]`

Not sure if this is a bug or I'm missing something.

**Comment by Yajo** [comment]
I think you forgot to set `type: bool` to the `notification` question. Please reopen otherwise and provide your `copier.yaml`. Thanks!

**Comment by parekh0711** [comment]
Do types of command line arguments need to be explicitly set in copier.yml? My copier.yml file does not include the variable notification as I always pass it through CLI.
It would be great if this could be mentioned in the documentation where --data is explained.

**Comment by Yajo** [comment]
The value you pass through `--data` from CLI should always be casted to the type specified in the question in `copier.yaml`.



> My copier.yml file does not include the variable notification as I always pass it through CLI.

In that case I'm not sure what happens. Probably there's no conversion. However, you can type-cast it directly in Jinja.

I'm curious, why do you pass the variable without declaring it in your `copier.yml` file?

**Comment by parekh0711** [comment]
Okay, got it.

> I'm curious, why do you pass the variable without declaring it in your `copier.yml` file?

I am running copier in the backend and my frontend prompts the user for variables. However, my backend now uses the copier library and not the CLI tool, so this issue is solved.

What's interesting is:
I went through your code, and even when not specified in copier.yml, the boolean values are loaded as booleans by your loader, so I still don't understand why it did not work in the first place.

**Comment by Yajo** [comment]
Well, as long as the problem's fixed, I wouldn't worry much about that 😄
