### ISSUE TITLE
bug: Quitting multiline on MacOS PyCharm not possible

### ISSUE THREAD

**Issue by Honest-Objections** [copier-org/copier#423]
**Describe the problem**

Just tried out the new `multiline: true` in `master`. Love the UI, however `(Finish with 'Alt+Enter' or 'Esc, Enter')` is more difficult on MacOS: 

* The `esc` is in the touchbar and when in the PyCharm IDE, `esc` takes you out of terminal context 
* There is no `alt` key and using `ctrl`, `option` + `enter` as substitute doesn't exit, at least again in PyCharm IDE, it just newlines again

**Template**
```yaml
# copier.yml
project_dedscription:
  type: str
  multiline: true
```

**To Reproduce**

1. Use a MacOS device
2. Checkout `8bed0441a98e56611142393bd32468be68b9416a`
3. Open PyCharm and in the terminal, run `copier  ../template-dir test`

**Expected behavior**

`ctrl`, `option` + `Enter` allows you to move on to the next step, rather than a new line

**Environment**
 - OS: MacOS
 - Copier version: 8bed0441a98e56611142393bd32468be68b9416a
 - Python version: 3.8
 - Installation method: git checkout + poetry env

**Comment by Yajo** [comment]
Thanks for the report, but this issue should be posted [upstream in the questionary library](https://github.com/tmbo/questionary/blob/144aa6074f278ec48c35213f1ccd81c26368a569/questionary/constants.py#L16). We use it to produce our forms.
