### ISSUE TITLE
bug: _templates_suffix: "" gives UnicodeDecodeError on binary files ( .ico or .png for example )

### ISSUE THREAD

**Issue by karolzlot** [copier-org/copier#433]
**Describe the problem**

I want to use `_templates_suffix: ""`
The problem is if I use it, then even image files will be processed by copier. And it will give error:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 14: invalid start byte
```

**Environment**
 - OS: Ubuntu on WSL2 on Win10
 - Copier version: copier 6.0.0a6.post43.dev0+2fe3072
 - Python version: 3.9.6
 - Installation method: pipx+git

**Additional context**

```
    create  .
    create  .dependabot
    create  .dependabot/config.yml
    create  .en v copy
    create  .env
    create  .gitignore
    create  LICENSE
    create  README.md
    create  Banana
    create  Banana/.prettierignore
    create  Banana/backend
    create  Banana/backend/alembic.ini
    create  Banana/backend/app
    create  Banana/backend/app/alembic
    create  Banana/backend/app/alembic/env.py
    create  Banana/backend/app/alembic/README
    create  Banana/backend/app/alembic/script.py.mako
    create  Banana/backend/app/alembic/versions
    create  Banana/backend/app/alembic/versions/91979b40eb38_create_users_table.py
    create  Banana/backend/app/alembic/__init__.py
    create  Banana/backend/app/alembic.ini
    create  Banana/backend/app/api
    create  Banana/backend/app/api/api_v1
    create  Banana/backend/app/api/api_v1/routers
    create  Banana/backend/app/api/api_v1/routers/auth.py
    create  Banana/backend/app/api/api_v1/routers/tests
    create  Banana/backend/app/api/api_v1/routers/tests/test_auth.py
    create  Banana/backend/app/api/api_v1/routers/tests/test_users.py
    create  Banana/backend/app/api/api_v1/routers/tests/__init__.py
    create  Banana/backend/app/api/api_v1/routers/users.py
    create  Banana/backend/app/api/api_v1/routers/__init__.py
    create  Banana/backend/app/api/api_v1/__init__.py
    create  Banana/backend/app/api/dependencies
    create  Banana/backend/app/api/dependencies/__init__.py
    create  Banana/backend/app/api/__init__.py
    create  Banana/backend/app/core
    create  Banana/backend/app/core/auth.py
    create  Banana/backend/app/core/celery_app.py
    create  Banana/backend/app/core/config.py
    create  Banana/backend/app/core/security.py
    create  Banana/backend/app/core/__init__.py
    create  Banana/backend/app/db
    create  Banana/backend/app/db/crud.py
    create  Banana/backend/app/db/models.py
    create  Banana/backend/app/db/schemas.py
    create  Banana/backend/app/db/session.py
    create  Banana/backend/app/db/__init__.py
    create  Banana/backend/app/initial_data.py
    create  Banana/backend/app/main.py
    create  Banana/backend/app/tasks.py
    create  Banana/backend/app/tests
    create  Banana/backend/app/tests/test_main.py
    create  Banana/backend/app/tests/test_tasks.py
    create  Banana/backend/app/tests/__init__.py
    create  Banana/backend/app/__init__.py
    create  Banana/backend/conftest.py
    create  Banana/backend/Dockerfile
    create  Banana/backend/pyproject.toml
    create  Banana/backend/requirements.txt
    create  Banana/docker-compose.yml
    create  Banana/frontend
    create  Banana/frontend/.dockerignore
    create  Banana/frontend/.eslintrc.js
    create  Banana/frontend/.prettierrc.js
    create  Banana/frontend/Dockerfile
    create  Banana/frontend/package.json
    create  Banana/frontend/public
Traceback (most recent call last):
  File "/home/orange/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/home/orange/.local/pipx/venvs/copier/lib/python3.8/site-packages/plumbum/cli/application.py", line 614, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/orange/.local/pipx/venvs/copier/lib/python3.8/site-packages/plumbum/cli/application.py", line 609, in run
    retcode = inst.main(*tailargs)
  File "/home/orange/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/cli.py", line 70, in _wrapper
    return method(*args, **kwargs)
  File "/home/orange/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/cli.py", line 293, in main
    self.parent._worker(
  File "/home/orange/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/main.py", line 575, in run_copy
    self._render_folder(src_abspath)
  File "/home/orange/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/main.py", line 467, in _render_folder
    self._render_folder(file)
  File "/home/orange/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/main.py", line 467, in _render_folder
    self._render_folder(file)
  File "/home/orange/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/main.py", line 467, in _render_folder
    self._render_folder(file)
  File "/home/orange/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/main.py", line 469, in _render_folder
    self._render_file(file)
  File "/home/orange/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/main.py", line 429, in _render_file
    tpl = self.jinja_env.get_template(str(src_relpath))
  File "/home/orange/.local/pipx/venvs/copier/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/orange/.local/pipx/venvs/copier/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/orange/.local/pipx/venvs/copier/lib/python3.8/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/orange/.local/pipx/venvs/copier/lib/python3.8/site-packages/jinja2/loaders.py", line 184, in get_source
    contents = f.read().decode(self.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 14: invalid start byte
```

**Comment by pawamoy** [comment]
On that day we entered the dark territory of binary vs. text detection.

https://unix.stackexchange.com/questions/275516/is-there-a-convenient-way-to-classify-files-as-binary-or-text
https://stackoverflow.com/questions/567757/how-do-i-distinguish-between-binary-and-text-files

Maybe you should simply exclude those images using `_exclude` in your `copier.yml` file.

**Comment by karolzlot** [comment]
IIUC those files won't be copied to output directory when excluded.

I would like to have option to exclude only from parsing, not copying.

**Comment by pawamoy** [comment]
Ah, true, my bad! Let see how CookieCutter does that then!

**Comment by xsc27** [comment]
`binaryornot` looks like it may be unmaintained.

a solution w/o requiring dependencies could be:
```python
from pathlib import Path
from typing import Union

def is_binary(check_file: Union[str, Path]):
    with Path(check_file).open("rt") as f:
        try:
            f.readline()
        except UnicodeDecodeError:
            return True
    return False
```

**Comment by pawamoy** [comment]
That would probably be enough for Copier yes, thanks for the snippet @xsc27! But for edge-cases (there are always edge-cases), an option similar to `_copy_without_render` would be necessary.

**Comment by Yajo** [comment]
Can't we just catch the `UnicodeDecodeError` jinja raises and perform a copy in that case?

**Comment by pawamoy** [comment]
Well indeed @Yajo, it would be even more elegant and robust (in my opinion), nice suggestion.

**Comment by karolzlot** [comment]
@Yajo anyway having option `_copy_without_render` still will be helpful:
- it is faster to exclude files this way than to check each file and catch Exception
- maybe we don't want to process some files, for example project may use Jinja tags in itself so some may want to exclude `.html` or `.jinja` files from parsing

**Comment by xsc27** [comment]
normally `_templates_suffix` mean a single extentions correct? one can argue that setting the suffix to an empty string means, no extentions. if support for multiple suffixes is desired, should globbing/wildcards be supported instead? Then `_copy_without_render` is more applicable.

Catching a `UnicodeDecodeError` exception should throw/log a warning.

**Comment by karolzlot** [comment]
@xsc27 
I don't like `_templates_suffix` even if it would support multiple extensions, because it removes those extensions from filenames after parsing.

I don't want to have different extensions before and after parsing because it makes correct syntax highlighing more difficult.

So I like what you wrote:

> Then `_copy_without_render` might be more applicable.
> 
> Catching a `UnicodeDecodeError` exception should throw/log a warning.

**Comment by pawamoy** [comment]
@karolzlot 

> it is faster to exclude files this way than to check each file and catch Exception

You might have misunderstood @Yajo's suggestion (or I misunderstood it myself!): this would be implemented in Copier itself, the template writers/users would not have to catch any exceptions themselves. It would automatically copy images and other binary files without trying to render them (well, trying, failing, and falling back to a simple copy).

> I don't want to have different extensions before and after parsing because it makes correct syntax highlighing more difficult.

Could you expand on this? In my opinion, having a `README.md.jinja` in the template makes it very clear to the IDE that you want a Jinja+Markdown syntax highlighting, not just a Markdown one.

**Comment by karolzlot** [comment]
@pawamoy Yes, I was talking about implementation in Copier 😄. I meant "faster" as "generating project from template will be faster", because reading file takes non-zero amount of time. 

-----

> Could you expand on this? In my opinion, having a README.md.jinja in the template makes it very clear to the IDE that you want a Jinja+Markdown syntax highlighting, not just a Markdown one.

Vscode doesn't work this way. And even it if would, then I prefer to not use additional extension, because typically I start template with many files and I would need to add additional extension to all of them in which I want to have parsing. 

And if syntax highlighting will be the same, then I would make many mistakes like: I put jinja syntax, but I forget to add Copier template extension.

I prefer Cookiecutter way here: no need to add additional extension at all, all files are parsed by default.

**Comment by pawamoy** [comment]
The Better Jinja VSCode extension by Samuel Colvin does wonders 😉 

But I agree with you. I did that mistake several times (templating a file and forgetting to add the extension). And I like being able to simply tell Copier to try and render everything. I actually opened the ticket about empty extension suffix and sent the PR to make it possible 😄 The best of both world would be to have automatic detection of templating (and thus Jinja syntax highlighting) without an additional file extension.

About performance: using an extension suffix makes Copier even faster as only templated files pass through the Jinja engine 🙂  

Anyway. I'll stop here and see what @Yajo decides.

**Comment by karolzlot** [comment]
@pawamoy 
If syntax support with this extension is good and it is making development easier then I see also this way:

Copier should allow mix approaches:
- parse files with `.jinja` extension (for better syntax highlighting) with removing `.jinja` extension after parsing
- parse any other files (without excluded ones) and without changing extension after parsing

This hybrid approach would prevent mistake "Oh I forgot to change file extension" and also will allow to use better syntax highlighting.

----

I also see a place for a tool which would change names for example all `.py` files to `.py.jinja`. Such tool seems trivial to write.

**Comment by Yajo** [comment]
I think that the fix is quite simple:

- What's `_templates_suffix`?
  - `""`
    - Does it render?
       - Yes: render it
       - No: copy it
  - `".jinja"` (default for v6+) or anything else
    - Does it have the suffix?
      - No: copy it
      - Yes:
        - Does it render?
          - Yes: render it
          - No: raise error.

Having the suffix has its pros and cons, while not having it has other pros and cons. It's up to the template maintainer to decide, I think that's outside the scope of this issue. 🤷🏼‍♂️

**Comment by karolzlot** [comment]
@Yajo I added six lines at the beginning of your tree:


* File meets criteria in `_ignore_files`:
  * Yes: ignore it
  * No:    
    * File meets criteria in `_copy_without_render`:
      * Yes: copy it
      * No:
         * What's `_templates_suffix`?
           * `""` 
             * Does it render?
               * Yes: render it
               * No: copy it
           * `".jinja"` (default for v6+) or anything else    
             * Does it have the suffix?
               * No: copy it
               * Yes:
                 * Does it render?
                   * Yes: render it
                   * No: raise error.



------

This is example of `_copy_without_render` from cookiecutter:

  `_copy_without_render: [frontend2/src/**/*.html, frontend2/src/**/*.vue, frontend2/node_modules/*, backend/app/app/email-templates/**]`

It seems to me that it would be best if both `_ignore_files` and `_copy_without_render` would allow to have extension and / or folder matching capabilities (like `.gitignore` does)

---


I am not sure about naming of `_ignore_files` setting, maybe a better name exists.

**Comment by Yajo** [comment]
I don't want to support the copy without render setting because you can just use the templates suffix for that. There's no need to have 2 ways of doing things IMHO.

**Comment by karolzlot** [comment]
Some people prefer to use `_templates_suffix = ""`.

In this case let's imagine that some files contain jinja tags, but they shoudn't be rendered (they will be rendered by app later).
For example: [template repo with email templates](https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/email-templates/src/reset_password.mjml).


Cookiecutter allows to exclude such files. If copier would force to use different `_templates_suffix` for whole project because of this, then it would be less comfortable to use.

**Comment by pawamoy** [comment]
You can still use `raw` tags, wrapping the entire contents of a file into it to avoid rendering any of it.

```
{% raw %}
This will not be rendered. {{ variable }}
{% if condition %}...{% endif %}
{% endraw %}
```

**Comment by karolzlot** [comment]
@pawamoy 
I see, but if you have **a lot** of files in one folder which you want to exclude from parsing, then it seems like a lot more work than what cookiecutter allows to do.

**Comment by Yajo** [comment]
I prefer to keep it simple, consistent and straightforward.

If you really care about what files are templated and what files not, then use a suffix. It's more predictable and easier to understand, and you don't have the load of going to the copier.yaml file, reading the specific configuration, and even interpreting the ignore patterns to know why/if a certain file will be a template or not.
