### ISSUE TITLE
New alpha release please

### ISSUE THREAD

**Issue by xsc27** [copier-org/copier#438]
**Is your feature request related to a problem? Please describe.**
There have been significant changes since v6.0.0a6 on March 5th. This make `_min_copier_version: "6.0.0a6"` not meaningful.

**Describe the solution you'd like**
Please cut a new pre-release and publish to PyPI. (PyPI currently lists `6.0.0a0` as the latest pre-release)

**Describe alternatives you've considered**
I am installing currently install directly from GitHub, but I would rather not. Especially so I can pin dependencies with pip-tools.

I also tried using the archive. That did not work because of `poetry-dynamic-versioning` since it is not a git repo at that point.

**Comment by xsc27** [comment]
🤔 I probably should have opened this a bug, not a feature.

**Comment by Yajo** [comment]
There you go: https://github.com/copier-org/copier/releases/tag/v6.0.0a7
