### ISSUE TITLE
bug: dependabot is missing a link for copier

### ISSUE THREAD

**Issue by ntravis** [copier-org/copier#445]
**Describe the problem**

this is not an issue with copier itself, but with the Github dependency graph. an admin from copier-org will be able to correct this via Github's virtual assistant but I cannot submit a request for you. 

TL;DR to correct:

- Visit the github support page - [link](https://support.github.com/contact)
- select appropriate options until you are able to type in "dependency graph resolves to wrong repo"
- a button for a virtual assistant will show up
- going through that prompt should allow you to resolve the errant attribute in the dependency graph

I helped with a similar issue for Datadog's dd-trace-py [here](https://github.com/DataDog/dd-trace-py/issues/2494)

**Template**
n/a

**To Reproduce**

You would need a project that consumes copier as a dependency and has dependabot enabled. Here is what I see when using copier in my project:

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/8976020/133265105-0e5406f8-85e1-42c9-8b8b-e35ded72ad65.png">

**Logs**

n/a

**Expected behavior**

The grayed out "copier", after fixing, would read as copier-org/copier and be a link to this repo.

**Screenshots/screencasts/logs**

n/a

**Environment**

n/a

**Additional context**

n/a

**Comment by Yajo** [comment]
Fixed, thanks!
