### ISSUE TITLE
bug: characters with accents supplied through surveys lead to wrong updates

### ISSUE THREAD

**Issue by fdaguin** [copier-org/copier#448]
**Describe the problem**

[Non-alphabetical characters of the ASCII table](http://sticksandstones.kstrom.com/appen.html) supplied through a template survey are not properly supported when using `copier update`.

**Template**

Unfortunately, I'm not able to share a private template from my organization.

**To Reproduce**

1. Use a copier template and answer a question with a [non-alphabetical characters of the ASCII table](http://sticksandstones.kstrom.com/appen.html), for example `é`
2. Later on, update the project with `copier update`
3. See `é` being displayed as `Ã©` for the same question
![image](https://user-images.githubusercontent.com/72013963/134201818-bd039322-d45c-45a7-b6f7-c500226ec93c.png)
4. Change `Ã©` to `é` in the prompt and complete the survey
5. See `.rej` files being created, caused by a mismatch between `Ã©` and `é` :

```diff
@@ -3,3 +3,3 @@ name = "u-iris.robotframework-courses-u-webapp"
 version = "0.1.0"
-description = "Projet Courses U automatisÃ©"
+description = "Projet Courses U automatisé"
 packages = [
```

**Expected behavior**

Unicode characters are correctly handled.

**Environment**
 - OS: Windows 10
 - Copier version: 6.0.0a7.post1.dev0+b8ff4d8
 - Python version: 3.9.7
 - Installation method: pipx+git

**Comment by pawamoy** [comment]
What happens if you export `PYTHONIOENCODING=UTF8` in your shell first? And `PYTHONUTF8=1`?

**Comment by pawamoy** [comment]
Ah, I was able to replicate. First project generation is OK (accent written in copier answers file), but during the update the prompt shows `Ã©` just like @fdaguin said. I had `PYTHONIOENCODING=UTF-8` exported. I'll try with PYTHONUTF8 now.

**Comment by pawamoy** [comment]
`export PYTHONUTF8=1` fixed it 🎉 !

**Comment by fdaguin** [comment]
Thanks a lot for your investigation @pawamoy, I'm closing this issue!
