### ISSUE TITLE
docs: A few enhancement ideas

### ISSUE THREAD

**Issue by pawamoy** [copier-org/copier#521]
- [x] Document that double-quotes are not valid characters on Windows. If you template a file/dir name and need to use quotes, use single quotes.
- [x] Document that templated file names **must** end with the configured template suffix anyway:
    - `{% if thing %}this_file.jinja{% endif %}`: bad
    - `{% if thing %}this_file{% endif %}.jinja`: good
- [x] Document that, contrary to files, directories **don't have to** (or **must not**? need to verify) end with the configured template suffix:
    - `{% if thing %}this_dir{% endif %}`: works OK
- [ ] (related to the two previous points, maybe there are possible UX improvements to do?)
- [x] Document the available native Jinja2 extensions:
    - [expression statement](https://jinja.palletsprojects.com/en/3.0.x/extensions/#expression-statement) (too bad there's no link to [actual use](https://jinja.palletsprojects.com/en/3.0.x/templates/#expression-statement) in this paragraph). Can be used to alter the context (answers, filters, etc.). The file containing such modifiers has to be handled first, so file name should be aaaa or something. The file should also be removed by a post-processing task. Better than that: use my [copier-templates-extensions loader](https://github.com/pawamoy/copier-templates-extensions), which is easier to use 😛 
    - [loop controls](https://jinja.palletsprojects.com/en/3.0.x/extensions/#loop-controls)
    - [debug extension](https://jinja.palletsprojects.com/en/3.0.x/extensions/#debug-extension)
    - more generally, the [extensions](https://jinja.palletsprojects.com/en/3.0.x/extensions/) page 🙂

**Comment by Yajo** [comment]
Another idea: link to the site where you can get versioned docs

**Comment by pawamoy** [comment]
The "Creating a template" page also definitely lacks examples of template contents. I'll see if I can use the minimal example in the README to provide some more complete recipes.

**Comment by pawamoy** [comment]
I can add a dark/light theme switch button as well if you fancy it.

**Comment by Yajo** [comment]
Both seem good enhancements, thanks!
The dark mode can't be automatic when the browser is dark?

**Comment by pawamoy** [comment]
Yes it can! It will detect the user preference and use that by default.

**Comment by Yajo** [comment]
El jue, 6 de ene de 2022 a las 09:42:00 AM, Timothée Mazzucotelli 
***@***.***> escribió:
> Yes it can! It will detect the user preference and use that by 
> default.
> 

cool!

**Comment by Yajo** [comment]
A couple more ideas:

- Version dropdown/link. I like https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/ but maybe that's not applicable for us, as we use readthedocs. Maybe just a link in the header to https://readthedocs.org/projects/copier/ would be enough.
- Correct version number in the "latest" version, fixing the problem explained in https://github.com/mkdocstrings/pytkdocs/issues/122.

**Comment by pawamoy** [comment]
Asked here: https://github.com/squidfunk/mkdocs-material/discussions/3439
