### ISSUE TITLE
bug: Diagram not displaying correctly in dark mode in latest documentation

### ISSUE THREAD

**Issue by eyllanesc** [copier-org/copier#541]
**Describe the problem**
In the latest documentation (not in the stable one) it is observed that the arrows of the update diagram are not visible in the dark mode. See https://copier.readthedocs.io/en/latest/updating/#how-the-update-works.

**Expected behavior**

Arrows must be visible on all themes. 

**Screenshots/screencasts/logs**

dark mode:

![Screenshot_20220113_211119](https://user-images.githubusercontent.com/4896200/149439682-92d4558f-2451-4bef-b18c-5eeef99263c0.png)

light mode:

![Screenshot_20220113_211106](https://user-images.githubusercontent.com/4896200/149439696-31a38b5b-578d-4658-9cc6-985ae67442e9.png)

**Comment by pawamoy** [comment]
This was indeed brought up by @Yajo in #528. I saved the notification to see if I can find a way to make the lines visible with both themes.

**Comment by eyllanesc** [comment]
@pawamoy I think some css should be added that changes the color of the chart based on the theme change.

**Comment by pawamoy** [comment]
Native support for Mermaid.js is still in Insiders: https://squidfunk.github.io/mkdocs-material/reference/diagrams/
But yeah there might be a way with CSS :slightly_smiling_face:

**Comment by Yajo** [comment]
> Native support for Mermaid.js is still in Insiders: https://squidfunk.github.io/mkdocs-material/reference/diagrams/ But yeah there might be a way with CSS 🙂

That page works fine in dark mode. How do they do it?

**Comment by eyllanesc** [comment]
@Yajo [footnote](https://squidfunk.github.io/mkdocs-material/reference/diagrams/#using-entity-relationship-diagrams): While all Mermaid.js features should work out-of-the-box, Material for MkDocs will currently only adjust the fonts and colors for flowcharts, sequence diagrams, class diagams, state diagrams and entity relationship diagrams.

**Comment by pawamoy** [comment]
> That page works fine in dark mode. How do they do it?

Well I guess the mkdocs-material site is built with the insiders version of mkdocs-material, therefore supporting theme switch :slightly_smiling_face:

**Comment by pawamoy** [comment]
Found a way, there was actually an example in mkdocs-mermaid2-plugin docs :slightly_smiling_face: Pushing a PR
