### ISSUE TITLE
bug: `when` false still prompts for question.

### ISSUE THREAD

**Issue by TheUnknownFew** [copier-org/copier#564]
**Describe the problem**
The `when` field seems to have no effect on my questions. I am still promoted for the question even when `when` is explicitly set to false. Initially I thought it was an issue with Jinja rendering `[[enter]]` in my `when` field, but I then I set `when` to `false` to see if it would not prompt me the question, but even then I was prompted.

**Template**
[template.zip](https://github.com/copier-org/copier/files/8034088/template.zip)

**To Reproduce**
1. Run `copier template t1`
2. Answer: Simply accept all the defaults

**Logs**
```
copier template t1

Create folders
enter? Format: bool
? [Y/n] 

p
p? Format: str
 [ppp]: 

Enter a folder name
folder_name? Format: str
 [helloworld]:         

    create  .copier-answers.yml
    create  my_dir/

```

**Expected behavior**
I should not be prompted for this question.

**Environment**
 - OS: Ubuntu 20.04.3 LTS
 - Copier version: 5.1.0
 - Python version: 3.9
 - Installation method: pip

**Comment by TheUnknownFew** [comment]
I just realized that this might be a 6.x feature?
If that is the case, my bad. This issue can be closed.

**Comment by TheUnknownFew** [comment]
> Yes, sorry...

@Yajo I think logging would have been really important in this scenario. It wasn't abundantly clear that that yaml key was not supported.
Would it be possible to add WARNING messages when an unsupported YAML key is found for the currently installed Copier version? i.e. a `keywords` dictionary/set, and if a key for a question is not found in the dictionary/set, a warning is displayed that `key is has no effect` or something along those lines.

**Comment by Yajo** [comment]
That could be helpful, yes. However it would create unnecessary noise when one of those keys gets deprecated and removed in the future.

It seems like a separate issue though.

I have no plans to implement that, but I'd review the PR if somebody wants to volunteer.
