### ISSUE TITLE
bug: poetry self update 0.8.0 | RuntimeError

### ISSUE THREAD

**Issue by danielbellhv** [copier-org/copier#568]
Based on trying to solve a separate error, [Git Issue here](https://github.com/copier-org/copier/issues/563).

Terminal:
```
me@PF2DCSXD:/mnt/c/Users/me/Documents/GitHub/wpf/workers-python-framework/workers_manager$ poetry --version
Poetry version 1.1.12
me@PF2DCSXD:/mnt/c/Users/me/Documents/GitHub/wpf/workers-python-framework/workers_manager$ poetry self update 0.8.0
Updating to 0.8.0

  RuntimeError

  Could not find poetry-0.8.0-linux.sha256sum file

  at ~/.poetry/lib/poetry/console/commands/self/update.py:260 in _update
      256│         try:
      257│             r = urlopen(base_url + "/{}/{}".format(version, checksum))
      258│         except HTTPError as e:
      259│             if e.code == 404:
    → 260│                 raise RuntimeError("Could not find {} file".format(checksum))
      261│
      262│             raise
      263│
      264│         checksum = r.read().decode().strip()
```

**Comment by pawamoy** [comment]
This is *definitely not* related to Copier.

@Yajo if you feel like it, I'd gladly accept some elevation of privileges on this repo so I can manage issues like this one :slightly_smiling_face:

**Comment by danielbellhv** [comment]
Apologies, I meant to put this on Poetry... feel free to completely delete this

**Comment by pawamoy** [comment]
No problem, thank you for closing!

**Comment by Yajo** [comment]
> @Yajo if you feel like it, I'd gladly accept some elevation of privileges on this repo so I can manage issues like this one slightly_smiling_face

Of course! Thanks for volunteering 😊 

Welcome on board!
