### ISSUE TITLE
feat: Please avoid the use of suffix for template files

### ISSUE THREAD

**Issue by garu57** [copier-org/copier#577]
I'm experimenting with copier and i like it very much for it's flexibility, but IMHO there is a shortcoming in its design that impair its adoption. Unless i missed something, and i'd like to be proven wrong.
When programming normally anybody uses some sort of IDE, and all of them have specialized editors that usually triggers on file extensions. When you need to change some scaffolding template files, all of them ends with `.tmpl` or whatever suffix one can choose and this causes the IDE to treat them all as simple text files so missing any hints that a specialized editor can give.
And if editing a toml file as text is not a great hassle, editing typescript or python files as text is at best cumbersome.
The best solution i could find is to remove the `.tmpl` before editing the files, but it's a pain in the neck and I found that sometimes it happens that i commit files with the wrong extension because i forgot to put back the `.tmpl` extension. My fault obviously, but I cannot accept to use a tool that makes me commit errors.

Could you add the possibility to process template files with their native extension, like [cookiecutter](https://github.com/cookiecutter/cookiecutter) does?
Thanks

**Comment by pawamoy** [comment]
Hi! The latest version of Copier (v6 alpha) changes the default suffix to .jinja, which is well understood by most editors :)

**Comment by garu57** [comment]
Ok, using `.jinja` as extension, things works much better. I found a [vscode](https://code.visualstudio.com/) extension [Better Jinja](https://marketplace.visualstudio.com/items?itemName=samuelcolvin.jinjahtml) that is able to intercept many of the double file extensions (like `.py.jinja`, `.json.jinja` etc.) and trigger the right editor so things work right most of times.
Thanks, as i said i'd like to be proven wrong :)

I think this way i can work with copier templates in vscode and can use copier as a scaffolding tool.
So I think you can close this and forget.

**Comment by Yajo** [comment]
FTR, in Copier 5.1 you were able to configure a different suffix, so you can use `.jinja` there too.

Also, in Copier 6 you're able to set an empty suffix and then template all the things.

I'm glad you like it 😄
