### ISSUE TITLE
document how to use subdirectories to have various templates in a repo

### ISSUE THREAD

**Issue by Yajo** [copier-org/copier#578]
Coming in nearly a year later as I was confused about this feature (also coming from cookiecutter) -- did I understand right that I can't have a monorepo with multiple templates via `--subdirectory` option?

I couldn't find in the docs hence commenting in this closed issue:

```
repo/
    template1/
        copier.yml
        files_to_render/
    template2/
        copier.yml
        files_to_render/
    etc
```

_Originally posted by @heitorlessa in https://github.com/copier-org/copier/issues/315#issuecomment-1047540229_

**Comment by heitorlessa** [comment]
Thank you so much again for clarifying this @Yajo !
