### ISSUE TITLE
bug: error "is not a relative path" changing answers_file path

### ISSUE THREAD

**Issue by garu57** [copier-org/copier#579]
Working with Windows 10 updated to last patch an copier v6 installed from git repo master (need fix for #520).
I'm still testing copier behavior and i want to keep answers file separated from created project. I want to be able to delete project dir and recreate the test project without being asked again all the questions.
But trying to change answers file path i get this error:
```
pydantic.error_wrappers.ValidationError: 1 validation error for Worker
answers_file
  "C:\home\prjHome\templates\templates-build\gg-py-package-template-test\.copier-answers.yml" is not a relative path (type=value_error.path.not_relative; path=C:\home\prjHome\templates\templates-build\gg-py-package-template-test\.copier-answers.yml)
```
I couldn't find anywhere in the doc that answers file path must be relative to something. (By the way, relative to what?

**Comment by garu57** [comment]
Forgot to add how copier it is called.
For the above error copier is called by a win batch file:
```
:: testing prj build with copier
set CURDIR=%~dp0
call workon copier 
call copier -a %CURDIR%\.copier-answers.yml copy %CURDIR%\..\..\gg-py-package-template %CURDIR%\..\work\template-test
call deactivate
```
`.copier-answers.yml` is in the same dir as the batch file.

If I change the batch to use a relative file as follows:
```
:: testing prj build with copier
set CURDIR=%~dp0
pushd  %CURDIR%
call workon copier 
call copier -a .\.copier-answers.yml copy ..\..\gg-py-package-template ..\work\template-test
call deactivate
popd
```
the answers file is simply ignored and I'm prompted again for answers with the default values.

**Comment by garu57** [comment]
It works doing a weird thing like this
```
:: testing prj build with copier
call workon copier 
call copier -a ..\..\gg-py-package-template-test\.copier-answers.yml copy 
    C:\home\prjHome\templates\gg-py-package-template 
    C:\home\prjHome\templates\templates-build\work\template-test
call deactivate

```
but again, why i have to use an answers file path relative to the destination dir, while it is in the same directory as the script?
Could you explain please?
Thanks

**Comment by Yajo** [comment]
👋 welcome to copier! 

It has to be relative because its value is available at render time, and used to put that file. Also because it's used to update projects, and for that a project must be git-tracked, thus the file must be in the repo anyway. 

Closing, as this seems more a question than an issue.
