### ISSUE TITLE
feat: submit multiline with Opt+Enter on Mac

### ISSUE THREAD

**Issue by tpluscode** [copier-org/copier#582]
**Is your feature request related to a problem? Please describe.**

Multiline questions say `(Finish with 'Alt+Enter' or 'Esc then Enter')`

Apparently only the latter works on Macs because they do not have the `Alt` key

**Describe the solution you'd like**

I would not even change the help text, but simply make `Option+Enter` work since that key typically functions as `Alt`

**Comment by sid-maddy** [comment]
AFAICT this is controlled by the underlying prompt-toolkit library.

[Their README says](https://github.com/prompt-toolkit/ptpython/blob/master/README.rst#multiline-editing),
> To execute the input in multi-line mode, you can either press `Alt+Enter`, or `Esc` followed by `Enter`. (If you want the first to work in the OS X terminal, you have to check the "Use option as meta key" checkbox in your terminal settings. For iTerm2, you have to check "Left option acts as +Esc" in the options.)

**Comment by yajo** [comment]
That should be a fix, right?
