### ISSUE TITLE
Cannot update to HEAD - "Downgrades are not supported"

### ISSUE THREAD

**Issue by tpluscode** [copier-org/copier#603]
**Describe the problem**

I have a project generated from version 1.2.0 of a template.

I want to try out new changes from master branch by running `copier -r HEAD`

**Template**

https://github.com/hypermedia-app/creta-template-app/releases/tag/1.2.0

**To Reproduce**

1. Generate from latest tag
2. Update from newer commit

**Logs**

```
Your are downgrading from 1.2.0 to 1.2.0.dev3+g5f731f1. Downgrades are not supported.
```

**Expected behavior**

This should succeed since commit `g5f731f1` is newer than tag `1.2.0`

**Environment**
 - OS: macOS Catalina 10.15.7
 - Copier version: copier 6.0.0a9
 - Python version: 3.9.10
 - git version 2.24.3 (Apple Git-128)
 - Installation method: pipx

**Comment by Yajo** [comment]
Please can you confirm if https://github.com/copier-org/copier/pull/637 fixes the issue?
