### ISSUE TITLE
Improve conflict resolution

### ISSUE THREAD

**Issue by tpluscode** [copier-org/copier#613]
Would it be possible to change how copier handles conflicts?

Presently, conflicting changes are saved as `*.rej` files. Their contents may not be immediately obvious to interpret to decide what to do about them.

I suppose that what copier does is essentially a 3-way merge between the baseline generated from `vN` of a template, the newer version generated from `vN+1`, and the actual project files.

Would it be possible to instead modify the actual template files so that they include the `>>>>` markings for conflicting changes? Maybe this way it would be possible to handle conflicts with `git difftool` or IDE?

**Comment by pawamoy** [comment]
Relevant: https://github.com/copier-org/copier/pull/407

**Comment by Yajo** [comment]
It would be a nice improvement indeed.

**Comment by tguillemot** [comment]
I have some time during my weekend to work on this. You can find my proposal in #627.
