### ISSUE TITLE
Quick start in README.md contains instructions for alpha release

### ISSUE THREAD

**Issue by jmgilman** [copier-org/copier#615]
**Describe the problem**

It appears the quick start guide in the current `README.md` is out of date.

**Template**
- {{project_name}
  - {{module_name}}.py.jinja

**To Reproduce**
1. Follow the quick start section of `README.md`
2. Try to use the resulting template structure: `copier my_tmpl my_project`
3. See that no interpolation happens

**Logs**
N/A

**Expected behavior**
Expected the result shown in the quick start.

**Screenshots/screencasts/logs**
N/A

**Environment**
 - OS: macOS Monterey 12.1 (aarch64)
 - Copier version: 5.1.0
 - Python version: 3.10.2
 - Installation method: `pip install copier`

**Additional context**

It's possible this is simply a misunderstanding of how this tool works, however, running through the quick start section of the `README.md` at `HEAD` was producing something that didn't appear to work on my system. Specifically, the quick start has you use `{{project_name}}` and `{{module_name}}.py.jinja`, both of which did not get transformed by Jinja when I invoked `copier`. 

It was necessary for me to change it to `[[project_name]]` and `[[module_name]].py.tmpl` before everything worked correctly.

What made this more confusing was trying to understand the difference between the [latest](https://copier.readthedocs.io/en/latest/creating/) docs and the [stable](https://copier.readthedocs.io/en/stable/creating/) docs. It wasn't until I happened to run across the stable docs that I saw the reference to use `[[ ]]` over `{{ }}` and `.tmpl` over `.jinja`. If you click the `docs` badge at the top of the README, it takes you to the latest docs, which appears to suggest the same structure as the quick start (i.e. using `{{ }}`).

**Comment by pawamoy** [comment]
Yup, latest docs work for latest alpha version only. Maybe the badge should point to the stable docs instead.

**Comment by jmgilman** [comment]
I think it's just a bit confusing for a new user who follows the README and runs `pip install copier` and then is unable to get the quick start to work because it's targeting an alpha version (these were my exact steps). There's also no indication *why* it doesn't work other than interpolation appears to just be broken (i.e. no errors hinting about migrating from `[[ ]]` to `{{ }}`. 

I know sometimes these things can get overlooked by regular users of the package, so I thought it prudent to point it out :)

**Comment by pawamoy** [comment]
A note or warning about the state of current versions would certainly help new users :slightly_smiling_face:

**Comment by Yajo** [comment]
Another problem is that in old docs versions, the header icon always points to the latest version of docs. It's a bug that I hope is fixed because on PR builds it doesn't happen anymore. But old docs still have it. At least the color change helps on that.

I changed the link in the "about" section of the repo, pointing it to https://readthedocs.org/projects/copier/ now.

I think it would be nice to have a version indicator or even a link to the version selector from the docs.
