### ISSUE TITLE
Strange pathing behavior when specifying a destination without separators

### ISSUE THREAD

**Issue by macintacos** [copier-org/copier#699]
**Describe the problem**

While trying to stand up a Copier template recently, we ran into some behavior that I can't quite explain. To demonstrate it, I create the following public repo that you can use as a test (since the template I created is a private one and I can't share it): https://github.com/macintacos/copier-dest-test

The issue is when it comes to the `_tasks` definitions in the `copier.yml` file. As you can see currently (https://github.com/macintacos/copier-dest-test/blob/9f68d814317369c9a9e21d1ad8ea62a4a2f64dd4/copier.yml#L17), if you choose `Name2` when running the template generation, it should execute the script in the template's `scripts` directory.

For some reason, the following attempts at creating a repo work just fine:

```
$ copier https://github.com/macintacos/copier-dest-test.git ../blah -d project_name="Name2"
No git tags found in template; using HEAD as ref

Copying from template version 0.0.0.post8.dev0+9f68d81
    create  .
    create  scripts
    create  scripts/test.sh

 > Running task 1 of 1: ../blah/scripts/test.sh
Project name is: Name2!

$ copier https://github.com/macintacos/copier-dest-test.git . -d project_name="Name2"
No git tags found in template; using HEAD as ref

Copying from template version 0.0.0.post8.dev0+9f68d81
 identical  .
    create  scripts
    create  scripts/test.sh

 > Running task 1 of 1: ./scripts/test.sh
Project name is: Name2!

$ copier https://github.com/macintacos/copier-dest-test.git $PWD/blah -d project_name="Name2"
No git tags found in template; using HEAD as ref
🎤 Choose a project name
project_name? Format: str Name2

Copying from template version 0.0.0.post8.dev0+9f68d81
    create  .
    create  scripts
    create  scripts/test.sh

 > Running task 1 of 1: /Users/macinburrito/GitLocal/Play/something/blah/scripts/test.sh
Project name is: Name2!
```

And the following doesn't (note how I'm specifying just "blah" instead of any other way):

```bash
$ copier https://github.com/macintacos/copier-dest-test.git blah -d project_name="Name2"
No git tags found in template; using HEAD as ref

Copying from template version 0.0.0.post8.dev0+9f68d81
 identical  .
 identical  scripts
 identical  scripts/test.sh

 > Running task 1 of 1: blah/scripts/test.sh
/bin/sh: blah/scripts/test.sh: No such file or directory
Traceback (most recent call last):
  File "/Users/macinburrito/.local/bin/copier", line 8, in <module>
    sys.exit(CopierApp.run())
  File "/Users/macinburrito/.local/pipx/venvs/copier/lib/python3.10/site-packages/plumbum/cli/application.py", line 629, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/Users/macinburrito/.local/pipx/venvs/copier/lib/python3.10/site-packages/plumbum/cli/application.py", line 624, in run
    retcode = inst.main(*tailargs)
  File "/Users/macinburrito/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/cli.py", line 71, in _wrapper
    return method(*args, **kwargs)
  File "/Users/macinburrito/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/cli.py", line 298, in main
    ).run_copy()
  File "/Users/macinburrito/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 608, in run_copy
    self._execute_tasks(
  File "/Users/macinburrito/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 192, in _execute_tasks
    subprocess.run(task_cmd, shell=use_shell, check=True, env=local.env)
  File "/Users/macinburrito/.pyenv/versions/3.10.2/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'blah/scripts/test.sh' returned non-zero exit status 127.
```

I don't really understand why, because if I generate the project successfully and run `scripts/test.sh`, it works just fine:

```bash
$ scripts/test.sh
Project name is: Name2!
```

Does anyone have any idea what's going on here?

**Template**

https://github.com/macintacos/copier-dest-test

**Expected behavior**

As long as the "destination" provided to Copier is valid, it should be able to run the scripts as specified in the linked template repository.

**Screenshots/screencasts/logs**

**Environment**
 - OS: macOS 12.4 (but also repro'd on a colleague's machine running Ubuntu 22.04 LTS)
 - Copier version: 6.1.0
 - Python version: 3.10.5
 - Installation method: Pipx

**Comment by yajo** [comment]
It seems that the fact you're entering `blah` instead of `./blah` makes a difference.

Bash will search for any executable when given an explicit path, such as `./blah`. But when the string is not an explicit path (`blah` is a path, but it's implicit), then it will search for an executable with that name inside its `$PATH`.

This is normal, standard bash behavior.

You can just change this into your `_tasks`:

```diff
-- "{% if project_name == 'Name2' %}{{{ _copier_conf.dst_path }}}/scripts/test.sh{% else %}echo 'Not doing anything! Choose Name2!'{% endif %}"
+- "{% if project_name == 'Name2' %}$(realpath {{{ _copier_conf.dst_path }}}/scripts/test.sh){% else %}echo 'Not doing anything! Choose Name2!'{% endif %}"
```

**Comment by macintacos** [comment]
Thanks @yajo! I found it a bit strange that executing the same code from a bash shell would work, but executing it from copier it wouldn't. Appreciate the workaround!
