### ISSUE TITLE
feat: Support local bare repositories

### ISSUE THREAD

**Issue by pawamoy** [copier-org/copier#790]
**Is your feature request related to a problem? Please describe.**
We have a lot of absurd restrictions at work and I've came to have to pack a copier git repo in another git repo...
A regular clone would be very wasteful, and I thought of using a bare clone instead: `git clone --bare`.
Unfortunately `is_git_repo_root` and `is_in_git_repo` are not enough to be able to use bare repos.

**Describe the solution you'd like**

To detect a bare repository, we could have this:

```python
def is_git_bare_repo(path: StrOrPath) -> bool:
    """Indicate if a given path is a git bare repo directory."""
    try:
        with local.cwd(path):
            return git("rev-parse", "--is-inside-git-dir").strip() == "true"
    except OSError:
        return False
```

...and use it in `get_repo`.

**Describe alternatives you've considered**
A clear and promising alternative is using git bundles, which seems way cleaner compared to using local bare repositories, so I don't mind if this feature request is closed in favor of git bundles.
I'll update here if I get something working 🙂

**Comment by yajo** [comment]
I'm not sure I really get to understand the use case, but if you're tired just come [join our team](https://www.moduon.team/jobs/detail/odoo-senior-developer-1)! 😊 

Otherwise please could you elaborate a bit more on the use case?

**Comment by pawamoy** [comment]
Yeah sorry I didn't take time to explain clearly my use case. And I think I won't because Git bundles should work better :slightly_smiling_face: 

We can close this and see if others are interested by bare repositories support ^^

Hehehe thanks for the offer, good to know there's an opportunity here ^^
