### ISSUE TITLE
`_secret_questions` setting is undocumented

### ISSUE THREAD

**Issue by sisp** [copier-org/copier#809]
The `_secret_questions` setting

https://github.com/copier-org/copier/blob/608654a03e748a3ed1b032c089e20b2811a0cfd3/tests/test_answersfile.py#L34-L35

is not documented. I think it's a redundant setting since a question supports the `secret` flag as well. In any case, the docs and capabilities should be in sync.

Which solution do you prefer?

1. Document this setting.
2. Remove support for this setting in the code.

**Comment by yajo** [comment]
It's there to provide support for secrets when you're using the simplified questionary format:

```yaml
_secret_questions:
  - password

user: example
password: secret
```

So I guess it's better to document it.

**Comment by sisp** [comment]
Ah, that makes sense. I hadn't thought about the simplified questionary format. I'll send a PR that extends the documentation.
