### ISSUE TITLE
Expand ~ in answers' _src_path

### ISSUE THREAD

**Issue by pawamoy** [copier-org/copier#825]
**Describe the problem**
I have a template in a private git repository ($work's policy). I can't give access to the repository to others, so I went with the solution of packaging the git repo as a bundle inside of a Python package. Users can then install the Python package and use wrapper commands to generate or update projects.

The issue is then that `_src_path` in `.copier-answers.yml` is a local path **specific to the current user** (the Python package + git bundle are installed through pipx, and therefore end up under the user's home).

I tried to replace the user-specific part (`/home/user`) with `~`, but then the path is not detected as a git repo/bundle anymore.
Running an update results in `Updating is only supported in git-tracked templates.`

**Expected behavior**
`~` in `_src_path` should be expanded.

**Environment**
 - OS: Linux
 - Copier version: 6.2.0
 - Python version: 3.8
 - Installation method: pipx + pypi

**Additional context**
I'll send a PR. The fix is quite easy: use `.expanduser()` on paths received in `is_git_repo_root` and `is_git_bundle`. I don't think there's a way to expand higher in the call chain because we're not yet sure if it's a URL or a local path.
Oh and this could be considered a feature request rather than a bug, so feel free to change the associated label 🙂

**Comment by yajo** [comment]
Seems a valid request to me. Thanks for the proposal and for volunteering!

**Comment by pawamoy** [comment]
Hi @yajo, I hope you're doing well 🙂 Tell me: would it be possible to release a new version with this feature? Or were you hoping to pack more things in the next release?
