### ISSUE TITLE
copier always using tag, even locally with dirty changes

### ISSUE THREAD

**Issue by FlorianLudwig** [copier-org/copier#834]
**Describe the problem**

When using `copier` with a local repository that contains tags, it always uses the latest tag instead of the current checkout.

Confusingly, it prints a warning that it does use dirty local changes - but does then proceed to not use them:

```
copier template-python-project test
/home/f.ludwig/.local/pipx/venvs/copier/lib64/python3.10/site-packages/copier/vcs.py:156: DirtyLocalWarning: Dirty template changes included automatically.

[...]

Copying from template version 0.0.3
```

**Template**

**To Reproduce**

1. git clone a template with tags
2. make local changes
3. run `copier` on local repo

**Expected behavior**
Use local changes (or have flag to choose)

**Environment**
 - OS: linux
 - Copier version: 6.2.0
 - Python version: 3.10.7
 - Installation method: pipx

**Comment by yajo** [comment]
https://copier.readthedocs.io/en/latest/generating/#templates-versions explains this expected behavior

**Comment by pawamoy** [comment]
In short: use `copier -r HEAD` to include unstaged/uncommitted modifications.
