### ISSUE TITLE
No copier v7.0.0 in pypi repository

### ISSUE THREAD

**Issue by lalmei** [copier-org/copier#842]
**Describe the problem**
copier v7.0.0 not pushed the pypi
Seems the CI failed before push during pytest
**Template**

**To Reproduce**
\
**Logs**

**Comment by yajo** [comment]
Sorry there was a bug in the tests that basically was only gonna happen when v7 were released, so I just released v7.0.1 including #843. It should get published now. Thus, v7.0.0 will never exist on pypi. But I don't think that's a big problem anyway.

Thanks for noticing!
