### ISSUE TITLE
Support Multiple Templates per Repository

### ISSUE THREAD

**Issue by BrutalSimplicity** [copier-org/copier#854]
I would like for `copier` to support multiple templates in a given repository by allowing the subdirectory of the repository to be specified with the vcs ref, and supporting updates by filtering commit history based on the subdirectory and a user-specified suffix/prefix for tags.

Alternatively, I can continue to use single repo per template approach that makes template management more difficult on the user and developer.

**Comment by BrutalSimplicity** [comment]
I've seen this workaround, https://copier.readthedocs.io/en/stable/configuring/#subdirectory, but I don't believe that will support the use case of having different questions per template. Unless it's possible to pull in questions from each subdirectory. If so, that would be 💯

**Comment by BrutalSimplicity** [comment]
nvm, it's in the docs, https://copier.readthedocs.io/en/stable/configuring/#include-other-yaml-files. I think I can work with the combination of those two options.

**Comment by mshafer-NI** [comment]
@BrutalSimplicity, if you figure out a working example, I would be interested in seeing it.

**Comment by BrutalSimplicity** [comment]
Well, I can open this back up. Do you mean the original support in the ticket, or a setup that the configuration supports?

**Comment by mshafer-NI** [comment]
An example layout, I'm interested doing something similar.

**Comment by BrutalSimplicity** [comment]
Hmm, ok. I assume you've seen this.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/5298126/198733232-441d8e85-d03a-4cab-b243-7601a6b145a2.png">

**Comment by mshafer-NI** [comment]
Yes, I played with putting extra `copier.yaml` files in the `_subdirectory`, but didn't seem to get anywhere with that.

**Comment by mshafer-NI** [comment]
(I am currently including a handful of files in the top level `copier.yml` to separate out my questions and each question does a when based on the `_subdirectory` parameter); but this has the downside of everything winding up in every answers file.

**Comment by yajo** [comment]
Maybe yaml anchors can help you reducing repetition.
