### ISSUE TITLE
Copier update unknown switch --vcs_ref

### ISSUE THREAD

**Issue by szebenyib** [copier-org/copier#857]
**Describe the problem**
Using copier update 7.0.1

**Template**
Any template

**To Reproduce**
1. Run `copier update --vcs_ref=HEAD` as specified in the docs
2. Observe error: Error: Unkown switch --vcs_ref

**Expected behavior**
Ref to HEAD working

**Environment**
 - OS:  Arch Linux
 - Copier version: 7.0.1
 - Python version: 3.9.5
 - Installation method: pip in virtualenv
 
**Additional context**
As a side note just after generating from template the update does not work, and refers to a non-existing commit.

**Comment by pawamoy** [comment]
Which part of the docs mention `vcs_ref`?

This part correctly mentions `vcs-ref` with a dash, though it's missing a leading one: `-vcs-ref` instead of `--vcs-ref` https://copier.readthedocs.io/en/stable/configuring/#vcs_ref

**Comment by szebenyib** [comment]
Here: "to update to the latest commit..."
https://copier.readthedocs.io/en/latest/updating/

**Comment by pawamoy** [comment]
The docs seem to be correct: `--vcs-ref=HEAD`.

**Comment by szebenyib** [comment]
Yet this command is not recognised, this is the output I receive when running this:

```
someone@somewhere (git)-[master] % copier update --vcs-ref=HEAD
Error: Unknown switch --vcs-ref
------
copier update 7.0.1

Update a copy from its original template

The copy must have a valid answers file which contains info from the last Copier execution, including the source template (it must be a key called `_src_path`).

If that file contains also `_commit` and `destination_path` is a git repository, this command will do its best to respect the diff that you have generated since the last
`copier` execution. To avoid that, use `copier copy` instead.

Usage:
    copier update [SWITCHES] args...

Hidden-switches:
    -h, --help         Prints this help message and quits
    --help-all         Prints help messages of all sub-commands and quits
    -v, --version      Prints the program's version and quits
```

**Comment by mshafer-NI** [comment]
Options get passed to copier rather than the sub-command.

Try `copier --vcs-ref=HEAD update`

**Comment by szebenyib** [comment]
Ouch, that is true. Thank you, this somehow did not occur to me.
