### ISSUE TITLE
Dynamic answer file naming not working

### ISSUE THREAD

**Issue by yajo** [copier-org/copier#866]
### Discussed in https://github.com/copier-org/copier/discussions/860

<div type='discussions-op-text'>

<sup>Originally posted by **nilsdebruin** November  3, 2022</sup>
Hi all!

It is possible to define an answer file in the copier.yml like for example:

`_answers_file: .copier-answers-copier-template.yml`

It would be really nice if this could be extended with a dynamic value that you could set as a jinja variable like this:

`_answers_file: .copier-answers-copier-template-{{module_name}}.yml`

Where module_name is an answer you can give in copier.yml like:

```
module_name:
  type: str
```

This would make It possible to create multiple instances of a template in the same structure like:

```
root_level/{{module_name_1}}
root_level/{{module_name_2}}
```

This would create two answer files:

```
.copier-answers-copier-template-module_name_1.yml
.copier-answers-copier-template-module_name_2.yml
```

These template instances could then be updated based on these answer files.</div>

**Comment by nilsdebruin** [comment]
@EthanBar if you need any help on this, let me know!
