### ISSUE TITLE
Allow migrations that run on every update

### ISSUE THREAD

**Issue by FlorianLudwig** [copier-org/copier#872]
**Is your feature request related to a problem? Please describe.**
A migration that is executed on every migration

**Describe the solution you'd like**

```
_migrations:
    - version: "*"
```

**Comment by pawamoy** [comment]
Couldn't you use a task then?

**Comment by FlorianLudwig** [comment]
@pawamoy no, tasks are executed after the merge, I want to execute tasks before that. For example deleting the `poetry.lock`

**Comment by yajo** [comment]
Duplicate of #240
