### ISSUE TITLE
Suggested improvements to the update process

### ISSUE THREAD

**Issue by adamcunnington-mlg** [copier-org/copier#877]
Unless I am misunderstanding the intended use of the update process, I think that there might be 3 missing features which would really improve the update experience:
1) When prompted to overwrite a file, instead of just [Y/n] options, have [Y/n/v] where v is for view and it prints out the diff and then prompts the [Y/n/v] again. [cruft update](https://github.com/cruft/cruft) works in this way and it's nice
2) Provide an option to skip tasks. In my case, the tasks do freezing of requirements and installation. I don't want to do this during most updates - especially as the tasks get run twice during an update
3) Default to correct Y/n during overwrite prompts. Currently, it defaults to yes but this default should be i) indicated e.g. emboldened/coloured and ii) False if the file has not changed more recently in the template source. This feels like the most significant point to me - if my destination has made changes to a file, I don't want to overwrite those changes with the template version - I must be misunderstanding what is happening here because this feels fundamental

Thanks for the consideration / your time in responding to these.

**Comment by adamcunnington-mlg** [comment]
Ok, great news, thanks for that.

There is probably also a way to avoid this double execution of a lot of the workload that happens during an update - but great to know something is in development - are there any more details on what is expected and when? Just to manage my expectations and excitement! Loving copier so far.

Thanks

**Comment by pawamoy** [comment]
You can follow the task issue here: https://github.com/copier-org/copier/issues/240.
The suggestion to remove the overwrite prompts was mentioned here: https://github.com/copier-org/copier/pull/562#issuecomment-1081088109, and leads to this PR that was merged: https://github.com/copier-org/copier/pull/807. So I think we're one release away from it?

**Comment by adamcunnington-mlg** [comment]
Thanks @pawamoy, I'll do that and I'll close this issue, thank you.

**Comment by yajo** [comment]
Well, #807 is a bit a different story. It's about having inline merge conflict markers. However it paves the way to not need overwrite prompts anymore too.

I maintain Copier in my free time. I try to commit some hours to it like about once every 2 weeks. Right now I'm focused on finishing #585 before the next release. But as you can guess, there's no real schedule. Help is always appreciated!
