### ISSUE TITLE
Document how to avoid redundant newline at the end of `.copier-answers.yml`.

### ISSUE THREAD

**Issue by huxuan** [copier-org/copier#894]
**Is your feature request related to a problem? Please describe.**

Currently, there is a redundant newline at the end of the generated `.copier-answers.yml` which violate the hook `end-of-file-fixer` in [pre-commit-hook](https://github.com/pre-commit/pre-commit-hooks).

**Describe the solution you'd like**

No redundant newline at the end of `.copier-answers.yml`.

**Describe alternatives you've considered**

N/A

**Additional context**

I tried to find the related code but failed, if with guidance, I am willing to fix this tiny issue if confirmed.

**Comment by yajo** [comment]
Have you tried adding a `-` character at the end of the Jinja expression? 

```jinja 
# Changes here will be overwritten by Copier
{{ _copier_answers|to_nice_yaml -}}
```

**Comment by huxuan** [comment]
@yajo That is brilliant! it works like a charm!

Maybe we should have it as the default sample in documentation [1]? 

And for the issue itself, it can be closed now. Thanks so much!

[1] https://copier.readthedocs.io/en/stable/#quick-start

**Comment by yajo** [comment]
> Maybe we should have it as the default sample in documentation [1]?

Indeed. Let me reopen.

**Comment by huxuan** [comment]
Hi @yajo, I would like to take this issue as my first issue if possible. :-)

Just a little concern that, the changes seem to affect many places, for example, README, docs, tmpl and may test cases. Do we expect to change all of them?

**Comment by yajo** [comment]
The lack of that instruction is not a bug. It's just something that will produce a file with 2 empty lines at the end, which is most likely not what you want, but is not really an invalid yaml file.

So, you can leave all the code and tests as they are. Just update the docs and readme.
