### ISSUE TITLE
copier update doesn't work in GutHub enterprise with SSH url

### ISSUE THREAD

**Issue by mliora** [copier-org/copier#911]
When I'm trying to use copier update in GitHub enterprise with SSH login I'm getting an error that git clone failed 

**To Reproduce**

1. Running copier update`
2. git clone error

Does copier supports github enterprise?

**Comment by yajo** [comment]
There's nothing special to support github enterprise. If you're using the `gh:` prefix, however, that one is only for github.com.

Just pass the full git URL to copier, and it will work just like normal git. Any git repo is enough for copier.
