### ISSUE TITLE
Option to copy without rendering

### ISSUE THREAD

**Issue by johannesloibl** [copier-org/copier#912]
**Is your feature request related to a problem? Please describe.**
I generally like to set the `templates_suffix` option to `""` so all files are rendered by default and then make exceptions for some few files (like cookiecutter does). But copier currently only provides `exclude`, which also skips copying the file.

**Describe the solution you'd like**
Having an option `copy_without_render` to define files/directories that are copied but not rendered would be nice to have.

**Describe alternatives you've considered**
Alternative would be suffixing all template files with e.g. `.jinja`, but considering a template folder with many files, it is annoying to suffix file name.

**Comment by yajo** [comment]
The feature you're requesting can be summarized in "allow copying some files and rendering others". This is actually supported by Copier and it is the default behavior. The system we use for that is the suffix. Just append `.jinja` to the files you want rendered and remove that `templates_suffix: ""` configuration.

At the beginning, it might seem counterintuitive, mostly when you come from cookiecutter. However, it has some benefits:

1. You don't have to read some setting in the config file to understand that the file will be rendered. Just by looking at its name, you'll know it.
2. Your IDE can provide jinja syntax highlighting or autocompletion when it detects that suffix. For example, see https://github.com/samuelcolvin/jinjahtml-vscode.

This follows [the zen of Python](https://peps.python.org/pep-0020/):

> There should be one-- and preferably only one --obvious way to do it.

Also remember that Copier is not cookiecutter. It has some different features and templates are not inter-compatible.

So I'll kindly reject this feature request. Thanks for it anyways!

**Comment by pawamoy** [comment]
You can also use Jinja's `raw` tags:

```
{% raw %}
Nothing {{ here }} will get rendered
{% endraw %}
```
