### ISSUE TITLE
allow to choose if symlinks should be copied as symlinks

### ISSUE THREAD

**Issue by AdrianFreundQC** [copier-org/copier#937]
**Describe the problem**
I have a copier template that has a `CHANGELOG.rst` file in the template root and a symlink to it in its `docs/` folder. After running `copier copy` the generated project ends up with a second copy of `CHANGELOG.rst` in the `docs/` folder instead of a symlink to it.

**Template**

https://github.com/AdrianFreundQC/copier-symlink-demo
Also as a zip here: [copier-symlink-demo-main.zip](https://github.com/copier-org/copier/files/10511794/copier-symlink-demo-main.zip)

**To Reproduce**

1. Run `copier copy https://github.com/AdrianFreundQC/copier-symlink-demo out`
2. Run `ls -l out/`
3. See that `symlink.txt` is not a symlink

**Logs**

<details>

```
$ copier copy https://github.com/AdrianFreundQC/copier-symlink-demo out
No git tags found in template; using HEAD as ref

Copying from template version 0.0.0.post1.dev0+9ac1db8
    create  .
    create  symlink.txt
    create  original_file.txt

$ ls -l out/
total 16
-rw-r--r--@ 1 adrian  staff  12 Jan 26 17:33 original_file.txt
-rw-r--r--@ 1 adrian  staff  12 Jan 26 17:33 symlink.txt
```

</details>

**Expected behavior**

Copier should preserve the symlink:
```
$ ls -l out/
total 8
-rw-r--r--@ 1 adrian  staff  12 Jan 26 17:33 original_file.txt
lrwxr-xr-x@ 1 adrian  staff  17 Jan 26 17:36 symlink.txt -> original_file.txt
```

**Environment**
 - OS: macOS Ventura 13.1
 - Copier version: copier 7.0.1
 - Python version: Python 3.11.0
 - Installation method: mamba+conda-forge

**Comment by yajo** [comment]
This is actually a feature that allows you to reuse files in some ways and
reduce code duplication. However indeed it would make sense to make it
optional.
