### ISSUE TITLE
Do not run tasks in --pretend mode

### ISSUE THREAD

**Issue by drewoldag** [copier-org/copier#950]
**Is your feature request related to a problem? Please describe.**
My only task is to `git init` the project that was just created from the provided template. But when running in --pretend mode, there is no directory to `init`.

**Describe the solution you'd like**
Make it optional to run tasks when running --pretend, or just don't run tasks at all.

**Describe alternatives you've considered**

**Additional context**

**Comment by yajo** [comment]
> just don't run tasks at all

I think this is a better solution. Thanks for the report!
