### ISSUE TITLE
Undocumented `envops` settings

### ISSUE THREAD

**Issue by sisp** [copier-org/copier#951]
**Describe the problem**
There is a test that uses 2 undocumented `envops` (i.e. Jinja2) settings: `lstrip_blocks` and `trim_blocks`

https://github.com/copier-org/copier/blob/ba8d2452cd310c3efc48f3213ab9ef8d1a6f6b51/tests/test_normal_jinja2.py#L23-L24

**Template**

https://github.com/copier-org/copier/blob/ba8d2452cd310c3efc48f3213ab9ef8d1a6f6b51/tests/test_normal_jinja2.py#L10-L38

**To Reproduce**

```shell
poetry run pytest tests/test_normal_jinja2.py -k test_normal_jinja2
```

**Expected behavior**

The behavior is fine, but the settings are not documented: https://copier.readthedocs.io/en/latest/configuring/#envops

I think those settings should be either documented or not supported by raising an error when an unsupported setting is used.

WDYT, @yajo?

**Comment by yajo** [comment]
There's a link to upstream docs: https://github.com/copier-org/copier/blob/ba8d2452cd310c3efc48f3213ab9ef8d1a6f6b51/docs/configuring.md?plain=1#L589-L590

And upstream documents those options. So IMHO we can close this...

Please reopen otherwise, thanks! 😊

**Comment by sisp** [comment]
Ahhh, you're right. I mistakenly took the example as a reference of the available options and overread the link to the upstream docs. Thanks! 🙂
