### ISSUE TITLE
Autoselecting version tags

### ISSUE THREAD

**Issue by FlorianLudwig** [copier-org/copier#987]
**Describe the problem**

Given the following git tags in a repo:
```
v1
v1.0
v1.0.1
v1.0.0
```

**To Reproduce**

1. Run `copier copy` on a repo with the above mentioned tags
2. copier will use `v1`

**Expected behavior**
copier will use `v1.0.1`

**Environment**
 - Copier version: 7.0.1

**Comment by FlorianLudwig** [comment]
I can still reproduce this:

```
$ copier --version                                                              
copier 7.0.1

$ copier copy git@github.com:FlorianLudwig/copier-987.git test
$ cat test/.copier-answers.yml                                
# Changes here will be overwritten by Copier
_commit: v1
_src_path: git@github.com:FlorianLudwig/copier-987.git
```

**Comment by sisp** [comment]
The problem is that

https://github.com/copier-org/copier/blob/17135c5f346bb2daad32c40ae43f8790ac50c270/copier/template.py#L264

returns `v1`, probably because multiple tags point to that same commit.

**Comment by yajo** [comment]
That's not a bug then

**Comment by FlorianLudwig** [comment]
@yajo would you accept a new feature to support repos that contain multiple tags on the same commit?

**Comment by FlorianLudwig** [comment]
suggested algorithm:

- get all tags
- filter valid versions
- select tag with longest string
```
tags = git("tag", "--points-at", "HEAD")
tags = filter(valid_version, tags)
tags.sort(key=lambda x: len(x))
```

**Comment by sisp** [comment]
> * filter valid versions
> 
> * select tag with longest string

I think the algorithm should rather be similar to this one:

https://github.com/copier-org/copier/blob/c96ff3cf5ebdea6bbd89f6204c3f1490bb30020c/copier/vcs.py#L103-L129

**Comment by FlorianLudwig** [comment]
@sisp the issue for me is that it does not solve my use-case.

Having tags for branches (e.g. `v1`, `v1.1` and `v1.1.0`) at the same is not too uncommon, I think.

sorting those with by version results in `['v1.1', 'v1.1.0', 'v1']`. So it selects "highest" version first and "least specific" next. Since it's tags on the same commit sorting by "highest" version should not make any difference as all tags are actually the "same" version.

**Comment by yajo** [comment]
> Since it's tags on the same commit sorting by "highest" version should not make any difference as all tags are actually the "same" version.

This is the most important part. Indeed, it doesn't matter which one is selected, for the sake of reproducibility.

It does have a meaning for migrations, but that's not what you were fixing in #1080.

So, let's start with the basics: what is the problem you're trying to solve? 🤔

**Comment by FlorianLudwig** [comment]
@yajo 

I am working in a project where git tags are set automatically. On each release, three tags are generated `vX`, `vX.Y.` and `vX.Y.Z`.

The `vX` and `vX.Y` ones are moving tags - so they are updated to the newest version within this release branch.

This makes it impossible to use copier without manually editing the `.copier-answers.yml` as the `vX` version is always selected by copier as reference.

**Comment by yajo** [comment]
Copier isn't compatible with moving tags. Even less if those tags are valid PEP440 version identifiers. 

If you have moving refs, try using branches for that. Or you could use tags that aren't recognized as version strings.
